### ISSUE TITLE
Introduce Tabs as Feature to Babun

### ISSUE THREAD

**Issue by ArthurZ** [babun/babun#101]
I wish Babun could have the capability to spawn tabs. It is a convenience feature, enhancement.

**Comment by joelray** [comment]
+1

**Comment by jalanb** [comment]
+1

**Comment by jlahijani** [comment]
+1 Would be nice to have tabs without relying on ConEMU or similar.

**Comment by asciireign** [comment]
use tmux instead of reinventing the wheel.
tmux is feature rich and once getting used to it
you can use in on most linux machines and improve your life. :+1: 
But getting rid of minitty as it is a dead base would
make some sense but i dont know what to replace it with.

**Comment by SamuelBeckingham-Cook** [comment]
Mintty is still being actively developed [here](https://github.com/mintty/mintty).  The newer version has some great features too, like running without a border.

However tmux is a great option and works excellent with Babun.
