### ISSUE TITLE
python installed package not visable

### ISSUE THREAD

**Issue by archlight** [babun/babun#104]
it is great tool with nice features. I tried to run python scripts but get modules not found. do i need to reconfigure pythonpath in /cygdrive/c way? cygwin can run python with windows environment variables. something i did wrong?

also occasionally tab auto complete freeze terminal. Thanks

**Comment by tombujok** [comment]
Moved to FAQ

**Comment by eosrei** [comment]
Can you add a link to the FAQ where this is covered? Thanks

**Comment by tombujok** [comment]
New FAQ will be regenerated and deployed soon by @jlupi
