### ISSUE TITLE
X-server and X11 forwarding

### ISSUE THREAD

**Issue by boulund** [babun/babun#105]
I was looking for a way to enable X11 forwarding (when I SSH to remote Linux computers) but couldn't find anything mentioned about this. How is this supposed to work? What can I do to help?

When I connect to a server with `ssh -X user@server` and try to run e.g. `xterm` I just get the following error message:
```
xterm: Xt error: Can't open display:
xterm: DISPLAY is not set
```

I tried installing xterm into babun using pact, like so: ``pact install xterm`` and it installed a  lot of dependencies, but I get the same error message trying to run xterm from my local babun shell. 
I could also mention that I'm using VcXsvr on my Windows 8.1 machine as X-server normally (when using PuTTY) and it works great. I also tried setting `DISPLAY=localhost:10.0` which usually fixes things, but this had no effect in babun:
```
xterm Xt error: Can't open display: localhost:10.0
```

**Comment by tombujok** [comment]
Moved to FAQ. 
It would be great if somebody contributed a plugin with these fixes

**Comment by WASasquatch** [comment]
As a note, I had no issues start xterm! How I did this, right out of the box is I ran a couple commands

`pact install openbox`
`CHMOD 0700 /tmp/uscreens/S-$USER && screen -dmS x bash -c 'startxwin'`
`startx /usr/bin/openbox`
