### ISSUE TITLE
Line ending problem

### ISSUE THREAD

**Issue by yeskarthik** [babun/babun#106]
I installed Node JS (before using babun) and when I try to run npm from babun/zsh I get the following error.

 npm
/cygdrive/c/Program Files/nodejs/npm: line 2: $'\r': command not found
/cygdrive/c/Program Files/nodejs/npm: line 4: $'\r': command not found
/cygdrive/c/Program Files/nodejs/npm: line 5: syntax error near unexpected token `$'in\r''
'cygdrive/c/Program Files/nodejs/npm: line 5: `case `uname` in

Guess this problem will also come up for other packages having \r line endings

**Comment by deric** [comment]
Babun virtually changed line endings to CRLF in all files in my project (thousands of useless changes) when directory is symlinked outside of cygwin. When I clone code directly into cygwin home it seems to be ok.

**Comment by miqdadalik** [comment]
It might be related to https://github.com/babun/babun/issues/309
