### ISSUE TITLE
Make it attachable to ConEmu

### ISSUE THREAD

**Issue by Arttii** [babun/babun#111]
Hi,
Was wondering if it possible to run this in ConEmu. My Conemu usually takes over consoles, but not this one. Would be kinda great. Specifically I us

**Comment by b-luu** [comment]
@chrnola: I ran into exactly the same issue. It was driving me crazy so you just saved my day !!

**Comment by carl-menezes-aql** [comment]
@chrnola Thank you so much! This was the one thing that prevented me from making Babun my default task in ConEmu
