### ISSUE TITLE
Application initialization failed: no display name and no $DISPLAY environment variable

### ISSUE THREAD

**Issue by lpalli** [babun/babun#130]
If it is possible how we must configure babun to use graphical tools like gitk ou git gui?
The installation work fine but the execution causes an error message:
```
Application initialization failed: no display name and no $DISPLAY environment variable
Error in startup script: invalid command name "tk_messageBox"
    while executing
"tk_messageBox  -icon error  -type ok  -title "git-gui: fatal error"  -message $err"
    invoked from within
"if {[catch {package require Tcl 8.4} err]
 || [catch {package require Tk  8.4} err]
} {
        catch {wm withdraw .}
        tk_messageBox \
                -icon error \
                -typ..."
    (file "/usr/lib/git-core/git-gui" line 34)
```

**Comment by oswaldo** [comment]
Actually that is not an issue.

You can use pact to install the required x packages. I believe I have done the following in my instance:

`pact install xinit tcl-tk`

Then launch the xserver with for instance:

`startxwin`

In another terminal, according to this documentation you should create the following environment variable:

`export DISPLAY=:0.0`

And then ssh with the -Y flag.
