### ISSUE TITLE
Start in current working directory

### ISSUE THREAD

**Issue by LukaszWiktor** [babun/babun#131]
Is it possible to set babun's working directory to the same location from which it was invoked? It would be very useful when I'm in a windows comman line (cmd.exe) and want to switch to babun and stay in the same directory. 

![image](https://cloud.githubusercontent.com/assets/2964543/3012909/2d4536a2-df40-11e3-99a5-a8f6713f2123.png)

**Comment by tombujok** [comment]
Duplicate of #183

**Comment by soulcreate** [comment]
Add in end of file "~/.babunrc"
```
cd /need/foolder/it
```

**Comment by ZenoArrow** [comment]
@soulcreate Isn't part of the issue that the ~/.babunrc is being created from scratch on every new computer you use Babun on?

**Comment by r3b00t909** [comment]
its working but actually shunt the "Open Babun Here" context menu entry

**Comment by Guiguillermo** [comment]
To keep the "Open Babun Here" context menu entry working, you can add it to "~/.babunrc" :

if [ `pwd` = "[default_folder]" ]
then
        cd /need/foolder/it
fi

(default_folder should be your home folder : /home/[user]).
