### ISSUE TITLE
BLODA software

### ISSUE THREAD

**Issue by juan-manuel-alberro** [babun/babun#132]
Hello,

The daily babun check give me always:

```
Prompt speed      [SLOW]
Hint: your prompt is very slow. Check the installed 'BLODA' software.
Connection check  [OK]
Update check      [OK]
```

How can I fix the prompt speed?
Thanks.-

**Comment by 5moufl** [comment]
Here's the list: https://cygwin.com/faq/faq.html#faq.using.bloda

**Comment by wtanksleyjr** [comment]
Is there any way an explanation of "BLODA" can be provided, so that this message can make sense and therefore be memorable?

**Comment by 3013216027** [comment]
@wtanksleyjr Maybe this is helpful:see_no_evil:: http://babun.github.io/faq.html#_what_is_bloda_software

**Comment by nolifede** [comment]
the same problem, how to fix?
