### ISSUE TITLE
Not the same git diff on babun and git bash, why ?

### ISSUE THREAD

**Issue by Johann-S** [babun/babun#136]
Hi,
I run the same command on git bash and babun, but the result is different and babun doesn't give me the right result.
Can you help me to understand why ?

![screenshot](https://cloud.githubusercontent.com/assets/1689750/3024119/5f082448-dff3-11e3-95d5-6e9522fbaf00.jpg)

**Comment by williamlv** [comment]
I have same problem, It's works, thank you jlupi!

**Comment by reetmoon** [comment]
thx very much to jlupi~

**Comment by Lynn-cc** [comment]
I have the same problem.
Our project is on Windows platform so that we set the `core.autocrlf` to `false`.
I have checked that my gitbash and babun are both setted to `false`, files' diffences still there.
How could I solve this problem ?
