### ISSUE TITLE
Babun check fails

### ISSUE THREAD

**Issue by dogrizz** [babun/babun#138]
Hi
I am behind restrictive corporate proxy. 
But thanks to cntlm and connect.c I am able to connect with most of stuff to outside world
(git wget curl pact etc.) but I can't run babun check or babun update without failure.
I set check time-out to 10 seconds but it doesn't matter as it fails pretty immediatly.
Is there anything that pops into your mind that I should check ?

**Comment by madiot** [comment]
Hi, 

behind an apparently windows proxy, i had to tweak curl cmdline from 
    curl --silent --connect-timeout 4 --location 
     https://raw.githubusercontent.com/babun/babun/release/babun.version
to 
    curl --silent --connect-timeout 4 **--proxy-ntlm** -x 'http://user:passwd@myproxy_host:myproxy_port' 
     --location https://raw.githubusercontent.com/babun/babun/release/babun.version

see the man curl for details

from http://stackoverflow.com/questions/7734518/how-to-set-up-git-to-get-through-a-proxy
adding this in ~/.curlrc seemed to work
proxy = proxy.proxyhost.com:8443
proxy-user = user:pass
proxy-ntlm = true
noproxy = localhost,127.0.0.1
