### ISSUE TITLE
Installation issue - cygiconv-2.dll error

### ISSUE THREAD

**Issue by davidjorgensen** [babun/babun#143]
Hello

I am getting this error after inflating files.
[Image](http://bit.ly/1noGAz1)

I am running Windows 8.1 (x64). It's working fine on my Windows 7 laptop.

Any ideas?

Much appreciated
Thanks in advance.

**Comment by diegoponciano** [comment]
Quick question: I'm going through a similar problem, and I can't deactivate my antivirus (company PC).
Is there a way I can tell babun to load bash instead of zsh before it starts?
Maybe editing .babunrc?
Thanks

**Comment by xjlin0** [comment]
How about using Console2 to start Bash in Babun?
http://blog.msbbc.co.uk/2009/11/configuring-console-2-and-bash-with.html

**Comment by dandiulto** [comment]
I've reinstalled the cygwin inside babun - lookup in update.bat
- fetch version from https://raw.githubusercontent.com/babun/babun-cygwin/master/cygwin.version
- fetch https://raw.githubusercontent.com/babun/babun-cygwin/%CYGWIN_VERSION%/babun-cygwin/setup-x86.exe -> https://raw.githubusercontent.com/babun/babun-cygwin/1.7.35/babun-cygwin/setup-x86.exe
- and finally - setup-x86.exe --quiet-mode --upgrade-also --site="%MIRROR%" --no-admin --no-shortcuts --no-startmenu --no-desktop --root="%CYGWIN_HOME%" --local-package-dir="%DIST_DIR%"
in dist directory inside babun
and installation fixed it

before that update and other bat's gave me an errors
