### ISSUE TITLE
gnome-terminal as default [enhancement]

### ISSUE THREAD

**Issue by rlvesco7** [babun/babun#144]
Hi there, 

I'd recommend providing gnome-terminal as a default terminal if possible, or at least an alternative. I got this working perfectly with cygwin on my old computer, but it's a pain to setup. If I recall I needed to get some packages from cygwin-ports. 

The benefit is that you get TABS and a bunch of other goodies. Also X-11 apps can be launched from it too since it requires the cygwin x-server. Also, since this is often the default terminal on many linux boxes, there would less of learning curve for people going back and forth.

**Comment by tombujok** [comment]
I get the idea, but there's not been any interest in this feature. 
If you would like follow on that a patch or config steps would be appreciated.
Closing for now - feel free to reopen should you work on it a bit (contributions appreciated as always :))
