### ISSUE TITLE
Fake sudo would be helpful

### ISSUE THREAD

**Issue by runvnc** [babun/babun#146]
Any chance you can add a fake `sudo` as suggested here http://superuser.com/questions/122418/theres-no-sudo-command-in-cygwin

```bash
#!/usr/bin/bash

"$@"
```

**Comment by tombujok** [comment]
Interesting feature - will be added in the forthcoming release.
Thanks for your contribution!

**Comment by cpicon92** [comment]
Worth noting: you can also put `cygstart --action=runas "$@"` in `/usr/bin/sudo` to actually run the command with admin privileges
