### ISSUE TITLE
Can I install virtualenvwrapper using babun's python?

### ISSUE THREAD

**Issue by kesco** [babun/babun#147]
I have used virtualenvwrapper in Ubuntu to manager my python packages. I want to used virtualenvwrapper in the Windows Platform, too.

**Comment by dragon788** [comment]
@kesco I followed most of the instructions here (other than getting the latest setuptools from PyPi. http://atbrox.com/2009/09/21/how-to-get-pipvirtualenvfabric-working-on-cygwin/

**Comment by tombujok** [comment]
Thanks for your comments guys!
Info moved to FAQ.
