### ISSUE TITLE
ps option -U and -o unknown

### ISSUE THREAD

**Issue by Brottweiler** [babun/babun#172]
I use Prezto instead of Oh-My-Zsh, and the [SSH module checks if SSH-agent is running](https://github.com/sorin-ionescu/prezto/blob/master/modules/ssh/init.zsh#L28) when I open babun. This works on linux, because it uses `ps -U` to check if it's running for my user, but the `-U` option doesn't exist in ps in babun.

This is how the SSH module looks like at the part where it checks if SSH-agent is started.
```sh
# Start ssh-agent if not started.
if [[ ! -S "$SSH_AUTH_SOCK" ]]; then
  # Export environment variables.
  source "$_ssh_agent_env" 2> /dev/null

  # Start ssh-agent if not started.
  if ! ps -U "$USER" -o pid,ucomm | grep -q "${SSH_AGENT_PID} ssh-agent"; then
    eval "$(ssh-agent | sed '/^echo /d' | tee "$_ssh_agent_env")"
  fi
fi
```

`ps --help` shows that `-U` and  `-o ` does not exist as options. Is there a package where these options are included?

**Comment by tombujok** [comment]
Thanks for feedback @jlupi 
Moved to FAQ and closed.
