### ISSUE TITLE
Support Windows standard %HOME% location

### ISSUE THREAD

**Issue by 13rac1** [babun/babun#173]
I just updated Bubun and it stopped working with the following error:

```
\Users\username: No such file or directory
```

I debugged a little bit and decided the best path would be re-installation. I downloaded the most recent dist file babun-1.0.1-dist.zip, deleted \Users\username\.babun, started the install.bat and I was greeted with this message:

```
[babun] Installing babun
[babun] WARN: Windows HOME environment variable is set to: C:\Users\username
[babun] WARN: ---------------------------------------------------------------
[babun] WARN: FULL COMPATIBILITY CANNOT BE GUARANTEED WHEN 'HOME' IS SET
[babun] WARN: YOU MAY RUN INTO MANY ISSUES THAT CANNOT BE FORESEEN...
[babun] WARN: ---------------------------------------------------------------
[babun] WARN: It's recommended to remove the HOME variable and try again.
[babun] WARN: If you are running the installer from a cmd.exe - restart it.
[babun] WARN: Otherwise the ENV variables will not be propagated to cmd.exe
Do you really wish to proceed (Y / N)?
```

I've had no issues with having a HOME variable set to C:\Users\username until the recent update. Is there a recommended method to make babun/cygwin and Windows share a user profile/home directory?

**Comment by coccoinomane** [comment]
I guess not...

**Comment by arctelix** [comment]
I have also been using HOME=%USERPROFILE% with no issues.  It would be nice to suppress this SCARRY warning...
