### ISSUE TITLE
Question: Best way to disable babun daily check

### ISSUE THREAD

**Issue by jktravis** [babun/babun#177]
What's the best way to disable the daily check? Or at least the prompt speed check?

**Comment by findepi** [comment]
@tombujok,

as a matter of feedback -- I wouldn't disable the check if frequency was configurable. 
I work on Linux most of the time and open console in Windows quite rarely. So "every 24h only" means "everytime" for me.

**Comment by KevinSheedy** [comment]
@tombujok 
Again, just my feedback:
I found this slow and annoying enough that I was tempted to stop using babun altogether. It would be great if it could be changed to provide a better user experience. Run it in the background or on shutdown or something.
