### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by Pherocity** [babun/babun#179]
Is there a config to change the default colors?  Current scheme doesn't work with some legacy software I have to deal with.

**Comment by aloisdg** [comment]
I did. You can change the color by editing the `.minttyrc` file.

For example for the `paraiso`  theme:

```
ForegroundColour=163,158,155
BackgroundColour=47,30,46
CursorColour=163,158,155
Black=47,30,46
BoldBlack=119,110,113
Red=239,97,85
BoldRed=249,155,21
Green=72,182,133
BoldGreen=65,50,63
Yellow=254,196,24
BoldYellow=79,66,76
Blue=6,182,239
BoldBlue=141,134,135
Magenta=129,91,164
BoldMagenta=185,182,176
Cyan=91,196,191
BoldCyan=233,107,168
White=163,158,155
BoldWhite=231,233,219
```

I got it with the tool [base16-builder](https://github.com/base16-builder/base16-builder):

```bash
$> base16-builder -s paraiso -t mintty -b dark
```

Disclaimer: I am working on the project.
