### ISSUE TITLE
Compdef error printed at start after adding plugins to zshrc file

### ISSUE THREAD

**Issue by robcsi** [babun/babun#181]
Hi,

I'm using latest babun version (1.0.1), and I've modified my .zshrc file to include more plugins for oh-my-zsh.

Here it is: https://github.com/robcsi/dotfiles/blob/master/.zshrc
Actually, lines are not included from line number 70 to end. Practically what I've done after installing babun, is just added more plugins.

After restarting babun for the changes to take effect, it prints these lines before giving me the prompt.

compdef: unknown command or service: git
compdef: unknown command or service: git
compdef: unknown command or service: git
compdef: unknown command or service: git
compdef: unknown command or service: git
compdef: unknown command or service: git
compdef: unknown command or service: git

I've tried removing plugins one-by-one, but the same appears; even if I revert the file to original content, the messages are shown.

What can be done to remove them?

Keep up the good work, and thanks,
robcsi

**Comment by dragon788** [comment]
@robcsi You might also try the steps here to see if there are any permissions issues. https://github.com/robbyrussell/oh-my-zsh/issues/630#issuecomment-70291622

**Comment by gdvallance** [comment]
I have this problem too.

The fix in: http://babun.github.io/faq.html *works* i.e.
``` 
$ compinit
cp .zcompdump .zcompdump-$HOSTNAME-5.0.2
```

**OR/**
 
```
$ compinit
```

However, in my case **the fix is not permanent**. If I close and reopen the shell the problem comes back. 

Any clues to a permanent fix? 

Thanks.

**Comment by TommyDevAll** [comment]
Same for me... do you have a permanent fix?
