### ISSUE TITLE
cannot chmod or chgrp files on windows drive (C)

### ISSUE THREAD

**Issue by giuspe** [babun/babun#182]
Hi there,

I'm using babun in standard configuration (out-of-the-box, zsh) on a 64b Windows 7 and I've got some .sh files in my web development directory (on my main Windows drive) that I'd like to make executable.

note: command execution goes on without any problem, I'm simply not able to browse to the command via "tab" shots: I type  ./sync.to[tab] and I get no fancy oh-my-zsh auto completion, suggestions, etc.

I actually see all the files owned to [myuser]:None; if I try

   > chmod +x [...] 

or

   > chmod 755 [...]

I get a " Permission denied" message (running babun as regular user) or nothing (running it as Administrator).

if I try a

   > chgrp Users [...]

I don't get anything, but it doesn't work.

thanks for your work and your support.

**Comment by tombujok** [comment]
Already moved to FAQ
