### ISSUE TITLE
babun update - not a git repository

### ISSUE THREAD

**Issue by Derheynn** [babun/babun#184]
hey :)

When i'm trying to update babun using babun update, i get the following error:

fatal: Not a git repository: '/usr/local/etc/babun/source/.git'
Error on or near line 40, last command 'git --git-dir="$babun/source/.git" --work-tree="$babun/soure" reset --hard';

Any idea ?

**Comment by tombujok** [comment]
Occurred once only. Plz reopen if reoccurs.
