### ISSUE TITLE
"C:\" as target directory on installation fails

### ISSUE THREAD

**Issue by strburst** [babun/babun#185]
![screenshot 2014-07-26 10 27 32](https://cloud.githubusercontent.com/assets/5883232/3711335/099b9310-14d1-11e4-97ab-c934028cf228.png)

The arguments to the installation script are on the last line. `C:\` (without quotes) also fails. This looks like a problem with parsing the path; it's coming out as `C:\"`.

![screenshot 2014-07-26 10 55 12](https://cloud.githubusercontent.com/assets/5883232/3711415/de4cb8f2-14d4-11e4-9e33-af1ac6581270.png)

`C:`, also fails, but only at the end. The paths look weird here too. An empty folder, `.babun`, is produced.

![screenshot 2014-07-26 10 58 55](https://cloud.githubusercontent.com/assets/5883232/3711428/68d12f30-14d5-11e4-87a8-916ae6023355.png)

I get this when running it a second time. This is despite `.babun` being empty.

I also have a side issue: setting the installation path as `C:\babun` installs files in `C:\babun\.babun`, which I think is odd. I'm used to installers putting things directly in the specified folder. This is how I stumbled on this issue.

**Comment by tombujok** [comment]
Thanks, moved to FAQ
