### ISSUE TITLE
Portable Profile

### ISSUE THREAD

**Issue by ZenoArrow** [babun/babun#190]
The feature to install to a custom directory is really good, ended up installing babun to a USB flash drive yesterday. However, this brought up a subsequent issue. When moving between computers, the user I'm logged in as changes. Currently, when babun starts it seems to check for profile config files on the local computer, and ends up creating a brand new profile each time.

Is it possible to have a configuration option that installs the shell config files in a roaming/portable profile stored in the same directory as the babun install? Also, it would be great if you could set to only use this portable profile at install time. Would solve a number of issues with user permissions as well (see here... http://codingwithspike.wordpress.com/2012/08/02/making-a-truly-portable-cygwin-install-working-around-drive-letter-and-file-permission-issues/ ).

**Comment by tombujok** [comment]
Seems legit, but requires a lot of testing. 
It doesn't seem to be a "common" requirement.
Please reopen if anybody feels interested in coding up this feature.

**Comment by AuthorProxy** [comment]
I have all programs fully portable or with portable profiles, so it is the single thing that stop me from using babun. Don't funny to setup the same environment on all computers, from scratch..

**Comment by majidaldo** [comment]
i'd like this bc i would like to have a babun installation for each project i work on..or at least have some concept of a user to create some isolation.

**Comment by Dod9ger** [comment]
Still no one up to this feature ? (Can´t do on my own  :( )
Being portable would be great to for using babun-installation from a dropbox/owncloud/onedrive etc. and would ease things up when you switch between various windows-machines from time to time...

**Comment by soulcreate** [comment]
+1

**Comment by tvollstaedt** [comment]
+1

**Comment by unsignedzero** [comment]
Do we know if this feature will be implemented? I know there are tools such as [CygwinPortable](https://github.com/ntmoe/CygwinPortable) to make Cygwin portable.

**Comment by kenijo** [comment]
I agree, cmder and cygwin can be portable, I would love it too

**Comment by shnbwmn** [comment]
> It  doesn't seem to be a "common" requirement.
A lot of people are switching to a portable setup. It's great to be able to completely reinstall Windows or work on another computer and only have to install/configure a handful of programs, while everything else resides on a trusty external.

**Comment by fossum** [comment]
:+1:

**Comment by MrHappy** [comment]
+1

**Comment by flick36** [comment]
+1

**Comment by ZenoArrow** [comment]
With regards to 'requires a lot of testing', I've thought about it and it strikes me it's actually a very simple feature to implement, and doesn't require a lot of testing.

There are two changes required:

1. The installer needs a checkbox to 'Set up profile in babun directory'. This indicates a ".profile" folder should be created in same directory specified for the babun install.

2. When babun starts up, it first looks for a ".profile" folder in the babun directory. If it doesn't find one, it looks in the standard folder it uses now. If it finds one in the standard folder it uses that one, if not it creates a ".profile" folder in this standard directory.

No other changes are required for this to work. Can someone point me in the direction of the code responsible for finding the profile folder at start up?

**Comment by unsignedzero** [comment]
@ZenoArrow Here's a grep search of all files that have ".profile" in it. I'd start with the bolded one above and work your way down. I'd say ignore the documents below.

**babun-core/plugins/core/install.sh**
babun-core/plugins/core/src/babun.bash
babun-core/plugins/core/src/babun.zsh
babun-cygwin/cygwin.groovy
babun-dist/install/install.bat
babun-dist/start/uninstall.bat
babun-doc/adoc/_faq.adoc
babun-doc/adoc/_installation.adoc
babun-doc/adoc/_usage.adoc

**Comment by 1-61803** [comment]
+1

**Comment by QiangF** [comment]
+1

**Comment by woodgear** [comment]
+1

**Comment by waldens** [comment]
+1

**Comment by damajor** [comment]
+1

**Comment by DovaMerith** [comment]
+1

**Comment by seredasv** [comment]
+1
