### ISSUE TITLE
Command "cmd" gives strange output

### ISSUE THREAD

**Issue by Chris2011** [babun/babun#201]
I use Windows 7 x64 and when I open babun.bat and type cmd I got this output:

![babuncmdoutput](https://cloud.githubusercontent.com/assets/795658/4459565/5888a7c4-48ac-11e4-9f1d-c35c33777b14.png)

Regards

Chris

**Comment by gdela** [comment]
I have similar issue when running bat scripts that does not turn off echo:

    { ~ }  » echo 'date /t' > print-date.bat                                                        ~
    { ~ }  » ./print-date.bat                                                                       ~
    
    %{)g[blue]%}{ %c } \
    %{)g[green]%}date /t
    2016-03-16

When echo is turned off everything is fine:

    { ~ }  » echo '@echo off\ndate /t' > print-date.bat                                             ~
    { ~ }  » ./print-date.bat                                                                       ~
    2016-03-16

The bat script gives correct output when run from windows command line.

**Comment by Chris2011** [comment]
Now I use the native shell of Windows, WSL. I don't need babun anymore. But we can keep this ticket open for others. Or we can close it because of inactivity of this plugin, Thx anyway.

**Comment by Chris2011** [comment]
I see that this project is discontinued so I will close the ticket. Thx anyway.
