### ISSUE TITLE
etc/zprofile is being called twice causing CHERE_INVOKING to fail.

### ISSUE THREAD

**Issue by piyooshm** [babun/babun#205]
Hi! I set CHERE_INVOKING=1 in babun.bat similar to what we do for standard cygwin installation for starting the shell in current dir. It didn't work. I tried installing chere package too, but was unsuccessful to start Babun in current dir. On further hacking/debugging, I found that the issue may be due to /etc/zprofile being called twice (I observed that it was called twice when I added an echo statement to the file). It deletes the variable after running the first time, so on the second time, the variable won't be available and it does a cd to ${HOME}. I believe that if you can prevent /etc/zprofile from running twice on startup, it will resolve the issue.

**Comment by tombujok** [comment]
Thanks for the thorough analysis!
Would you like to submit a pull request with a fix? I would merge it and include in the next release.

**Comment by tombujok** [comment]
Fixed in 1.1.0. 
Release status: #266

**Comment by kubamarchwicki** [comment]
This still seems to be an issue. With babun 1.1.1 I got a following startup log 
```
in /etc/zprofile
in /etc/zshrc
in /etc/zprofile
{ ~ }  »                                                                                        ~
```
So the execution is still `/etc/zprofile` -> `/etc/zshrc` -> `/usr/local/etc/babun.zsh` -> `/etc/zprofile` and the second /etc/zprofile unables chere / xhere to sucessfully pass the path.

Unfortunately - besides tracing  that I have no idea how to approach the change (and the implications). 

I was using 
```
{ ~ }  » babun --version                                                                        ~
babun version 1.1.1
Created and maintained by Tom Bujok (@tombujok)
Copyright (c) 2014-2015.
```

**Comment by kubamarchwicki** [comment]
One more thing. This happens when I run babun from the shortcut `C:\Windows\system32\cmd.exe /c "C:\Users\jmarchwicki\.babun\babun.bat"`

However, if I click already open icon and run `Terminal` - which is a shortcut to `mintty.exe` I got the following errors (with `source /etc/zprofile` in `/usr/local/etc/babun.zsh` commented out). 
With the original `/usr/local/etc/babun.zsh` I don't experience such problem (and also shell here doesn't work). 

```
/usr/local/etc/babun/source/babun-core/tools/plugins.sh: line 105: bash: command not found
Could not start plugin [git]
/usr/local/etc/babun/source/babun-core/tools/plugins.sh: line 105: bash: command not found
Could not start plugin [core]
/usr/local/etc/babun/source/babun-core/tools/plugins.sh: line 105: bash: command not found
Could not start plugin [cygdrive]
/cygdrive/c/Users/jmarchwicki/.oh-my-zsh/oh-my-zsh.sh:3: command not found: env
/cygdrive/c/Users/jmarchwicki/.oh-my-zsh/lib/theme-and-appearance.zsh:9: command not found: uname
/cygdrive/c/Users/jmarchwicki/.oh-my-zsh/lib/theme-and-appearance.zsh:13: command not found: uname
compaudit:132: command not found: getent
{ system32 }  »                                                      /cygdrive/c/Windows/system32
```

Having traced that (obviously by accident) I'm rather lost with what's going on but I hope smb will find it helpful (feels like tester ;>)
