### ISSUE TITLE
Possible to use fish shell?

### ISSUE THREAD

**Issue by Chris2011** [babun/babun#206]
I very like the feature with the auto completion what the fish shell has: http://ridiculousfish.com/shell/images/autosuggestion.png. As for that, the problem is, that this is not a package, which I can install or? I only figure out, that this is a common function inside the fish shell. I installed fish (pact install fish). No problem via installation, but when I type "fish", nothing happens, I got a new empty line but without fish features. So my question is, is it possible to use fish inside babun or not?

Regards

Chris

**Comment by Taconut** [comment]
:+1:

**Comment by tombujok** [comment]
Generally it should work, but it has to be tested thoroughly. I am not sure if fish works flawlessly with Cygwin.

Oh-my-zsh was always a shell to go for babun.
Adding a new shell is a great amount of maintenance work.
If you would like to code it up from scratch, feel free to drop us a line.
For now I am closing this issue.

**Comment by Chris2011** [comment]
I only would like to be the user for this, a lot of other projects are more important for me, than to create a shell implementation ;). Sad to hear it but ok.

**Comment by igitur** [comment]
Also, it would be nice if we can get the babun theme for fish shell. :)
