### ISSUE TITLE
Use of id_rsa key under Windows 8 - Propose to add a note in FAQ

### ISSUE THREAD

**Issue by lucamosca1** [babun/babun#208]
Hi all!
Great work with babun, I?ve discovered just a week ago and since now I'm using only it instead of cygwin and superputty!

I'd like to share with you an issue that could occur in Windows 8 environment: it could happens that usual chmod command to set permission for private key used for ssh connection doesn't work.

To fix this issue I found a solution here for cygwin that works also with Babun
http://superuser.com/questions/397288/using-cygwin-in-windows-8-chmod-600-does-not-work-as-expected

Short story:
From inside your home folder terminal type
mkdir .ssh

and copy your key inside the .ssh folder than:
chgrp -R Users .ssh/
chmod -R 700 .ssh/
chmod 600 .ssh/id_rsa

I think that this tip could be added to your FAQ

cheers

l

**Comment by tombujok** [comment]
Thanks for the solution.
Added to FAQ

**Comment by 2ue** [comment]
3ks
