### ISSUE TITLE
No obvious way to install a specific version of a library i.e. Subsversion

### ISSUE THREAD

**Issue by bigkahuna1uk** [babun/babun#209]
If I do a pact install, then there seems to be no way to install a specific version of a library. It always installs the latest version. 

This is an issue for me with Subversion as I was previously using an older client 1.7.14 but pact automatically installs 1.8.8. I'm hesitant to upgrade the working copy version as it means I would need to update the SVN clients for IDEs I'm using also such as IntelliJ or Eclipse. 

Apart from that, great project. Works straight out of the box :D

**Comment by tombujok** [comment]
Aggregated in #235
