### ISSUE TITLE
Cannot update oh-my-zsh on start

### ISSUE THREAD

**Issue by krzysztof-jelski** [babun/babun#211]
When starting babun I get the following:
```
Executing daily babun check:
Prompt speed      [OK]
Connection check  [OK]
Update check      [OK]
[Oh My Zsh] Would you like to check for updates?
Type Y to update oh-my-zsh: Y
Upgrading Oh My Zsh
Cannot pull with rebase: You have unstaged changes.
Please commit or stash them.
There was an error updating. Try again later?
```
Of course I enter the 'Y' myself.

**Comment by tombujok** [comment]
We need to deal with the windows line endings using dos2unix
git diff gives the following output:

a git diff daje: warning: LF will be replaced by CRLF in custom/example.zsh.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in lib/aliases.zsh.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in lib/bzr.zsh.

**Comment by tombujok** [comment]
Fixed in 1.1.0. 
Release status: #266

**Comment by gliptak** [comment]
I'm seeing this with:

Executing daily babun check:
Source consistent [OK]
Prompt speed      [OK]
File permissions  [OK]
Connection check  [OK]
Update check      [OK]
Cygwin check      [OK]
[Oh My Zsh] Would you like to check for updates? [Y/n]: y
Upgrading Oh My Zsh
Cannot pull with rebase: You have unstaged changes.
Please commit or stash them.
There was an error updating. Try again later?
{ system32 }  » Upgrading Oh My Zsh                                  /cygdrive/c/Windows/system32
{ system32 }  » babun --version                                    /cygdrive/c/Windows/system32 1
babun version 1.2.0
Created and maintained by Tom Bujok (@tombujok)
Copyright (c) 2014-2015.

**Comment by gliptak** [comment]
https://github.com/babun/babun/issues/211#issuecomment-64514731 didn't work.

```
{ .oh-my-zsh } master » git status                                                   ~/.oh-my-zsh
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   lib/spectrum.zsh
        modified:   plugins/catimg/catimg.sh
        modified:   plugins/cloudapp/cloudapp.plugin.zsh
        modified:   plugins/coffee/coffee.plugin.zsh
        modified:   plugins/git-flow-avh/git-flow-avh.plugin.zsh
        modified:   plugins/git-flow/git-flow.plugin.zsh
        modified:   plugins/git-hubflow/git-hubflow.plugin.zsh
        modified:   plugins/git-prompt/gitstatus.py
        modified:   plugins/gradle/gradle.plugin.zsh
        modified:   plugins/history-substring-search/history-substring-search.zsh
        modified:   plugins/laravel/laravel.plugin.zsh
        modified:   plugins/last-working-dir/last-working-dir.plugin.zsh
        modified:   plugins/per-directory-history/per-directory-history.zsh
        modified:   plugins/pj/pj.plugin.zsh
        modified:   plugins/wd/wd.plugin.zsh
        modified:   themes/adben.zsh-theme
        modified:   themes/muse.zsh-theme
        modified:   themes/nicoulaj.zsh-theme
        modified:   themes/pure.zsh-theme
        modified:   themes/sonicradish.zsh-theme
        modified:   tools/check_for_upgrade.sh
        modified:   tools/install.sh
        modified:   tools/require_tool.sh

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by saadfarooq** [comment]
For me it's a mode change. Not sure why it's happening. All the files say:

old mode 100644
new mode 100755

**Comment by floydpink** [comment]
This is what finally helped resolve the filemode issue:

```bash
cd ~/.oh-my-zsh
git config core.filemode false
```

Source: https://github.com/robbyrussell/oh-my-zsh/issues/1984#issuecomment-192612396

**Comment by AnthonyWC** [comment]
I solved it using:
```
git rebase --skip
```

**Comment by aditya43** [comment]
Solved it by doing :

```
cd ~/.oh-my-zsh
git add .
git commit -am "Before updating ZSH"
upgrade_oh_my_zsh
```

Cheers!
