### ISSUE TITLE
Can I ssh into a machine that has babun installed?

### ISSUE THREAD

**Issue by uchagani** [babun/babun#213]
I have a windows machine that has babun installed.  How can I ssh into this machine from a different machine?

**Comment by ylluminate** [comment]
Hmm, seems to be a problem with `babun`. Cygwin sshd installation goes well enough, but hitting walls when using babun on a system (and the cygwin sshd removed).

Here are my results:
```
{ ~ }  » ssh-host-config                                                                        ~

ssh-keygen: generating new host keys: RSA1 RSA DSA ECDSA ED25519
*** Info: Creating default /etc/ssh_config file
*** Info: Creating default /etc/sshd_config file
*** Info: Privilege separation is set to yes by default since OpenSSH 3.3.
*** Info: However, this requires a non-privileged account called 'sshd'.
*** Info: For more info on privilege separation read /usr/share/doc/openssh/README.privsep.
*** Query: Should privilege separation be used? (yes/no) yes
*** Warning: The file /etc/passwd is not readable by all.
*** Warning: Please run 'chmod +r /etc/passwd'.
*** Warning: The file /etc/group is not readable by all.
*** Warning: Please run 'chmod +r /etc/group'.
*** ERROR: Problem with LocalSystem or Adminstrator IDs
{ ~ }  » chmod +r /etc/passwd                                                                 ~ 1
{ ~ }  » chmod +r /etc/group                                                                    ~
{ ~ }  » ssh-host-config                                                                        ~

*** Query: Overwrite existing /etc/ssh_config file? (yes/no) yes
*** Info: Creating default /etc/ssh_config file
*** Query: Overwrite existing /etc/sshd_config file? (yes/no) yes
*** Info: Creating default /etc/sshd_config file
*** Info: Privilege separation is set to yes by default since OpenSSH 3.3.
*** Info: However, this requires a non-privileged account called 'sshd'.
*** Info: For more info on privilege separation read /usr/share/doc/openssh/README.privsep.
*** Query: Should privilege separation be used? (yes/no) yes
*** Warning: The permissions on the directory /var are not correct.
*** Warning: They must match the regexp d..x..x..[xt]
*** ERROR: Problem with /var directory. Exiting.
```

**Comment by ylluminate** [comment]
Any thoughts here on this?  Seems like we're pretty much bound to cygwin proper to get ssh working properly on Windows due to the user bound installation defaults of Babun.

**Comment by jhpaul** [comment]
I was able to get ssh server working with these commands:

[partial source](http://serverfault.com/questions/209480/cgywin-issue-setting-var-permissions-for-ssh)

 ```
chmod +r /etc/passwd                                                  
chmod +r /etc/group    
chmod 755 /var               
chmod ug-s /var
```
 then followed these instructions

 [http://docs.oracle.com/cd/E24628_01/install.121/e22624/preinstall_req_cygwin_ssh.htm#EMBSC281](http://docs.oracle.com/cd/E24628_01/install.121/e22624/preinstall_req_cygwin_ssh.htm#EMBSC281)

>  To configure the SSHD service, run C:\cygwin\Cygwin.bat, and execute the following command:
> ```
> ssh-host-config
> ```
> After running the command, you are prompted the following questions:
> ```
> *** Query: Should privilege separation be used? <yes/no>: yes   
> *** Query: New local account 'sshd'? <yes/no>: yes   
> *** Query: Do you want to install sshd as a service?
> *** Query: <Say "no" if it is already installed as a service> <yes/no>: yes
> *** Query: Enter the value of CYGWIN for the deamon: [] binmode ntsec
> *** Query: Do you want to use a different name? (yes/no) yes/no
>```
> At this point, if you want to use the same name, that is cyg_server, enter no. You are then prompted the following questions:
> 
>```
> *** Query: Create new privileged user account 'cyg_server'? (yes/no) yes
> *** Query: Please enter the password:
> *** Query: Renter:
>```
> However, if you want to use a different name, enter yes. You are then prompted the following questions:
> 
>```
> *** Query: Enter the new user name: cyg_server1
> *** Query: Reenter: cyg_server1
> *** Query: Create new privileged user account 'cyg_server1'? (yes/no) yes
> *** Query: Please enter the password:
> *** Query: Reenter:
>```
> If the configuration is successful, you will see the following message:
> ```
> Host configuration finished. Have fun!
>```

**Comment by billryan** [comment]
@jhpaul Thanks. It works for me.

**Comment by tombujok** [comment]
We need a plugin for that.
Anybody willing to contribute?

**Comment by anchoo2kewl** [comment]
@jhpaul , still works great. Just as a caveat, the above instructions work after I install getent
> pact install getent

Without that, I get an errornet:
```
    Cannot find required command /usr/bin/getent. 
    *** Warning: Please (re)install the getent package.
```

**Comment by hourback** [comment]
Hmm.  Tried all of this and the service won't start after installation.  I'm getting:

```
{ ~ }  » net start sshd                                                                                                                                                    ~ 2
The CYGWIN sshd service is starting.
The CYGWIN sshd service could not be started.

The service did not report an error.

More help is available by typing NET HELPMSG 3534.
```
. . . and . . .

```
{ ~ }  » cygrunsrv -S sshd                                                                                                                                                   ~
cygrunsrv: Error starting a service: QueryServiceStatus:  Win32 error 1062:
The service has not been started.

```

**Comment by jhpaul** [comment]
@hourback can confirm, same error on windows 7, fresh sshd install

**Comment by jhpaul** [comment]
@hourback Have you ever installed SSHD before? Or run MobaXterm? some arrows pointing there on my end.

**Comment by ylluminate** [comment]
It may be worth exploring Microsoft's new `sshd` solution: 
https://winscp.net/eng/docs/guide_windows_openssh_server

**Comment by tteke** [comment]
@hourback Answer here : http://stackoverflow.com/questions/17736096/unable-to-start-cygwin-sshd-service 
solved the problem for me.

**Comment by ylluminate** [comment]
So to be specific (Windows Server 2012 R2), the following allowed this to work after getting the failures noted above after following instructions:

```
chmod 400 /etc/ssh_host_ecdsa_key
net start sshd
```

**Comment by rianquinn** [comment]
I just set this up on a fresh install of Windows 10 in VMWare Fusion, and here is what I did:

run babun as admin and type:
```
babun shell /bin/bash

pact install getent

chmod +r /etc/passwd                                                  
chmod +r /etc/group    
chmod 755 /var               
chmod ug-s /var

ssh-host-config -y
<password>
<password>

chmod 400 /etc/ssh_host_ecdsa_key
net start sshd

netsh advfirewall firewall add rule name='SSH Port' dir=in action=allow protocol=TCP localport=22
```

From there I was able to start a terminal from macOS and login via ssh using:

```
ssh <username>@<ipaddress>
<password>
```

It even seems to work on reboots as well, and I don't have to login on the Windows machine to run ssh.

**Comment by tristan-k** [comment]
@rianquinn  How do I setup the ssh server in order to login with keys

I transferd them with `ssh-copy-id` but they will get stored at `~/.ssh/authorized_keys`. Where is the path to for the `authorized_keys` for `sshd`?

**Comment by rianquinn** [comment]
@tristan-k to be honest I have no idea. We dropped support for babun because it doesn't support 64bit.

**Comment by DeadRabbits307** [comment]
executing `ssh-host-config -y` shows following output:

    ....
    *** Info: called 'sshd'.
    *** Info: For more info on privilege separation read /usr/share/doc/openssh/README.privsep.
    *** Query: Should privilege separation be used? (yes/no) yes
    *** Warning: It appears that you do not have entries for the local
    *** Warning: ADMINISTRATORS and/or SYSTEM sids in /etc/group.
    *** Warning:
    *** Warning: Use the 'mkgroup' utility to generate them or allow "db"
    *** Warning: search of group accounts in /etc/nsswitch.conf
    *** Warning:
    *** Warning: It appears that you do not have an entry for the local
    *** Warning: ADMINISTRATORS (group) and/or SYSTEM sids.
    *** Warning:
    *** Warning: Use the 'mkpasswd' utility to generate it or allow "db"
    *** Warning: search of passwd accounts in /etc/nsswitch.conf
    *** Warning:
    *** ERROR: Problem with LocalSystem or Adminstrator IDs

`net user` gives me following:

    Benutzerkonten für \\xy
    
    -------------------------------------------------------------------------------
    Administrator            DefaultAccount           Gast
    me
    Der Befehl wurde erfolgreich ausgeführt.

Whats the problem?
