### ISSUE TITLE
I can't execute octave under babun

### ISSUE THREAD

**Issue by mszlosser** [babun/babun#214]
pact install octave octave-image
octave --force-gui

**Comment by dcrystalj** [comment]
same problem here

**Comment by xjlin0** [comment]
I have a question:  Octave GUI need full X window support, did you install X windows (server/client)?

**Comment by dcrystalj** [comment]
But what if i need only console version without plot (to get started)
________________________________

**Comment by tombujok** [comment]
Could you try after upgrading babun to 1.1.0?

**Comment by dcrystalj** [comment]
nice! very nice!
if i run startx && octave,  then plot is working but in ascii mode only. is there any workaround?

**Comment by tombujok** [comment]
Nice!
