### ISSUE TITLE
Prompt is slow while babun check says OK

### ISSUE THREAD

**Issue by amosbird** [babun/babun#219]
It's about 1-2 seconds lag time after executing commands like 'ls'.

**Comment by whitneyit** [comment]
I've been experiencing this as well. Even when using just Cygwin by itself

**Comment by ylluminate** [comment]
Same here in both `babun` and `cygwin64`.

**Comment by tombujok** [comment]
Unfortunately it's a Cygwin's "feature" sometimes... 
The only possible answer is: check BLODA: https://cygwin.com/faq/faq.html#faq.using.bloda
Babun is optimized to make the prompt fast - but it's a known problem and often the problem is on your host...

**Comment by ylluminate** [comment]
Yeah, it's a stinker of an issue and is very intermittent.

**Comment by whitneyit** [comment]
I honestly think that its a hardware issue with cygwin. Some machines it
runs flawlessly and others it just locks up for up to 5 seconds at a time

**Comment by salahtahri** [comment]
unfortunatly babun is slow on my laptop i wish there was a easy guide how to fix this, i will keep using cygwin until this problem is fixed....

**Comment by XiangSugar** [comment]
I also met this problem, how can I improve it.
