### ISSUE TITLE
Provide simple mean to install without refering to http://projects.reficio.org/

### ISSUE THREAD

**Issue by rolfschr** [babun/babun#220]
As of now 02Jan2015 14h27 CET, there is no babun subfolder in http://projects.reficio.org/. I don't know how to download the dist zip otherwise. I am sure I can somehow use the babun-dist subfolder from this repo but Git is not even installed on my current machine. It would be great to host the dist file here at github.

**Comment by tombujok** [comment]
Download from the download link
http://projects.reficio.org/babun/babun-dist.zip

Works like a charm.

**Comment by rolfschr** [comment]
Hi Tom,

thanks for the quick reply. I opened this issue exactly because I cannot download from there :/ Visiting http://projects.reficio.org does not yield a subfolder 'babun' and hence no file babun/babun-dist.zip. Maybe this is a local problem here. All I can see there are two folders: p2-maven-plugin/ & soap-ws/. If this is a server issue, I suggest the dist file is better hosted at github.


![downloadnotpissible](https://cloud.githubusercontent.com/assets/1188465/5596843/f52446a8-9297-11e4-82e9-6cfdd14c3a73.png)

![downloadnotpissible_wget](https://cloud.githubusercontent.com/assets/1188465/5596861/3676a344-9298-11e4-9003-1a1303f3bace.png)

**Comment by tombujok** [comment]
You will not see that folder. It's a link rewrite to Bintray, it's hosted
there. You can go directly to Bintray or use wget with redirect option
enabled.

**Comment by rolfschr** [comment]
Hi Tom,

Thanks for you quick reply. For reference: I checked https://bintray.com/tombujok/babun/babun-dist/1.0.1/ (found this via google). I do have the same problems here downloading the file mentioned there. I will check the company's network and report.

**Comment by wolfo** [comment]
All these download links are still not working. Is there a mirror?

**Comment by rolfschr** [comment]
@wolfo 
I still have the problem on the company network but it worked fine at home. Our IT guy suggested it was a problem with the zip file (which I know is not true). My workaround was to download from another location (a.k.a. at home) and put the zip file on another location on the internet from where I could download it later.
