### ISSUE TITLE
support 64bit version of cygwin and babun

### ISSUE THREAD

**Issue by drikin** [babun/babun#234]
I recently found this project. babun is awesome.
I'm currently facing some folk() related issues. I heard this was common cygwin+win8 issue which was resolved by cygwin 64bit.
Do you have any plan to support 64bit version of babun?

**Comment by tombujok** [comment]
No sorry, it was never planned. Too much maintenance work for now.

**Comment by leycec** [comment]
64-bit Babun is unofficially installable by meticulously following the [installation instructions](https://github.com/babun/babun/wiki/64-bit) now documented at the [Babun wiki](https://github.com/babun/babun/wiki).

I can confirm these instructions as working (_more-or-less_) perfectly on a mildly decrepit Windows XP Professional 64 virtual box. Let the geriatric times roll! :older_man:

**Comment by ionelmc** [comment]
Perhaps consider having a 64bit only build? Who uses 32bit nowdays?

**Comment by dohque** [comment]
+1 for having 64bit only
