### ISSUE TITLE
Upgrade or downgrade to a specific version with pact

### ISSUE THREAD

**Issue by tombujok** [babun/babun#235]
See #209 #187

**Comment by chrisgilbert** [comment]
There are some other issues in terms of dependencies also in pact.  For example - I tried the following to upgrade git (1.7.9 is too old to work with our repository):

`pact remove git && pact install git`

This works, but git doesn't work afterwards, as some dependencies need updating too.  At the moment pact ignores dependencies that are already installed if they are any version.

I wasn't able to get it to work at all, other than by using the cygwin install and updating that way - a lot of the packages are hard dependencies, such as libgcc1, which break pact if you remove them.

**Comment by tombujok** [comment]
Duplicate of #229
