### ISSUE TITLE
Is it possible to display full path to current location in prompt?

### ISSUE THREAD

**Issue by BastiTee** [babun/babun#236]
I am used to seeing the full path displayed in Cygwin, e.g.,

`/cygdrive/c/development $ echo "hello world"`

Babun on the other hand shortens that to something like

`{ development } » echo "hello world"`

Is it possible to configure Babun to get the first display style?

**Comment by jlupi** [comment]
Hi

babun is by default configured to display the full path on the right side of the console

![image](https://cloud.githubusercontent.com/assets/4189968/6059157/a3d2527a-ad2e-11e4-9798-ca4e251c4e74.png)

Is this not what you need?

**Comment by BastiTee** [comment]
Hi,

thanks for the reply! 

Yes, I find the right-side path weird :) I'd rather prefer the path on the left side, just like a "normal" unix shell. I also switched to bash as default console, which obviously does not support the path on the right-hand side.

**Comment by jlupi** [comment]
You can customize the prompt if you like. You just have to override the PS1 variable.

You have to do that in the `~/.babunrc` file. 

The current style for bash is defined in `.babun\cygwin\usr\local\etc\babun.bash` and for zsh in `.babun\cygwin\usr\local\etc\babun.zsh` . You can take those as a reference.

Important is not to modify those files as they will be overwritten on every update.

There are plenty of examples on the internet on how to customize the prompt, for example http://www.thegeekstuff.com/2008/09/bash-shell-ps1-10-examples-to-make-your-linux-prompt-like-angelina-jolie/

Please also note that some customization may have impact on the babun's performance, or may even not be displayed correctly. This is a cygwin limitation. But basic settings like colors, paths etc should work fine.

**Comment by tombujok** [comment]
Thanks @jlupi

**Comment by BastiTee** [comment]
Thank you very much for the detailed answer!

**Comment by 1-61803** [comment]
Although according to `babun check` my prompt is `OK`, when I open the first shell it almost always use the `PS1` from `/usr/local/etc/babun.bash` — no problem after that one though. So I had to modify the default setting, as it was getting annoying.

**Comment by jezhee** [comment]
How can I hide the full path on the right side? When I use ls command, it messes up the terminal in some way. I edit the PS1 in both .bashrc and .babunrc, but it dose not take effect.

**Comment by shrmrf** [comment]
try one of the themes under `~/.oh-my-zsh/themes` ...
You might like: `source ~/.oh-my-zsh/themes/afowler.zsh-theme`  (babun version 1.2.0)
