### ISSUE TITLE
windows 10 9926 build when start babun there are three console were opened

### ISSUE THREAD

**Issue by jiamo** [babun/babun#237]
The cygwin has this error before, After update this error disappear in cygwin. But still in babun.

**Comment by mezka** [comment]
I'm having the same problem on Windows 10 build 9926.

![2015-02-21 12_27_20-greenshot](https://cloud.githubusercontent.com/assets/6831866/6314631/0386f69c-b9c5-11e4-8fb0-4f80fa4434b3.png)

**Comment by v-yadli** [comment]
you can update babun just like how you updated Cygwin.

**Comment by mezka** [comment]
What do you mean by update?

![2015-02-22 14_10_25--bash](https://cloud.githubusercontent.com/assets/6831866/6319484/9796e8d8-ba9c-11e4-8b7c-12dd595e61c8.png)

**Comment by mezka** [comment]
Well I've found a workaround for this issue (with a little help of a /g/ anon), go to .babun/cygwin/bin and change mintty.exe to Windows 8 compatibility mode.

**Comment by v-yadli** [comment]
To update babun you'll need the cygwin installer. Simply point the installation target at .babun/cygwin and it will detect your installed packages and update them if necessary.

**Comment by v-yadli** [comment]
Note that you have to use x86 installer. A x64 installer will refuse to destroy the babun installation (lucky enough! :)

**Comment by TimHiggison** [comment]
The suggestion above, "go to .babun/cygwin/bin and change mintty.exe to Windows 8 compatibility mode." worked for me on Windows 10 TP Build 9926.

**Comment by tombujok** [comment]
Fixed - FAQ supplemented
http://babun.github.io/faq/

**Comment by sturgman** [comment]
This suddenly started happening on Win7 as well. Should I file a new ticket? There is no compatibility mode for Win8 on a Win7 machine obviously.
