### ISSUE TITLE
command not found: zstyle

### ISSUE THREAD

**Issue by jdeniau** [babun/babun#238]
Hi,

First of all, thank you for babun, it is quite a great console for windows ;)

I have a small problem for some weeks. When I launch babun, I got this error:
```sh
.oh-my-zsh/lib/completion.zsh:18: failed to load module `zsh/zutil': No such file or directory
.oh-my-zsh/lib/completion.zsh:21: command not found: zstyle
.oh-my-zsh/lib/completion.zsh:26: command not found: zstyle
.oh-my-zsh/lib/completion.zsh:27: command not found: zstyle
.oh-my-zsh/lib/completion.zsh:32: command not found: zstyle
.oh-my-zsh/lib/completion.zsh:36: command not found: zstyle
.oh-my-zsh/lib/completion.zsh:40: command not found: zstyle
.oh-my-zsh/lib/completion.zsh:41: command not found: zstyle
.oh-my-zsh/lib/completion.zsh:44: command not found: zstyle
.oh-my-zsh/lib/completion.zsh:55: command not found: zstyle
compinit:532: command not found: zstyle
```

I tried upgrading babun, zsh or oh-my-zsh but apparently nothing works

Thank you for your help.

**Comment by v-yadli** [comment]
could be a .zcompdump problem. there should be a .zcompdump-$HOSTNAME-$version_of_zsh in your home dir. If that one doesn't exist, zsh will refuse to execute some commands (actually a lot)

**Comment by jdeniau** [comment]
I just checked: the file is here, with the right version of zsh and the right hostname.

**Comment by v-yadli** [comment]
could you try to run compinit to generate the file? I don't know why it gets automatically respawned but I encountered a similar problem when upgrading from zsh 5.0.2 to 5.0.6 and it didn't generate that file for me. Executing compinit manually solved my problem.

**Comment by jdeniau** [comment]
Got this:
```sh
{ ~ }  » compinit                                                                               
compinit:532: command not found: zstyle
```
Maybe I should try to re-install it (but I can continue testing if you want to debug this)

**Comment by v-yadli** [comment]
I'm not sure what happened. Maybe reinstallation would fix it.

**Comment by jdeniau** [comment]
After re-installation, the problem is fixed ;)

Thank you
