### ISSUE TITLE
Cannot start Node

### ISSUE THREAD

**Issue by ArthurZ** [babun/babun#241]
I can start Node in Windows Shell, but in Babun I get error
{ ~ }  » node                                                                                   ~

net.js:156
    this._handle.open(options.fd);
                 ^
Error: EINVAL, invalid argument
    at new Socket (net.js:156:18)
    at process.stdin (node.js:664:19)
    at startup (node.js:145:16)
    at node.js:906:3
What would fix that?

**Comment by vjustov** [comment]
Node no longer supports Cygwin which is what babun is working on top of. [node wiki's](https://github.com/joyent/node/wiki/Installation#building-on-cygwin)

**Comment by jlupi** [comment]
@ArthurZ @vjustov You are right, it is not supported but I was able to build it from sources. I'm not a node developer so I cannot tell you if all works as expected. Could you guys try and let me know? If it works I would add it to the FAQ.

First of all update Babun to the newest version, then follow the steps from https://github.com/babun/babun/issues/216#issuecomment-89526799

**Comment by jlupi** [comment]
Looks like this was fixed in 1.1.0. Feel free to reopen if you still have the problem.
