### ISSUE TITLE
Add ipv6 capable tools, like ping6

### ISSUE THREAD

**Issue by hak8or** [babun/babun#243]
This would be pretty handy considering the slow but steady transition to ipv6.

**Comment by v-yadli** [comment]
This package is not provided in the upstream Cygwin repo. Maybe viable through a wrapper to call native Windows ping with -6?

**Comment by jlupi** [comment]
That would be a nice little feature, perfect for hackergarten.

The other problem with cygwin's ping is that it requires admin rights to execute otherwise you'll get 

> ping: socket: Operation not permitted

I'm wondering if we could get rid of the cygwin's ping.exe and only use the native one.

**Comment by jlupi** [comment]
fixed in  #300 #301
