### ISSUE TITLE
Duplicate call of babun.zsh in /etc/zshrc

### ISSUE THREAD

**Issue by jlupi** [babun/babun#249]
Already fixed in commit https://github.com/babun/babun/commit/b90801bcdc9ac9d0ac998223f57de54bafb8b8c8 but people may still have the duplicated entry in /etc/zshrc

````
source /usr/local/etc/babun.rc
source /usr/local/etc/babun.zsh
source /usr/local/etc/babun.start
source /usr/local/etc/babun.zsh

````

**Comment by tombujok** [comment]
Fixed in 1.1.0. 
Release status: #266
