### ISSUE TITLE
[Looking for volunteers] 1.1.0 release candidate acceptance tests

### ISSUE THREAD

**Issue by jlupi** [babun/babun#251]
We are looking for volunteers who would beta test the 1.0.2 release candidate.

The tests would look like this, that you would:
- backup your current babun instance (just zip and copy the .babun folder)
- change the update branch to candidate (details will follow)
- execute 'babun update' to 1.0.2 and check if everything works as expected
- execute 'update.bat' to update Cygwin core and check if everythings works as expected.

More details as well as the test scenarios will follow.
Who would volunteer to take part in the "acceptance" tests for 1.0.2?

How to switch to candidate branch:
(details will follow)

Tests Scenarios:
(details will follow)

**Just post a reply here if you would like to be included**

**Comment by almorelle** [comment]
Count me in.

**Comment by vanushv** [comment]
Me

**Comment by tonilampela** [comment]
One more volunteer signing up!

**Comment by tombujok** [comment]
Thanks for volunteering guys!
We've just baked an awesome candidate relaese!
@v-yadli @kubamarchwicki @airborn Would you like to join beta tests of the next release, plz ;) ?
@almorelle @vanushv @tonilampela Could you send ma short email at tom.bujok[at]gmail.com?
I will send you the test instructions and the download link to the release candidate. Thanks!

**Comment by tombujok** [comment]
BTW, @jlupi and me will be testing too ;)

**Comment by v-yadli** [comment]
Yeah sure!

Sent from my Sony Xperia™ smartphone

---- Tom Bujok wrote ----

Thanks for volunteering guys!
We've just baked an awesome candidate relaese!
@v-yadli @kubamarchwicki @airborn Would you like to join beta tests of the next release, plz ;) ?
@almorelle @vanushv @tonilampela Could you send ma short email at tom.bujok[at]gmail.com?
I will send you the test instructions and the download link to the release candidate. Thanks!

---

**Comment by airborn** [comment]
You have my axe!

**Comment by kubamarchwicki** [comment]
+1

**Comment by tombujok** [comment]
Tests in progress. Status can be followed here: #266
