### ISSUE TITLE
Cmake just returns to prompt without doing anything

### ISSUE THREAD

**Issue by zumpchke** [babun/babun#252]
`cmake` does nothing but returns to prompt after doing `pact install cmake`. Any way to get debug output?

**Comment by tombujok** [comment]
Consequence of #239. Many packages installed with pact will not work now. Fix will be released within a couple of days maximally. We are already testing the candidate relase...

**Comment by tombujok** [comment]
Fixed in 1.1.0. 
Release status: #266

**Comment by alwyn** [comment]
I am getting the problem with cmake on babun 1.2.0 trying to build tasksh.

**Comment by cfz42** [comment]
I am also getting this issue when trying to build YouCompleteMe

**Comment by JerzySpendel** [comment]
I got the same.

**Comment by nojhan** [comment]
Got the same too. Windows 7, babun 1.2.0, cmake 3.6.2.

**Comment by yzhangcg** [comment]
Got the same issue with babun 1.2.0, windows 10. Essentially all the packages installed by pact quit silently that way with a "127" to the right most of the screen, including cmake, ruby, rails, clang, sqlite3 ... Interestingly, python3-3.4.3 works fine.

**Comment by glennbright** [comment]
^ same problem. Windows 10, babun 1.2.0

its returning 127  (in red)

**Comment by mosynaq** [comment]
Same here! Any way out?

**Comment by cfz42** [comment]
I fixed the issue for weechat by running the `<BABUN_INSTALLDIR>/update.bat` (typically ~/.babun/update.bat) script. Note that I fixed it by manually running the `update.bat` as `babun udpate` didn't find any updates and didn't run the script (which may be broken too).
