### ISSUE TITLE
Package 'git' is broken after update

### ISSUE THREAD

**Issue by kgizdov** [babun/babun#259]
Hi,

I installed 'babun' today and tried to update 'git', as the included version is very old (1.7.x). Firstly, it did not update through 'pact' -> 'git already installed'. So I tried as suggested in the issues here to remove and reinstall,

After 'pact remove git' and 'pact install git', it installed fine (I updated the MD5 to SHA512 fix in pact). However, now 'git' is not a valid command in babun. 'git' returns nothing regardless of operands and other packages return that 'git' is not installed.

Moreover, there is no way of returning 'git' to the older version at all. The only option is complete reinstallation of 'babun' itself. This is very disappointing as I cannot rely on an old version of 'git' got my projects and I also cannot use the new version...

Is there going to be a new release that fixes this soon? Or at least if someone can build from updated source as I do not have a machine configured for building cygwin currently.

Thanks.

**Comment by tombujok** [comment]
We've been working on it for the last two weeks. The release will follow soon, for now reinstall babun to amke git working again.

**Comment by tombujok** [comment]
Fixed in 1.1.0. 
Release status: #266

**Comment by discernment** [comment]
I just had this happen to me.  I was running babun 1.2.0.  I did a `pact update git` and said that it was removing git.  Now I get a 127 error code whenever running git.  It's totally gone!  Babun is worthless to me if git is not available and upgradeable.

**Comment by jcao219** [comment]
@discernment Go to the .babun directory in your Users directory and execute update.bat _as administrator_ . The problem will be fixed.
