### ISSUE TITLE
zsh: child_info_fork 'complete.dll' is already occupied

### ISSUE THREAD

**Issue by jktravis** [babun/babun#263]
Hi. I don't think there was anything installed to change this, but I am on a managed machines, so...

But, after doing a restart to clear up some system resources, I launch Babun and am greeted with this:

          0 [main] zsh 8712 child_info_fork::abort: address space needed by 'datetime.dll' (0x3F0000) is already occupied
    /home/myusername/.oh-my-zsh/tools/check_for_upgrade.sh:37: fork failed: resource temporarily unavailable
          0 [main] zsh 8216 child_info_fork::abort: unable to remap complist.dll to same address as parent (0x4D0000) - try running rebaseall
    /home/myusername/.oh-my-zsh/lib/git.zsh:148: fork failed: resource temporarily unavailable
          0 [main] zsh 4248 child_info_fork::abort: address space needed by 'complete.dll' (0x490000) is already occupied
    grep-flag-available:1: fork failed: resource temporarily unavailable
          0 [main] zsh 4636 child_info_fork::abort: address space needed by 'complete.dll' (0x490000) is already occupied
    /home/myusername/.oh-my-zsh/lib/theme-and-appearance.zsh:9: fork failed: resource temporarily unavailable
          0 [main] zsh 10236 child_info_fork::abort: address space needed by 'complete.dll' (0x490000) is already occupied
    compinit:530: fork failed: resource temporarily unavailable
          0 [main] zsh 6476 child_info_fork::abort: address space needed by 'complist.dll' (0x4D0000) is already occupied
    /home/myusername/.zshrc:85: fork failed: resource temporarily unavailable
    (myusername@localcomputer)[6066] ~ %

I move oh-my-zsh to a new directory and comment out the `source $ZSH/oh-my-zsh.sh` in my `~/.zshrc`. I then get 

    (user@host)[6] ~ % ls
          1 [main] zsh 7552 child_info_fork::abort: address space needed by 'complete.dll' (0x550000) is already occupied
    zsh: fork failed: resource temporarily unavailable
    (user@host)[7] ~ % ls
          1 [main] zsh 6812 child_info_fork::abort: address space needed by 'complete.dll' (0x550000) is already occupied
    zsh: fork failed: resource temporarily unavailable
    (user@host)[8] ~ %

Bash works fine, but only if it's run outside of zsh (e.g. directly from the `cygwin/bin/` folder or replacing my shell in `/etc/passwd`).

I downloaded the latest dist of babun and tried running zsh directly from that package as well to the same effect. Has anyone else seen this issue?

**Comment by jktravis** [comment]
Not sure what the issue was, but it decided to resolve itself. Probably just my machine. Closing.

**Comment by ylecuyer** [comment]
I'm experiencing the same issue

**Comment by jlupi** [comment]
It usually happens when another windows process hijacks one of cygwin's dlls. Maybe your anty-virus?
I am affraid that it's rather OS / cygwin but not babun related. Have a look here http://stackoverflow.com/questions/11107155/how-to-fix-address-space-is-already-occupied-error-on-fetch-commit

**Comment by kytel0925** [comment]
I had the same problem on my Windows 10 with "Kaspersky antivirus" all I did is add the application as a trusted program and done

**Comment by Sieg** [comment]
Same problem with no antiviruses.. But it appears sometimes when more then one instance of console is opened (and running something already at the moment) and im trying to open one more terminal.

**Comment by iammoen** [comment]
I was getting this tonight. Downloaded the install exe again. No dice. Did a rebase. No help. Finally launched the 'update.bat' file. It worked away and when it was done everything was good to go.

**Comment by saccohuo** [comment]
Follow #558 and [this link](https://stackoverflow.com/questions/9300722/cygwin-error-bash-fork-retry-resource-temporarily-unavailable), the problem is solved.
