### ISSUE TITLE
Release 1.1.0 status

### ISSUE THREAD

**Issue by tombujok** [babun/babun#266]
Status of the critical 1.1.0 release:
- candidate release prepared [OK]
- candidate release smoke-tested [OK]
- update from 1.0.1 to 1.1.0 tested [OK]
- install of fresh 1.1.0 [OK]
- acceptance tests by volunteers [IN PROGRESS]

Release will be performed when all steps have been completed.
Expected release date: 04.04.2015 - 10.00 CET

**Comment by tombujok** [comment]
Updated:
- install of fresh 1.1.0 [EXPERIENCING PROBLEMS] -> [OK]

**Comment by harijoe** [comment]
Fresh install to User home : 
Everything okay except 

    { ~ }  » arj --version                                                                        ~ 7
    ARJ32 v 3.10, Copyright (c) 1998-2004, ARJ Software Russia. [28 Dec 2009]
    
    
    Invalid switch: --version

I wonder if the Invalid switch was expected here.

**Comment by jlupi** [comment]
@harijoe thank you for such a quick feedback. I should be more precise in the expected section but yes, it was expected, we just want to see if the package was installed correctly. arj does not have that switch

**Comment by tombujok** [comment]
@harijoe Thanks for testing, please let us know when you test all scenarios - the first scenario is the most important ;)

**Comment by tombujok** [comment]
Expected release date: in 1-2 days

**Comment by tonilampela** [comment]
No errors during the upgrade from 1.0.1 to 1.0.2. I will test with another installation later tonight.

**Comment by tombujok** [comment]
To all beta testers, please report the results in the following format:
Thanks for your tests!

Test Scenario | Status | Comments
------------- | -------------|---------------
Scenario 1 | OK / NOK | ...
Scenario 2 | OK / NOK | ...
Scenario 3 | OK / NOK | ...
Own scenario | OK / NOK | ...

**Comment by v-yadli** [comment]
I think I'm a bit out of sync now... Could you please send me the test instructions? Can't seem to find it, sorry!

**Comment by tombujok** [comment]
You should have got an email, maybe spam? I will ask @jlupi to resend it.

**Comment by jlupi** [comment]
@v-yadli check your mail

**Comment by glennular** [comment]
I tried to switch the candidate version but got the following error:

```
Executing babun update
  upstream  [candidate]
  installed [1.0.1]
  newest    [FORCE]
HEAD is now at 1c30d0f Fixing displayed version - 2
Fetching origin
Fetching origin
Already up-to-date.
Switched to branch 'candidate'
Fixing new line feeds
Making core scripts executable
Installing plugin [dist]
  installed [1]
  newest    [1]
  action    [skip]
Installing plugin [core]
Compatibility fixes [core] version=[0]
Fixing /etc/fstab permissions on /cygdrive
Fixing permissions
/bin/chmod: changing permissions of `/etc/passwd': Permission denied
/bin/chmod: changing permissions of `/etc/postinstall/symlinks_repair.sh.done': Permission denied
Error on or near line 89, last command '/bin/chmod u+rwx -R /etc';
ERROR: Could not update babun!
Error on or near line 58, last command '"$babun"/source/babun-core/tools/update_exec.sh';
```

**Comment by tonilampela** [comment]
Scenario | Status | Comments
------------|------------|--------------
Scenario 1 | OK | Upgraded existing 1.0.1 installation on Win 7. No issues.
Scenario 2 | OK | New installation on Windows 10 Technical Preview. No issues.

**Comment by v-yadli** [comment]
Scenario|Status|Comments
---|---|---
Scenario 1|NOK|Windows 8.1 64bit, domain joined, encounters file permission issues. (See logs below)
Scenario 2|OK|Installs. Several "File not found" errors in "Fixing symlink" stage.
Scenario 3|TODO|
Scenario 4|OK|See below
S4.a|OK|
S4.b|OK|
S4.c|NOK|upstream is [candidate] instead of [master]
S4.d|OK|
S4.e|OK|
S4.f|OK|
S4.g|OK|Cool!
S4.h|OK|
S4.I|OK|Yeeeaah!


Installation log of scenario 1:
```
Installing plugin [core]
chmod: changing permissions of ‘/usr/local/bin/babun’: Permission denied
Error on or near line 12, last command 'chmod 755 /usr/local/bin/babun';
ERROR: Could not update babun!
Error on or near line 61, last command '"$babun"/source/babun-core/tools/update_exec.sh';
➜  ~  ls -la /usr/local/bin/babun
-rwxrwx---+ 1 Administrators Domain Users 4362 Apr  1 13:28 /usr/local/bin/babun
```

**Comment by kubamarchwicki** [comment]
Scenario | Status | Comments 
 --- | --- | --- 
 Scenario 1 | OK | Windows7 Pro 64bit. Service Pack 1 

## Scenario 1 comments:
Step c
{ ~ }  » babun update                                                                           ~
Executing babun update
  upstream  **[candidate]** - not master, but that's minor
  installed [1.1.0]
  newest    [1.1.0]
Babun is up to date
Checking Cygwin version:
  installed [1.7.35]
  newest    [1.7.35]
Cygwin is up to date

**Comment by tombujok** [comment]
@kubamarchwicki that's ok - we test against candidate

**Comment by tombujok** [comment]
@v-yadli ad. Scenario 1 -> that seems to be a blocker ;( We saw it before but it's difficult to find the reason. Do you you think you could rerun it again, against the zipped backup?

**Comment by v-yadli** [comment]
@tombujok I do have a backup tarball that I wrapped several months ago. I'll see if it works.

**Comment by v-yadli** [comment]
@tombujok I'm experimenting with the half-way-done installation. Seems that I cannot chmod the babun script even manually.

**Comment by tombujok** [comment]
@v-yadli great that you have an instance when we can reproduce it and play around. Why can't you chmod - that's the question that will solve it! Maybe you are using a different windows user?

**Comment by tombujok** [comment]
@v-yadli Yes, but why wouldn't a user be able to modify files in his/her user home folder?

**Comment by v-yadli** [comment]
@tombujok I performed a Bitlocker re-encryption procedure and reinstalled OS a while ago so that might be the case. With the new OS and new account the system does not think that the files belong to me anymore .Maybe we can just call it an edge case, or give the user a hint on this(no write permission).

**Comment by tombujok** [comment]
@v-yadli Maybe we should add a check in update.bat - and skip the process otherwise, because otherwise it blows up?

**Comment by glennular** [comment]
@tombujok I also found if you originally install Babun in a prompt with administrative rights. You have to make sure you run update with Babun running as administrator.

**Comment by tombujok** [comment]
@glennular Great that you found it! Do you know how we could check it in update.bat?

**Comment by glennular** [comment]
@tombujok I think you should just be able to try to read a file in /usr while running in cygwin and you'll get a permission denied. Then just show an error message " this was originally installed with admin right, reopen bubun with admin rights""

A work around I have is I have a shortcut to Babun.bat that always opens in Admin mode. We might want to include a similar solution.

**Comment by tombujok** [comment]
@glennular Is it only /usr that you don't have permission to? or all folders in root folder (/) ?

**Comment by glennular** [comment]
@tombujok  Correct all root folders are owned by `Administrator`

Also I noticed that when i update to the candidate branch successfully as Admin. And then try to update `babun update' with out admin rights i get the following error:

```
Executing babun update
  upstream  [candidate]
 ")syntax error: invalid arithmetic operator (error token is ": 0
Error on or near line 26, last command 'installed_version=$( get_version_as_number "$installed_version_string" )';
```

Note: i do not get that error when i re-run the update as Admin.

**Comment by tombujok** [comment]
@glennular That's great that we managed to nail it down!  Could you figure out a short command that would enable us to distinguish these situations, maybe like:
` if [ -w /use ] ; then echo 'write enabled!' ; else echo 'write disabled'; fi
Don't know if this one would work (the cygwin/windows permissions are more quirky I guess)
Then we would add this check to the babun update script - not allowing the user to update babun if he/she installed babun as admin, but runs the update as "normal" user.

It's the last issue that blocks us from releasing 1.1.0

**Comment by airborn** [comment]
Test Scenario | Status | Comments
------------------ | -------- | ---
Scenario 1 | NOK |  D: grep warnings visible

**Comment by glennular** [comment]
@tombujok Your commit https://github.com/babun/babun/commit/154c7ea6a8f1a513d77a5673fc82029f59def441 fixed when running `babun update` on 1.1.0 already 

But when I try to update from 1.0.1 I still get the following error:
```
Fixing permissions
/bin/chmod: changing permissions of `/etc/postinstall/symlinks_repair.sh.done': Permission denied
Error on or near line 89, last command '/bin/chmod u+rwx -R /etc';
ERROR: Could not update babun!
Error on or near line 58, last command '"$babun"/source/babun-core/tools/update_exec.sh';
```
I created a merge request with a fix in update_exec.sh https://github.com/babun/babun/pull/270

**Comment by v-yadli** [comment]
@glennular The permission to chmod is not write permission.

**Comment by tombujok** [comment]
@v-yadli Do you mean that for the test it should be chmod 777 /usr?

**Comment by v-yadli** [comment]
@tombujok Yes! I do have write permission on the files. Just cannot change permission or delete them(sorry didn't make it clear). How about replicate the action of chmod'ing /usr/local/bin/babun? Maybe that would be safer to execute.

**Comment by tombujok** [comment]
@v-yadli I was also wondering if using /usr is safe, So you mean `chmod 777 /usr/local/bin/babun` instead of `chmod 777 /usr`

**Comment by jlupi** [comment]
@airborn do you still see the grep warnings? Even if you restart babun?

We are unsetting grep options on babun's start. It may happen that another script that you executed sets it back.

**Comment by v-yadli** [comment]
@tombujok I get an error message here: `zsh: permission denied: babun` with nothing else printed out.
Executing `permcheck=$( chmod 777 /etc/passwd /usr/local/bin/babun 2> /dev/null || echo "FAILED" )` manually does echo "FAILED" back to me. So I think it never reached there.

**Comment by tombujok** [comment]
@v-yadli ok, but your case is really specific, with these BitLocker hacks and the fact the you are using a differen user. It's an edge case - either update as admin or change the permissions in windows. @jlupi WDYT?

**Comment by tombujok** [comment]
We are about to release ;) Would be great to hear back from @glennular. Any chance you could retest your case?

**Comment by jlupi** [comment]
@tombujok I agree, this scenario is rather unlikely to happen. I just tested few variants and it looks good for me

**Comment by glennular** [comment]
@tombujok not at a computer at the moment. Give me ~2 hours

I want to make sure I don't get the same error as @v-yadli

Side note, we need better support for development off of forks. Better documentation or the ability to specify repo. I'd like to help for the next release

**Comment by tombujok** [comment]
Expected release date: 18.00 CET today

**Comment by tombujok** [comment]
@glennular Ok, perfect. We are waiting. I agree.

Expected release date: 18.00 CET today

**Comment by glennular** [comment]
@tombujok New error occurring with your recent changes when updating without admin rights

```
Executing babun update
  upstream  [candidate]
  installed [1.0.1]
  newest    [1.1.0]
error: unable to unlink old '.gitignore' (Permission denied)
error: unable to unlink old 'README.adoc' (Permission denied)
error: unable to unlink old 'babun-core/core.groovy' (Permission denied)
error: unable to unlink old 'babun-core/plugins/cacert/install.sh' (Permission denied)
error: unable to unlink old 'babun-core/plugins/cacert/install_home.sh' (Permission denied)
...
error: unable to unlink old 'babun-packages/packages.groovy' (Permission denied)
error: unable to unlink old 'babun-packages/wget.exe' (Permission denied)
error: unable to unlink old 'babun.version' (Permission denied)
error: unable to unlink old 'build.groovy' (Permission denied)
fatal: Could not reset index file to revision 'HEAD'.
Error on or near line 41, last command 'git --git-dir="$babun/source/.git" --work-tree="$babun/source" reset --hard';
```

**Comment by jlupi** [comment]
@glennular weird

What do you get when you run this as a normal user?

````
chmod 777 /etc/passwd /usr/local/bin/babun
````

What are the steps that you perform?

For me it is:

* download 1.0.1 from the website
* install 1.0.1 as administrator
* download and execute the test_setup_script.sh as described in scenarios (here I tried both, running the sh as administrator and as a normal user)
* exit babun
* start babun as a normal user
* babun check - expected File permissions  [FAILED]
* babun update - expected: RROR: The update has failed! You don't have write permission to / filesystem!

**Comment by glennular** [comment]
@jlupi  When i run that i get:

```
{ ~ }  » chmod 777 /etc/passwd /usr/local/bin/babun
chmod: changing permissions of `/etc/passwd': Permission denied
chmod: changing permissions of `/usr/local/bin/babun': Permission denied
```

My Steps
* download 1.0.1 from the website
* install 1.0.1 as administrator
* exit babun
* start babun as normal user
* `export BABUN_BRANCH=candidate`
* `babun update`

**Comment by jlupi** [comment]
Ok, I guess that when you run babun update you probably see a msg that your branch is behind XX commits right?

The problem is that in normal scenario you do not switch branches, you always stay on the release branch. 
In 1.0.1 there was a small issue that the update fetched changes but did not pull them when branches were switched. This is why you probably do not even have the code that @tombujok checked in recently.

To workaround this issue, for the test purposes, we provided the bash-betatest-setup.sh, which does the branch switch and git pull (and afterwards some dos2unix and chmods just in case).

You can do that manually, or just try running the script.

**Comment by jlupi** [comment]
@glennular  BTW the chmod checks look good, based on this and having the new code you should not be able to perform 'babun update'

**Comment by glennular** [comment]
just to let you know, I was able to update successfully yesterday with the steps I listed above.

Where is the bash-betatest-setup.sh?

**Comment by jlupi** [comment]
@glennular I belive you :) It may work if you execute babun update multiple times, or if you do git pull in the source folder after branch switching (depending on your git autocrlf settings). 

The problem was fixed here https://github.com/babun/babun/commit/82c3484c153dfb15fce225093dbca0b385acf409

The script itself:

````
wget http://static.reficio.org/babun/babun-betatest-setup.sh

dos2unix babun-betatest-setup.sh

chmod 755 babun-betatest-setup.sh

./babun-betatest-setup.sh

source ~/.babunrc
````

**Comment by glennular** [comment]
@jlupi Nope it worked. i would run update once as normal user (get to permission error when updating the babun core plugin) and then run in admin mode and get a successful update. Testd on both win7x64 and win8x64

i will try the script

**Comment by glennular** [comment]
OK tested with the beta script got the permission check

did see this though: `error: Unable to append to .git/logs/HEAD: Permission denied`

**Comment by glennular** [comment]
have you guys thought of opening a Gitter room for communication? https://gitter.im

**Comment by tombujok** [comment]
@glennular I know the test procedure is complex, (we will try to make it easier) but as I reckon you executed the betatest.sh script as admin, that's the reason why you see this error.
I am sure that when you execute it even now as non-admin you will get permission denied:
chmod 777 /etc/passwd /usr/local/bin/babun

Could you check this chmod? and if possible try to rexecute this test case, but do it like this:
- as admin -> only install babun and close it
- as non admin:  open babun and then
````
wget http://static.reficio.org/babun/babun-betatest-setup.sh
dos2unix babun-betatest-setup.sh
chmod 755 babun-betatest-setup.sh
./babun-betatest-setup.sh
source ~/.babunrc
babun update
````

**Comment by glennular** [comment]
@tombujok I had to run the scripts as admin or else I get the following

```
{ ~ }  » dos2unix babun-betatest-setup.sh
dos2unix: converting file babun-betatest-setup.sh to Unix format...
{ ~ }  » chmod 755 babun-betatest-setup.sh
{ ~ }  » ./babun-betatest-setup.sh
error: unable to unlink old '.gitignore' (Permission denied)
error: unable to unlink old 'README.adoc' (Permission denied)
error: unable to unlink old 'babun-core/core.groovy' (Permission denied)
error: unable to unlink old 'babun-core/plugins/cacert/install.sh' (Permission denied)
error: unable to unlink old 'babun-core/plugins/cacert/install_home.sh' (Permission denied)
error: unable to unlink old 'babun-core/plugins/cacert/plugin.desc' (Permission denied)
error: unable to unlink old 'babun-core/plugins/core/install.sh' (Permission denied)
...
dos2unix: Failed to change the owner and group of temporary output file /usr/local/etc/babun/source/.git/d2utmpuOG9zM: Permission denied
dos2unix: converting file /usr/local/etc/babun/source/.git/config to Unix format...
dos2unix: problems converting file /usr/local/etc/babun/source/.git/config
dos2unix: Failed to change the owner and group of temporary output file /usr/local/etc/babun/source/.git/d2utmpyIKKM6: Permission denied
...
chmod: changing permissions of `/usr/local/etc/babun/source/babun-core/plugins/cacert/install.sh': Permission denied
chmod: changing permissions of `/usr/local/etc/babun/source/babun-core/plugins/cacert/install_home.sh': Permission denied
chmod: changing permissions of `/usr/local/etc/babun/source/babun-core/plugins/core/install.sh': Permission denied
```

Running your command:
```
{ ~ }  » chmod 777 /etc/passwd /usr/local/bin/babun
chmod: changing permissions of `/etc/passwd': Permission denied
chmod: changing permissions of `/usr/local/bin/babun': Permission denied
```

**Comment by tombujok** [comment]
@glennular Thanks for your tests! I think it's an extreme corner case. We've tested a lot this admin/non-admin problem and added two checks to make sure the user does not run into troubles.  It's anyway the user's responsibility to control if they update with the same user that they've installed babun with - and it's easy to think of a case where sth may go wrong. We will add an entry to the FAQ to summarize what to do in case "permission denied" messages pop up during the update. I've just found a small bug which means that @jlupi and me have to run our acceptance tests again (sic!)...

**Comment by tombujok** [comment]
@glennular Now I understood, it went through but you saw `error: Unable to append to .git/logs/HEAD: Permission denied` -> So this is OK! 

OK guys we are ready for release!

**Comment by tombujok** [comment]
The release is ready, but tomorrow is Good Friday, so we will be offline. 
The release is scheduled for Saturday 10.00 CET.

**Comment by tombujok** [comment]
The newest babun has been just released! It's been a tremendous effort, but we believe that the newest version is a huge step forward. I would like to personally thank everybody who contributed to this release.
I would like to menton @jlupi in the first place, since he was the main driver of this release. 
Many thanks also to our beta testers and all other people who submitted contributions or pull requests!

Enough said, now execute babun update and enjoy the newest version with the newest cygwin!

**Comment by tombujok** [comment]
Have a look at the newest blog entry about 1.1.0:
http://babun.github.io/blog/

**Comment by dragon788** [comment]
@tombujok Sadly I've run into some issues upgrading babun when behind a proxy (enterprise). The upgrade process doesn't appear to have honored the proxy settings defined in my .babunrc and while it references a proxy "switch", passing in /proxy http://user:passwd@proxyname:80 didn't appear to work either. I tried setting http_proxy manually and exporting http and https entries in .babunrc, but nothing has worked. I'll probably just grab the newest release, but it would be great to get the "seamless" upgrades working regardless of network environment.

**Comment by tombujok** [comment]
It should automatically read http_proxy from .babunrc - I am not sure why
it did not work for you.
Could you show the output of :
grep 'export http_proxy=' ~/.babunrc | grep -v '#' | sed 's/export
http_proxy=//g' | cut -d "@" -f 2

Passing the proxy in the following format to udate.bat should work too:
/proxy http://proxyname:80

(no username:password@ part).
If the proxy requires authentication a popup will be shown.

**Comment by igitur** [comment]
@dragon788 Also see issue 273 . I had a similar issue and had to omit the `http://` part from the proxy parameter. Does that work for you?

**Comment by dragon788** [comment]
I think part of my problem is I "moved" my home directory according to the cygwin documentation to C:\Users\<username> via /cygdrive/c/Users/<username> instead of /home/<username> 

But when I run with /proxy=proxyname:port or /proxy=http://proxyname:port it never prompts me for the password, and even if I hardcode with /proxy=(http://)username:password@proxyname:port it still fails to update correctly.

Something similar to mkpasswd -l [-d] > /etc/passwd is what I used to change my "home".

Starting cygwin install, version 2.870
User has backup/restore rights
io_stream_cygfile: fopen(/etc/setup/setup.rc) failed 2 No such file or directory

Current Directory: C:/Users/<username>/.babun//dist
Could not open service McShield for query, start and stop. McAfee may not be ins
talled, or we don't have access.
root: C:/Users/<username>/.babun/\cygwin system
Selected local directory: C:/Users/<username>/.babun//dist
net: Proxy
Cached mirror list unavailable
get_url_to_membuf http://cygwin.com/mirrors.lst
getUrlToStream http://cygwin.com/mirrors.lst
getUrlToStream failed!
get_url_to_membuf failed!
Defaulting to empty mirror list
site: http://mirrors.kernel.org/sourceware/cygwin/

**Comment by dragon788** [comment]
After babun got itself in a bad way (opening to just sh4.1). I have been able to execute /bin/bash and then 'http_proxy=http://proxyname:port babun update' works and it prompts me for a username and password for the proxy for Cygwin. I'm not sure if it will sort itself out with my correct home directory again at this point, but its not too terribly hard to redirect my home directory and leave everything installed where it sits. Is there any code/tests around whether the user's current home directory is the default or has moved before performing an upgrade?

**Comment by tombujok** [comment]
@dragon788 Great that you managed to fix your babun instance. Yes, there is such code.
