### ISSUE TITLE
3 Windows opening when launching babun.bat

### ISSUE THREAD

**Issue by hachre** [babun/babun#267]
I'm on Windows 10. When I launch babun.bat I get 1 window with the actual terminal that I want and 2 additional ones which are empty. Is this a 10 specific bug? I have not tested it on other Windows versions.

**Comment by tombujok** [comment]
Yes, it's windows 10 specific, and we have no windows 10 environment to
test it, so if you managed to fix it, I'm sure that somebody from the
community would offer you a beer ;)

**Comment by jlupi** [comment]
the same problem (and solution) was reported here #237

**Comment by hachre** [comment]
Thanks @jlupi
