### ISSUE TITLE
Upgrading cygwin behind proxy

### ISSUE THREAD

**Issue by igitur** [babun/babun#273]
Hi,

I'm also having issues upgrading to the lastest version. I think babun itself upgraded successfully to 1.1.0, but cygwin can't upgrade.

I'm using cntlm as a local proxy which forwards requests to out corporate proxy.

See screenshot.

![image](https://cloud.githubusercontent.com/assets/145854/7020739/ae183ea8-dd1b-11e4-942e-a59b4f3d0fa0.png)

**Comment by tombujok** [comment]
Yes, you are right, there's been problems with the Internet Connection.

The update.bat has been invoked with the following proxy setup:
`update.bat /proxy=http://127.0.0.1:3128`
is that correct?

To finish the update try invoking update.bat manually with the correct proxy switch.

**Comment by igitur** [comment]
I tried that command, but it still doesn't work.

**Comment by igitur** [comment]
I tried that command, but it still doesn't work. Here is my full log:

```
2015/04/07 12:08:48 Starting cygwin install, version 2.870
2015/04/07 12:08:48 User has backup/restore rights
2015/04/07 12:08:48 io_stream_cygfile: fopen(/etc/setup/setup.rc) failed 2 No such file or directory
2015/04/07 12:08:48 Current Directory: C:/Users/FrancoisBo/.babun//dist
2015/04/07 12:08:48 Could not open service McShield for query, start and stop. McAfee may not be installed, or we don't have access.
2015/04/07 12:08:48 root: C:/Users/FrancoisBo/.babun/\cygwin system
2015/04/07 12:08:48 Selected local directory: C:/Users/FrancoisBo/.babun//dist
2015/04/07 12:08:48 net: Proxy
Cached mirror list unavailable
get_url_to_membuf http://cygwin.com/mirrors.lst
getUrlToStream http://cygwin.com/mirrors.lst
getUrlToStream failed!
get_url_to_membuf failed!
Defaulting to empty mirror list
2015/04/07 12:08:48 site: http://mirrors.kernel.org/sourceware/cygwin/
get_url_to_membuf http://mirrors.kernel.org/sourceware/cygwin/x86/setup.bz2
getUrlToStream http://mirrors.kernel.org/sourceware/cygwin/x86/setup.bz2
getUrlToStream failed!
get_url_to_membuf failed!
get_url_to_membuf http://mirrors.kernel.org/sourceware/cygwin/x86/setup.bz2.sig
getUrlToStream http://mirrors.kernel.org/sourceware/cygwin/x86/setup.bz2.sig
getUrlToStream failed!
get_url_to_membuf failed!
get_url_to_membuf http://mirrors.kernel.org/sourceware/cygwin/x86/setup.ini
getUrlToStream http://mirrors.kernel.org/sourceware/cygwin/x86/setup.ini
getUrlToStream failed!
get_url_to_membuf failed!
get_url_to_membuf http://mirrors.kernel.org/sourceware/cygwin/x86/setup.ini.sig
getUrlToStream http://mirrors.kernel.org/sourceware/cygwin/x86/setup.ini.sig
getUrlToStream failed!
get_url_to_membuf failed!
2015/04/07 12:08:48 mbox note: Unable to get setup.ini from <http://mirrors.kernel.org/sourceware/cygwin/>
2015/04/07 12:08:48 unattended_mode is set at mbox: returning default value
2015/04/07 12:08:48 site: http://mirrors.kernel.org/sourceware/cygwin/
get_url_to_membuf http://mirrors.kernel.org/sourceware/cygwin/x86/setup.bz2
getUrlToStream http://mirrors.kernel.org/sourceware/cygwin/x86/setup.bz2
getUrlToStream failed!
get_url_to_membuf failed!
get_url_to_membuf http://mirrors.kernel.org/sourceware/cygwin/x86/setup.bz2.sig
getUrlToStream http://mirrors.kernel.org/sourceware/cygwin/x86/setup.bz2.sig
getUrlToStream failed!
get_url_to_membuf failed!
get_url_to_membuf http://mirrors.kernel.org/sourceware/cygwin/x86/setup.ini
getUrlToStream http://mirrors.kernel.org/sourceware/cygwin/x86/setup.ini
getUrlToStream failed!
get_url_to_membuf failed!
get_url_to_membuf http://mirrors.kernel.org/sourceware/cygwin/x86/setup.ini.sig
getUrlToStream http://mirrors.kernel.org/sourceware/cygwin/x86/setup.ini.sig
getUrlToStream failed!
get_url_to_membuf failed!
2015/04/07 12:08:48 mbox note: Unable to get setup.ini from <http://mirrors.kernel.org/sourceware/cygwin/>
2015/04/07 12:08:48 unattended_mode is set at mbox: returning default value
2015/04/07 12:08:48 site: http://mirrors.kernel.org/sourceware/cygwin/
get_url_to_membuf http://mirrors.kernel.org/sourceware/cygwin/x86/setup.bz2
getUrlToStream http://mirrors.kernel.org/sourceware/cygwin/x86/setup.bz2
getUrlToStream failed!
get_url_to_membuf failed!
get_url_to_membuf http://mirrors.kernel.org/sourceware/cygwin/x86/setup.bz2.sig
getUrlToStream http://mirrors.kernel.org/sourceware/cygwin/x86/setup.bz2.sig
getUrlToStream failed!
get_url_to_membuf failed!
get_url_to_membuf http://mirrors.kernel.org/sourceware/cygwin/x86/setup.ini
getUrlToStream http://mirrors.kernel.org/sourceware/cygwin/x86/setup.ini
getUrlToStream failed!
get_url_to_membuf failed!
get_url_to_membuf http://mirrors.kernel.org/sourceware/cygwin/x86/setup.ini.sig
getUrlToStream http://mirrors.kernel.org/sourceware/cygwin/x86/setup.ini.sig
getUrlToStream failed!
get_url_to_membuf failed!
2015/04/07 12:08:48 mbox note: Unable to get setup.ini from <http://mirrors.kernel.org/sourceware/cygwin/>
2015/04/07 12:08:48 unattended_mode is set at mbox: returning default value
2015/04/07 12:08:48 site: http://mirrors.kernel.org/sourceware/cygwin/
get_url_to_membuf http://mirrors.kernel.org/sourceware/cygwin/x86/setup.bz2
getUrlToStream http://mirrors.kernel.org/sourceware/cygwin/x86/setup.bz2
getUrlToStream failed!
get_url_to_membuf failed!
get_url_to_membuf http://mirrors.kernel.org/sourceware/cygwin/x86/setup.bz2.sig
getUrlToStream http://mirrors.kernel.org/sourceware/cygwin/x86/setup.bz2.sig
getUrlToStream failed!
get_url_to_membuf failed!
get_url_to_membuf http://mirrors.kernel.org/sourceware/cygwin/x86/setup.ini
getUrlToStream http://mirrors.kernel.org/sourceware/cygwin/x86/setup.ini
getUrlToStream failed!
get_url_to_membuf failed!
get_url_to_membuf http://mirrors.kernel.org/sourceware/cygwin/x86/setup.ini.sig
getUrlToStream http://mirrors.kernel.org/sourceware/cygwin/x86/setup.ini.sig
getUrlToStream failed!
get_url_to_membuf failed!
2015/04/07 12:08:48 mbox note: Unable to get setup.ini from <http://mirrors.kernel.org/sourceware/cygwin/>
2015/04/07 12:08:48 unattended_mode is set at mbox: returning default value
2015/04/07 12:08:48 site: http://mirrors.kernel.org/sourceware/cygwin/
get_url_to_membuf http://mirrors.kernel.org/sourceware/cygwin/x86/setup.bz2
getUrlToStream http://mirrors.kernel.org/sourceware/cygwin/x86/setup.bz2
getUrlToStream failed!
get_url_to_membuf failed!
get_url_to_membuf http://mirrors.kernel.org/sourceware/cygwin/x86/setup.bz2.sig
getUrlToStream http://mirrors.kernel.org/sourceware/cygwin/x86/setup.bz2.sig
getUrlToStream failed!
get_url_to_membuf failed!
get_url_to_membuf http://mirrors.kernel.org/sourceware/cygwin/x86/setup.ini
getUrlToStream http://mirrors.kernel.org/sourceware/cygwin/x86/setup.ini
getUrlToStream failed!
get_url_to_membuf failed!
get_url_to_membuf http://mirrors.kernel.org/sourceware/cygwin/x86/setup.ini.sig
getUrlToStream http://mirrors.kernel.org/sourceware/cygwin/x86/setup.ini.sig
getUrlToStream failed!
get_url_to_membuf failed!
2015/04/07 12:08:48 mbox note: Unable to get setup.ini from <http://mirrors.kernel.org/sourceware/cygwin/>
2015/04/07 12:08:48 unattended_mode is set at mbox: returning default value
2015/04/07 12:08:48 download/verify error in unattended_mode: out of retries
2015/04/07 12:08:48 note: Installation incomplete.  Check C:\Users\FrancoisBo\.babun\\cygwin\var\log\setup.log.full for details
2015/04/07 12:08:48 Ending cygwin install
```

**Comment by tombujok** [comment]
I mean you have to figure out what is the correct address of your proxy.
You can also try without proxy.
Update.bat runs the cygwin setup.exe so ther's no bug there. The problem
with your update is the correct proxy setup.

**Comment by igitur** [comment]
That *is* the correct proxy. It's a local cntlm proxy. http://cntlm.sourceforge.net 

My oh-my-zsh scripts update through it all the time.

I'm starting to think this is a cygwin bug, not a babun bug.

**Comment by tombujok** [comment]
I understand, so `127.0.0.1:3128` is the correct address.
Could you try directly with your corporate proxy?

**Comment by igitur** [comment]
Ah, found the problem. The `setup-x86.exe` file expects the proxy parameter in this format:
`--proxy=127.0.0.1:3128`

Currently it is being sent through as
`--proxy=http://127.0.0.1:3128`

The `http` or `https` should be stripped from the entry in the environment variable.

**Comment by tombujok** [comment]
Great that it works!

It's funny because it works for me with the http(s) prefix, but maybe cntlm
proxy is kind of an edge case...?

**Comment by igitur** [comment]
No, I also tried with the corporate proxy and it failed. You have to omit the `http://` part.

**Comment by igitur** [comment]
Oh, but you say it worked for you. Weird. When I run `setup-x86.exe --help` it does state that the proxy format is:

` -p --proxy                        HTTP/FTP proxy (host:port)`

**Comment by tombujok** [comment]
You are right, it strips the http:// part correctly when the http proxy is specified like this:
`http_proxy=http://user:pass@host:port`

It does NOT work if there's no user:pass
`http_proxy=http://host:port`

This is the command that extract the proxy in the update process:
`/bin/grep.exe 'export http_proxy=' ~/.babunrc | /bin/grep.exe -v '#' | /bin/sed.exe 's/export http_proxy=//g' | /bin/cut.exe -d "@" -f 2`

Could anyone fix it so that it works correctly in both cases?

**Comment by darinkes** [comment]
Hehe, had the same problem today.

Here's my approach to fix this:

```
{ ~ }  » echo "export http_proxy=http://user:pass@host:port" | /bin/sed.exe 's,export http_proxy=http://,,g' | /bin/awk '{n=split($0,a,"@"); print a[n]}'
host:port
{ ~ }  » echo "export http_proxy=http://host:port" | /bin/sed.exe 's,export http_proxy=http://,,g' | /bin/awk '{n=split($0,a,"@"); print a[n]}'
host:port
```

**Comment by tombujok** [comment]
Thx!
So the correct command that should be placed in update.bat looks like this IMHO:
`source ~/.babunrc && echo $http_proxy | /bin/sed.exe 's,http://,,g' | /bin/awk '{n=split($0,a,"@"); print a[n]}'`

any objections?

**Comment by darinkes** [comment]
:+1: looks good

**Comment by jlupi** [comment]
it works, just for the consistency use /bin/awk.exe

**Comment by darinkes** [comment]
{ ~ }  » /bin/awk.exe
-bash: /bin/awk.exe: No such file or directory

**Comment by tombujok** [comment]
there's /bin/gawk.exe, we could use this one.

{ code } master » ls -al /bin/awk
                                           /d/work/zld/code
lrwxrwxrwx 1 ue62407 8 Jun  6  2014 /bin/awk -> gawk.exe

**Comment by tombujok** [comment]
@darinkes Do you want to submit a PR, so that the commit is on your account ;) ?

**Comment by darinkes** [comment]
Sure! Here you go :)
Just tested it by updating to current release.

**Comment by darinkes** [comment]
wait with merging, a minor syntax problem occured.

**Comment by tombujok** [comment]
OK, and plz make sure that it returns nothing (but does not fail) when the
.babunrc file does not exist

**Comment by darinkes** [comment]
Ok. Done.
Escaping is a total pain in the a**

**Comment by jlupi** [comment]
@darinkes  @tombujok looks cool, but I gues it fails if the .babunrc file does not exist. For me greping .babunrc instead of sourceing it is a safer option. Otherwise we have to add additional check here. WDYT?

**Comment by jlupi** [comment]
sorry just tried it, it will be the same thing, grep also complains if the file does not exist.

**Comment by tombujok** [comment]
Could you guys retest when the file does not exist?
@jlupi I think echo is still safer. A person can have sth like this:
```
export proxy=proxy.com:8080
export http_proxy=$proxy
export https_proxy=$proxy
export ftp_proxy=$proxy
```
In this case echo is much better, otherwise it's the same IMHO.

**Comment by darinkes** [comment]
I don't think it's a problem in this case, cause update.bat tries to source .babunrc multiple times before checking for the proxy.

See SETUPRC and RUNNINGCHECK

**Comment by tombujok** [comment]
I've just tested it and it works fine with and without .babunrc file.
We will publish a fix release whenever we will find a free slot of time...

**Comment by tombujok** [comment]
1.1.1 with the proxy fix released
