### ISSUE TITLE
install.bat fails due to antivirus blocking .vbs file

### ISSUE THREAD

**Issue by igitur** [babun/babun#275]
I tried the `install.bat` in the normal dist file. It quickly fails because out antivirus (McAfee), like most antivirus programs, blocks any execution of .vbs files. 

I think the `freespace.vbs` file is non-critical enough that if it fails, normal installation can continue. Agree?

**Comment by igitur** [comment]
pull request #279 added

**Comment by tombujok** [comment]
Merged. Should be released in 1.2.1 #393
