### ISSUE TITLE
babun check fails

### ISSUE THREAD

**Issue by igitur** [babun/babun#276]
Ok, so after all my cygwin proxy issues, I managed to update to babun version 1.1.0.

I had to reboot, and now, when I open babun and execute `babun check`, I get a message: `You can only run one instance of babun. Exiting!`

I have ensured that there are no other babun instances running.

![image](https://cloud.githubusercontent.com/assets/145854/7028438/24f9276e-dd56-11e4-91f9-d8eae89a8a57.png)

**Comment by tombujok** [comment]
It's probably an incosistent state after the proxy problems.
Try `rm /var/lock/*`

**Comment by tombujok** [comment]
Did it help?

**Comment by igitur** [comment]
I'll check tomorrow.

**Comment by igitur** [comment]
Thanks, `rm -rf /var/lock/*` removed all the locks.

Suggestion, change the error message to:
`You can run only one instance of babun. Close all other instances of babun or clear the /var/lock/ directory if you are sure there are no other instances currently running.`

**Comment by igitur** [comment]
Created pull request #278

**Comment by Vigorass** [comment]
great, this works! Thank you~

**Comment by yveshwang** [comment]
i had the same problem. The situation with me is that i have a proxy setup at work, and babun fails when with ``` babun update ``` command when it got to updating cygwin via another dos prompt.

the work around was to remove the lock folder as stated above.

**Comment by dragon788** [comment]
Just had the same problem and the rm -rf fixed it, can't wait to do this as work as this has been hindering my use of Babun recently since I couldn't do much with any settings.

**Comment by tombujok** [comment]
Merged. Should be released in 1.2.1 #393
