### ISSUE TITLE
Autocomplete not working??

### ISSUE THREAD

**Issue by pertrai1** [babun/babun#281]
This is a great shell. Only issue is that after making some changes, only to .zshrc, I have lost my ability to tab autocomplete. Any idea of what would have made this happen?

**Comment by noirchen** [comment]
I also got this problem.

**Comment by fuzzmz** [comment]
Try running `rm -f ~/.zcompdump*; compinit` and see if that fixes it.

**Comment by noirchen** [comment]
This has no change.

**Comment by pertrai1** [comment]
Yeah, I had to do complete reinstall as I stated in [Issue 322](https://github.com/babun/babun/issues/322)

**Comment by zexpp5** [comment]
'rm -f ~/.zcompdump*; compinit '
did help

**Comment by shayts7** [comment]
"rm -f ~/.zcompdump*; compinit" worked for me too

**Comment by cyberto** [comment]
I have the same problem and when running
`rm -f ~/.zcompdump*; compinit`
I get
`bash: compinit: command not found`

**Comment by sangimed** [comment]
the "rm -f ~/.zcompdump*; compinit" works but its effect disappears after restarting babun :s

**Comment by theox26** [comment]
the "rm -f ~/.zcompdump*; compinit" works but its effect disappears after restarting babun for me as well.  

It also seems to have made babun almost unbearably slow no matter if I restart it or not.

**Comment by binard** [comment]
"rm -f ~/.zcompdump*; compinit" worked for me too !! Thanks

**Comment by thiamteck** [comment]
in case `rm -f ~/.zcompdump*; compinit` does not work for you, you shall give this a try:

    $ compinit
    $ cp .zcompdump .zcompdump-$HOSTNAME-$ZSH_VERSION

Reference: Q31 at http://babun.github.io/faq.html

**Comment by j-marjanovic** [comment]
Yes, I can confirm that creating `.zcompdump-$HOSTNAME-$ZSH_VERSION` fixes problem permanently

**Comment by pertrai1** [comment]
Sorry for long delay. This did the trick for me. Thank you all.

**Comment by mitcc** [comment]
@thiamteck 
"$ compinit
$ cp .zcompdump .zcompdump-$HOSTNAME-$ZSH_VERSION" worked for me, thank you!

**Comment by yreenchan** [comment]
```
$ compinit
$ cp .zcompdump .zcompdump-$HOSTNAME-$ZSH_VERSION
```
The above code work for me.But it just works once.When I restart babun,the autocomplete is also not working.

**Comment by JGobeil** [comment]
`$ compinit`
Give me 
`zsh compinit: insecure directories, run compaudit for list.`

So
`$ chmod -R 755 $(compaudit)`

And now completion work even after restart. However, it's still slow to start.

**Comment by rbwebdev** [comment]
$ rm -f ~/.zcompdump*; compinit

Work for me. Thx for tips

**Comment by kharloss** [comment]
run 
_autoload -U compaudit compinit_

Works for me.  Hope this help.

**Comment by xiyusullos** [comment]
Hit this `compaudit` to check what the insecure directories are. Then hit `chmod -R 755 ` appending the directories.
 
Works for me when I restart it. Hope this helpful.
