### ISSUE TITLE
Does babun has a Changelog somewhere ?

### ISSUE THREAD

**Issue by kimond** [babun/babun#283]
It could be interesting to have a changelog.

**Comment by BradKnowles** [comment]
They've been posting details about releases on their blog.

http://babun.github.io/blog.html

**Comment by kimond** [comment]
Maybe they should add an explicit link to the changelog.

**Comment by tombujok** [comment]
@kimond Great idea. Could you convert the existing blog posts into the first draft of the changelog and submit a Pull Request?

**Comment by kimond** [comment]
Yes I can. But, where I put changelogs on the site or in the repo in a changelog file ?

**Comment by tombujok** [comment]
Let's put it here: https://github.com/babun/babun/tree/master/babun-doc

**Comment by SamHasler** [comment]
If releases had detailed release notes the changelog would be here:
https://github.com/babun/babun/releases
