### ISSUE TITLE
GREP_OPTIONS deprecated

### ISSUE THREAD

**Issue by ylecuyer** [babun/babun#284]
When using grep I have the following warning: 

```grep: warning: GREP_OPTIONS is deprecated; please use an alias or script```

I saw b439e14145de5f438115455c12042ef86876392e and I have the same babun.rc however it doesn't seem to be loaded at startup because when I do ```echo $GREP_OPTIONS``` it returns ```--color=auto --exclude-dir=.cvs --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn```

**Comment by jlupi** [comment]
As you noticed we are unsetting GREP_OPTIONS on startup. 

Does babun shows those grep options immediatelly after startup, or first when you execute some commands?

Can you check the following if you have the latest version of oh-my-zsh?

````
cd ~/.oh-my-zsh/tools
./upgrade.sh
````

Can you also paste the output of `cat ~/.oh-my-zsh/lib/grep.zsh`?

Last check if GREP_OPTIONS is set somewhere else

````
cd ~
find . -type f -exec grep  "GREP_OPTIONS" {} +
````

**Comment by ylecuyer** [comment]
Apparently upgrading oh-my-zsh resolved the issue. Thanks @jlupi
