### ISSUE TITLE
Cant Install

### ISSUE THREAD

**Issue by pertrai1** [babun/babun#285]
Hi, anytime I click on the bat file all I see is a quick terminal and then it closes with nothing being installed. I downloaded and unzipped but no luck each time I try to install.

**Comment by jlupi** [comment]
Could you please execute `install.bat` from cmd? What do you see?

**Comment by pertrai1** [comment]
@jlupi This is what I get:

>cmd install.bat
cmd install.bat
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

**Comment by jlupi** [comment]
not quite what i meant.

open windows command (cmd), navigate to the directory where you downloaded and unzipped the dist file and run install.bat 

You probably get some error messages.

**Comment by pertrai1** [comment]
I got this working after trying install again.
