### ISSUE TITLE
Cygwin kernel update fails

### ISSUE THREAD

**Issue by uahim** [babun/babun#288]
I just updated from 1.0.1 to 1.1.1; babun now tells me that "the underlying Cygwin kernel is outdated"

```
Checking Cygwin version:
  installed [1.7.29]
  newest    [1.7.35]
```

so after typing babun update again, a seperate cmd window opens 

```
[babun] Executing Cygwin upgrade without proxy
'setup-x86.exe' is not recognized as an internal or external command,
operable program or batch file.
[babun] Terminating due to internal error #1
[babun] Execute C:/gnu/.babun//update.bat to rerun the Cygwin update process.
Press any key to continue . . .
```

now, I do see C:\gnu\\.babun\dist\setup-x86.exe but I assume that when I run it via doubleclick it won't do no good as it would be missing some switches that babun would pass to it?

I also assume it's some path issue, but C:\gnu\\.babun *is* in my PATH variable

any ideas?

**Comment by jlupi** [comment]
Looks like the update script did not download the cygwin installer. Can you check if you have the cygwin installer (`setup-x86.exe`) in the `c:\gnu\.babun\dist`?

If not, does this command download the installer?

````
wget --directory-prefix='C:\gnu\.babun\dist' https://raw.githubusercontent.com/babun/babun-cygwin/1.7.35/babun-cygwin/setup-x86.exe
````

You should be able to run the `update.bat` manually. The switch is optional and only sets the proxy, but looks like you have a direct connection anyway.

**Comment by uahim** [comment]
@jlupi the download itself does work, the file is there physically alright.

what does not work is to be run automatically from the upater/update.bat

according to your advice I just started C:\gnu\.babun\dist\setup-x86.exe via doubleclick and as I assumed, in the second screen it offers a path for the root directory where my non-babun Cygwin is installed (which updated properly the other day)

is it safe to change the path accordingly there (to C:\gnu\\.babun\cygwin) or will it break my babun installation?

**Comment by jlupi** [comment]
just start `update.bat` instead of the `setup-x86.exe` from the babun install directory. It should not break anything.

**Comment by uahim** [comment]
you don't seem to understand; if I do that, I get what I posted in the second listing in the first post above.

**Comment by jlupi** [comment]
I do understand, was just hoping that the first failure was due to some internet connection problems (since the wget did download the installer). 

It would be great to get to the root cause, but not to block you try the following: 

* close all babun instances 
* open windows CMD 
* navigate to C:/gnu/.babun/dist 
* execute 

````
setup-x86.exe --quiet-mode --upgrade-also --site="http://mirrors.kernel.org/sourceware/cygwin" --no-admin --no-shortcuts --no-startmenu --no-desktop --root="C:/gnu/.babun/cygwin" --local-package-dir="C:/gnu/.babun/dist" 
````

**Comment by uahim** [comment]
that did work, thanks. this is what I get now

```
{ ~ }  » uname -a                                                                              ~
CYGWIN_NT-5.1 deepblue 1.7.35(0.287/5/3) 2015-03-04 12:07 i686 Cygwin
```

however, babun check doesn't seem to recognize the new version and still tells me I have 1.7.29 installed. I guess it's just some string in a file that wasn't updated? if so, I could edit it manually if I knew which file it is.

thanks again

**Comment by tombujok** [comment]
Awesome! Could you try to find the reason why it did not work with update.bat? 
Update.bat invokes the same command - it would be great to find the possible bug...

**Comment by uahim** [comment]
unfortunately, no. I spent a couple hours messing with update.bat even going as far as removing `cd "%DIST_DIR%"` and adding the relative `dist\` path before setup-x86.exe - but, no luck. everything else worked fine too, including babun updating itself as mentioned before.

**Comment by tombujok** [comment]
OK, just set 1.7.35 in /usr/local/etc/babun/installed/cygwin

**Comment by uahim** [comment]
great, thanks/dziekuje
