### ISSUE TITLE
Can't change the shell theme - zsh

### ISSUE THREAD

**Issue by pertrai1** [babun/babun#294]
I have tried to change the theme in ,zshrc and it does not change the look of the shell. Anyone experience  this before, and if so, how were you able to fix it? Thank you.

**Comment by fuzzmz** [comment]
Did you `source ~/.zshrc` after changing the theme flag in the file?

**Comment by pertrai1** [comment]
No that did not work once I made the change. This looks good and I am going to keep an eye on it.
