### ISSUE TITLE
Add 'babun which' option

### ISSUE THREAD

**Issue by jlupi** [babun/babun#296]
Add an `babun which` option which prints babun's installation path.

This would be useful in case one has multiple instances installed (for example for testing) and want to check which version is currently started.

**Comment by darinkes** [comment]
Why is this not enough?
````
{ ~ }  » babun --version
babun version 1.1.1
Created and maintained by Tom Bujok (@tombujok)
Copyright (c) 2014-2015.
{ ~ }  » which babun
/usr/local/bin/babun
```

**Comment by jlupi** [comment]
it should show you the windows path not the cygwin path, for example

Instance A would print 
````
{ ~ } which babun
c:\user\.babun
````
Instance B would print
````
{ ~ } which babun
d:\apps\.babun
````

**Comment by darinkes** [comment]
For this, I think using BABUN_HOME from env is enough:

```
{ ~ }  » echo $BABUN_HOME
C:/Users/user/.babun/
```

**Comment by jlupi** [comment]
it may be not enough, the more reliable option would be sth like

````
cygpath -ma "/" | sed "s#/cygwin##g"
````

**Comment by darinkes** [comment]
Sorry, maybe I just don't get it. I don't see any benefit by adding this option to the babun command.
IMHO core tools should not be used for developer informations.

BABUN_HOME is set on start by babun.bat to the directory it was started from.
So it always points to the correct "babun root" of your instance.
And root of cygwin is always BABUN_HOME + /cygwin.

**Comment by jlupi** [comment]
1. As I said `BABUN_HOME` is not reliable, for example when babun restarts after update it does not call babun.bat but mintty directly. Same if you open babun from the taskbar (and couple of other scenarios).

2. I agree that core tools should not be used for dev information. But this is strictly user oriented feature. 
After a while of using babun you may not know where you installed it. 
You may also have multiple installations (for whatever reason) and want to check which one is currently active.

3. It is pretty much the same as the standard unix `which` command but since we are emulating unix `which babun` will always point to `/usr/local/bin/babun`.

I agree that the version information is not necessary, I'll remove this from the description.

**Comment by darinkes** [comment]
Then wouldn't it be better if BABUN_HOME is set in .babunrc with the command you mentioned above?
If BABUN_HOME is so unreliable, this should be fixed and not add a workaround so you don't have to use it.

**Comment by darinkes** [comment]
Just confirmed that BABUN_HOME and CYGWIN_HOME are missing if you start babun from a taskbar link.

I propose to move them from babun.bat to babun-core plugin. So they are set on startup of mintty.

**Comment by jlupi** [comment]
I agree, this needs to be set this way.

**Comment by jlupi** [comment]
@darinkes since you already have this change, would you like to submit a PR and get the credits? :)

**Comment by jlupi** [comment]
@darinkes I opened a new issue for this #298

**Comment by darinkes** [comment]
Sure! Coming soon :)
