### ISSUE TITLE
Pact hash does not match

### ISSUE THREAD

**Issue by c02y** [babun/babun#307]

**Comment by tombujok** [comment]
which one?

**Comment by c02y** [comment]
Anyone. I tried to `pact install emacs` in babun today, and after it downloaded the emacs.tar.xz, it said blabla ( I forgot the exact error message) and failed to install it, the network speed is not fast at that time, so I wondered where was the downloaded tar.gz file saved, but I couldn't find. 

This problem occurred to me several times, most of time, it will failed to install the package I tried to `pact install` then I tried to check the tar.xz file but couldn't find it.

**Comment by xjlin0** [comment]
Can you copy and paste the screen error messages after you enter the following command?
````
pact install emacs
````
I just tried and it automatically installed it flawless. Thanks!

**Comment by c02y** [comment]
{ ~ }  » pact install emacs                                                         ~
Working directory is /setup
Mirror is http://mirrors.kernel.org/sourceware/cygwin/
setup.ini taken from the cache

Installing emacs
Found package emacs
File ‘emacs-24.5-1.tar.xz’ already there; not retrieving.

MD5 sum did not match, exiting

**Comment by c02y** [comment]
{ ~ }  » pact install emacs                                                         ~
Working directory is /setup
Mirror is http://mirrors.kernel.org/sourceware/cygwin/
setup.ini taken from the cache

Installing emacs
Found package emacs
File ‘emacs-24.5-1.tar.xz’ already there; not retrieving.

MD5 sum did not match, exiting

**Comment by c02y** [comment]
{ ~ }  » pact install emacs                                                         ~
Working directory is /setup
Mirror is http://mirrors.kernel.org/sourceware/cygwin/
setup.ini taken from the cache

Installing emacs
Found package emacs
File ‘emacs-24.5-1.tar.xz’ already there; not retrieving.

MD5 sum did not match, exiting


Already `pact update`  before `pact install emacs`

**Comment by tombujok** [comment]
|You are running old babun version.
Run babun update

**Comment by c02y** [comment]
My mistake, I thought it could be solved by `pact update`.

But if you don't mind, I still want to know where the downloaded tar.xz file is saved.

**Comment by tombujok** [comment]
I dont' remember it by heart - you can have a look at pact source code.
