### ISSUE TITLE
Always got 'You can only run one instance of babun. Exiting!'

### ISSUE THREAD

**Issue by qiluo** [babun/babun#308]
I'm on latest 1.1.1 and Windows 7, it was working before 1.1.1, but now I kept getting `'You can only run one instance of babun. Exiting!'` when I executed whatever babun commands, update, install, restart, etc...

Besides, I also got `'gswin32' is not recognized as an internal or external command,
operable program or batch file.` when I executed zsh git alias command

No idea :(

**Comment by jlupi** [comment]
Did you install babun 1.1.1 from scratch or via 'babun update'?

Did you notice any errors during the installation?

Locks: See #276

Git: can you paste the git cmd that you are using?

**Comment by qiluo** [comment]
@jlupi 
I updated 1.1.1 from 1.0.1, `rm -rf /var/lock/*` resolved "one instance" problem, but git alias still not working

many cmds not work
```
gst
gb
glg
```
looks zsh not work

**Comment by jlupi** [comment]
is this a git alias problem or git itself?

does `git status` `git log` work for you? Do git aliases integrated in babun work for you (for example `git lg`)?

If  this is only a problem of git aliases from oh-my-zsh try cd ~/.oh-my-zsh/tools and run ./upgrade.sh

**Comment by qiluo** [comment]
`git status` works, `git lg` works as well

zsh got some changes which is only file permission change, `git reset --hard` can't revert these files, weird... I can't upgrade zsh because of these uncommitted change

**Comment by jlupi** [comment]
in babun 1.1.0 we added a git config to ignore permission changes.

What is the output of `git config core.filemode` or just paste `git config --list`?

**Comment by qiluo** [comment]
`git config core.filemode` showed `true`, then I modified it to false, run `upgrade` for zsh. The upgrade succeeded but zsh alias is not working as well.

My global ``git config core.filemode` is false

**Comment by jlupi** [comment]
The gswin32 is a GhostScript binary. I'm wondering if there is an alias collision in your config.

Can you search for `gswin32` ? 
````
cd ~
grep -r gswin32
````

**Comment by qiluo** [comment]
nothing found, I will have to try a fresh install

**Comment by jlupi** [comment]
In this case I'll close it for now. Feel free to reopen if this issue happens again on a clean install.
