### ISSUE TITLE
All Files Modified in Existing Git Repos

### ISSUE THREAD

**Issue by julien731** [babun/babun#309]
When using Babun with an existing Git repository, all the files are marked modified even though that aren't. What I'm getting is `^M` at the end of every line (see screenshot).

![image](https://cloud.githubusercontent.com/assets/1441024/7175458/1640dbc8-e43f-11e4-973d-f010f01924be.png)

Is there any way to fix that?

**Comment by tombujok** [comment]
Run:
`git config --global core.autocrlf=true`

**Comment by julien731** [comment]
Many thanks for this super fast reply. It worked perfectly. One small typo though, if should be

`
git config --global core.autocrlf true
`

**Comment by karlingen** [comment]
:+1: Thanks!

**Comment by crazyacking** [comment]
:+1: Thanks!
