### ISSUE TITLE
Resource Temporarily Unavailable

### ISSUE THREAD

**Issue by sertaconay** [babun/babun#316]
Hello.

I know it's related to Cygwin, but i want to ask you if you have any advice. I'm using Windows 8.1 64bit. I tried [this link](http://stackoverflow.com/questions/9300722/cygwin-error-bash-fork-retry-resource-temporarily-unavailable) but it didn't work. I couldn't change Read-Only value of my folders and files. Then i tried a couple of Windows Support Forum solution [like this](http://answers.microsoft.com/en-us/windows/forum/windows_8-files/in-windows-8-64-can-not-remove-read-only-attribute/b21c0629-58dd-477d-ae06-39c982b1cdd1) but no luck.

It was working well until i installed Vagrant. I uninstalled Vagrant and it worked again. Then installed Vagrant, it started to not working. I don't know if it's coincidence, i just wanted to say. I didn't examine Vagrant setup and Vagrant files.

    1 [main] bash 3808 child_info_fork::abort: C:\Users\Usera\.babun\cygwin\bin\cygiconv-2.dll: Loaded to different address: parent(0x710000) != child(0x790000)
    bash: fork: retry: No child processes
    1 [main] bash 4328 child_info_fork::abort: C:\Users\Usera\.babun\cygwin\bin\cygintl-8.dll: Loaded to different address: parent(0x360000) != child(0x2C0000)
    bash: fork: retry: No child processes
    1 [main] bash 3168 child_info_fork::abort: C:\Users\Usera\.babun\cygwin\bin\cygiconv-2.dll: Loaded to different address: parent(0x710000) != child(0x720000)
    bash: fork: retry: No child processes
    1 [main] bash 6892 child_info_fork::abort: C:\Users\Usera\.babun\cygwin\bin\cygiconv-2.dll: Loaded to different address: parent(0x710000) != child(0x790000)
    bash: fork: retry: No child processes
    1 [main] bash 2600 child_info_fork::abort: C:\Users\Usera\.babun\cygwin\bin\cygiconv-2.dll: Loaded to different address: parent(0x710000) != child(0x7B0000)
    bash: fork: Resource temporarily unavailable

**Comment by tombujok** [comment]
Feel free to reopen should anybody has any significant feedback.

**Comment by xiaohuix** [comment]
when I use the command: clang 1.cpp
and then the prompt is : 1 [main] clang 6336 child_info_fork::abort: C:\Users\Andy\.babun\cygwin\bin\cygLLVM-3.5.dll: Loaded to different address: parent(0x1E60000) != child(0x1B80000)
clang: error: unable to execute command: posix_spawn failed: Resource temporarily unavailable
Have any idea?

**Comment by zone-stalker** [comment]
This issue can be resolved by running the update.bat script in the .babun folder *after* installing clang via pact. This issue was resolved in a later release of cygwin, which update.bat will update to.

**Comment by fxtentacle** [comment]
Run a rebase with 

    cmd /c %SYSTEMDRIVE%\Users\%USERNAME%\.babun\cygwin\bin\dash.exe -c '/usr/bin/rebaseall -v'

the rebase process will adjust where each cygwin DLL is loaded in memory, so it is the general fix for all of those "Loaded to different address" and "Resource temporarily unavailable" problems.

**Comment by shinmai** [comment]
> Run a rebase with
> 
> cmd /c %SYSTEMDRIVE%\Users\%USERNAME%\.babun\cygwin\bin\dash.exe -c '/usr/bin/rebaseall -v'
> the rebase process will adjust where each cygwin DLL is loaded in memory, so it is the general fix for all of those "Loaded to different address" and "Resource temporarily unavailable" problems.

Running the above snippet I get the following error:
`/usr/bin/rebaseall: 29: /usr/bin/rebaseall: Cannot fork`
