### ISSUE TITLE
Babun 1.1 problem: startup compaudit error message, tab completion fail

### ISSUE THREAD

**Issue by noirchen** [babun/babun#317]
I upgraded to 1.1 yesterday, and these errors start showing up everytime I start the shell:
`compaudit:74: _i_addfiles: assignment to invalid subscript range`
`compdef: unknown command or service: git`
`compdef: unknown command or service: git`
`compdef: unknown command or service: git`
...
The number of compdef errors is the same as the enabled zsh plugins. And the tab completion fails after I modified the .zshrc file. Even if I restore the original .zshrc file, the tab completion still does not work.

**Comment by fuzzmz** [comment]
You can fix that by running `rm -f ~/.zcompdump*; compinit`

**Comment by tombujok** [comment]
Could you try opening babun and invoking: `babun install`

**Comment by noirchen** [comment]
@tombujok This does not fix the error and the tab completion.

**Comment by pertrai1** [comment]
I am also getting the error when I start up a shell.

**Comment by noirchen** [comment]
It seems for some strange reason, after enabling other zsh plugins, the .zcomdump-$HOST file was cleared. The fix is copying the .zcompdump file to that corrupted .zcompdump-$HOST file.

**Comment by pfrayer** [comment]
@fuzzmz solutions works well for me. Thanks :)

**Comment by s4wny** [comment]
None of the above solutions worked for me. Do anyone know why we get this error in the first place? And does it exist some fix?
