### ISSUE TITLE
git error about credential.help wincred

### ISSUE THREAD

**Issue by wikilike7** [babun/babun#318]
Hello : 
 
     i get error when i use babun for my git shell, when i want to use git to remember my user name and password , follow the step of [Github](https://help.github.com/articles/caching-your-github-password-in-git/) 

i get a error :  git: 'credential-wincred' is not a git command. See 'git --help'.

OS : Windows 7
Babun version : 1.1.1

could you help me ?

**Comment by darinkes** [comment]
Github for windows needs to be installed

**Comment by benfreke** [comment]
Use store instead. It's not great but it'll work.

`git config --global credential.helper store`

I assume wincred doesn't work because you're not in a windows environment.

**Comment by tombujok** [comment]
@benfreke Thanks for the fix.

**Comment by Explorare** [comment]
@benfreke Use `store` method will save the credentials to a *plain-text* file on the disk, which is fairly dangerous behavior.

**Comment by Explorare** [comment]
`wincred` is for the project [git-credential-winstore](https://gitcredentialstore.codeplex.com/) which is no longer maintained. It was replaced by [Git-Credential-Manager-for-Windows](https://github.com/Microsoft/Git-Credential-Manager-for-Windows) maintained by Microsoft with love. 

You can download the zip file and extract the content to `\.babun\cygwin\usr\libexec\git-core`. Execute `git config --global credential.helper manager`. And voila, it works like a charm.

**Comment by hafah** [comment]
if the solution of @Explorare got you an error like

```
git: 'credential-manager' is not a git command. See 'git --help'.
```

Make sure you extracted the `gcmw.zip` file below the executable. So that's not the _Source Code (zip)_ link at the bottom.

**Comment by arribass** [comment]
I used  " git config --global credential.helper store " and now works fine and doesnt ask me for user and password but it still prints that annoying wincred is not a command when i git push. Any idea how to remove it?

**Comment by varad-more** [comment]
Run this command ```git config --global -e``` and delete credentials block.
 Or run this command ```git config --remove-section credential```
Hope it works for you
