### ISSUE TITLE
Changing color theme?

### ISSUE THREAD

**Issue by pertrai1** [babun/babun#320]
I am starting to use cobalt color theme with other programs and was wondering how I would go about doing this with Babun? Is there a setting somewhere that will allow me to make a change to the background color and font - ala iTerm?

Thank you

**Comment by pertrai1** [comment]
I am going to close this as I will just play around and see if I can come up with figuring out how to change the color.

**Comment by aloisdg** [comment]
@pertrai1 did you find something?

**Comment by aloisdg** [comment]
I did. You can change the color by editing the `.minttyrc` file.

For example for the `paraiso`  theme:

```
ForegroundColour=163,158,155
BackgroundColour=47,30,46
CursorColour=163,158,155
Black=47,30,46
BoldBlack=119,110,113
Red=239,97,85
BoldRed=249,155,21
Green=72,182,133
BoldGreen=65,50,63
Yellow=254,196,24
BoldYellow=79,66,76
Blue=6,182,239
BoldBlue=141,134,135
Magenta=129,91,164
BoldMagenta=185,182,176
Cyan=91,196,191
BoldCyan=233,107,168
White=163,158,155
BoldWhite=231,233,219
```

I got it with the tool [base16-builder](https://github.com/base16-builder/base16-builder):

```bash
$> base16-builder -s paraiso -t mintty -b dark
```

Disclaimer: I am working on the project.
