### ISSUE TITLE
zsh output % on every command

### ISSUE THREAD

**Issue by xkrt** [babun/babun#321]
Hi!
Just after installation I run /bin/zsh.exe and getting '%' after any command.
```
%
{ ~ }  » ls
%
{ ~ }  »
```

If I run babun.bat (Mintty) everything is fine. And everything is fine if I run /bin/bash.exe.
How can I fix it?

In fact I want to host zsh.exe in ConEmu, solution from FAQ unsuitable because Mintty inside ConEmu intercepts all keyboard shortcuts.

Babun 1.1
Windows 7 x64

**Comment by RichardOtvos** [comment]
I have the same problem in Windows 8. It is quite annoying, because I want to set ZSH as the default terminal in Webstorm, but the '%' after every command makes it look really bad, and wastes to much space.

**Comment by RichardOtvos** [comment]
I had waayy too much time on my hand, so I found the solution by browsing trough zsh maillists. Of course it isn't an issue wih Babun, but a ZSH feature, but I thought you it's useful to have the answer here as well. You can learn more info about this here: http://zsh.sourceforge.net/FAQ/zshfaq03.html under the section: _How do I prevent the prompt overwriting output when there is no newline?_

*The solution:* 
1. Go to your Babun installation directory (`<your username>\.babun` by default) and from there go to `cygwin\home\<username>` and open `.zshrc`.
2. Just add unsetopt promptcr to a new line (the end of the file is fine) and save it. 
3. Restart your terminal (or open a new one).
4. Be happy, no more `%` on new lines

@tombujok @jlupi Would it be possible to add this config option to Babun by default (even if the it is just commented out, so its easier to find a solution for this)

**Comment by xkrt** [comment]
@RichardOtvos thanks! it works! now I can host babun's zsh in ConEmu, so cool combination

**Comment by msenturk** [comment]
@RichardOtvos  thanks for the % problem but babun's zhs in ConEmu is too slow is there any solution for that ?

**Comment by jlupi** [comment]
@RichardOtvos definatelly! Thanks for the solution. We'll squeeze it in the next release.

**Comment by jlupi** [comment]
Fixed in #393
