### ISSUE TITLE
Add ~/.local/bin to PATH variable

### ISSUE THREAD

**Issue by jlupi** [babun/babun#325]
It would be useful to have ~/.local/bin folder added to the PATH variable. Custom scripts could be stored there instead of in /usr/local/bin which would be better from the portability point of view. Besides there is no risk that the scripts are overwritten on update.

**Comment by darinkes** [comment]
:+1: 

And I would also like to see $HOME/bin in the default PATH

**Comment by tombujok** [comment]
Do we need both:  `$HOME/bin` and  `$HOME/.local/bin` ?

**Comment by darinkes** [comment]
$HOME/bin is a unix/linux default.

see /etc/skel/.profile:
```
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
```

Not sure where the .local/bin is coming from.

**Comment by tombujok** [comment]
What would you say if we did it as follows:
- we put ~/.local/bin to PATH
- we create a softlink from ~/.local/bin to ~/bin

.local scales somehow better, since we could have ~/.local/lib, etc.

**Comment by jlupi** [comment]
@tombujok looks good to me, the scalibility was my point too. @darinkes will that work for you?

BTW the ~/.local/bin i saw in fedora. Python's pip also uses such location for installed packages (`pip install --user` command)

**Comment by darinkes** [comment]
ok for me

**Comment by jlupi** [comment]
Part of Release 1.2.0 #304
