### ISSUE TITLE
A lot of keys are not working in fish-shell inside babun

### ISSUE THREAD

**Issue by c02y** [babun/babun#326]
It is OK to install fish (pact install fish) and open it inside babun, but a lot keys are not working, such as UP/DOWN/RIGHT/LEFT, they will be `[A[B[C[D` instead, ·Nothing will happen if I hit very command keys `Backspace` to go back one character or `M-Backspace` to go back one word or `C-l` to clear the screen, currently, the only shortcut I found usable is `C-c` to delete all the characters you just typed, is is possible to correct this problem?

BTW: open `fish` will output:

    fish: Runtime path not available. Try deleting the directory /tmp/fish.dsp_public and restarting fish.
    fish: Could not connect to universal variable server. You will not be able to share variable values          between fish sessions.
    set_color: Expected an argument

then prompt of the shell
    
    user@device-name ~#

**Comment by jlupi** [comment]
its a bug in fish shell. see https://github.com/fish-shell/fish-shell/issues/1160
