### ISSUE TITLE
Can't Read Local SSH Keys

### ISSUE THREAD

**Issue by julien731** [babun/babun#327]
I have a certain number of SSH keys with a config file that handles matching an SSH key with the queried domain. All those keys are stored in the standard Windows directory (`C:\Users\Username\.ssh`).

In order to let Babun know about my SSH keys without having to copy/paste them all in the Cygwin directory, I have created a symlink `C:\Users\Username\.babun\cygwin\home\Username\.ssh` that points to `C:\Users\Username\.ssh`.

When running a `git push`, it looks like Babun correctly follows the symlink, but I get the following error.

```
Bad owner or permissions on /home/Username/.ssh/config
```

There is also the `git` error that says it couldn't read from remote repository, but it is most likely due to the fact that the SSH key can't be read.

Have you ever had such a problem, and do you know a way to fix it?

**Comment by jlupi** [comment]
You probably have to `chown` and `chmod` the `.ssh` directory. [This] (http://superuser.com/questions/348694/bad-owner-or-permissions-error-using-cygwins-ssh-exe) should help.

**Comment by lgricius** [comment]
I think it would be better to make a symlink to your .ssh/config file

**Comment by Honwhy** [comment]
I have met this problem before, and I changed the file access authority to solved the problem.
```
chmod 700 id_rsa
````
![image](https://cloud.githubusercontent.com/assets/2212273/7439902/49a7bc64-f0c6-11e4-9325-977994478e2e.png)

**Comment by csansone** [comment]
I just encountered this same problem and the same error message:

```
Bad owner or permissions on /home/Username/.ssh/config
```

I had used the windows command line to create the symlink.

I got it working by crating the symlink from within the Babun shell instead:

```
ln -s /c/Users/USERNAME/.ssh /home/USERNAME/.ssh
```

Notes:

- Remove previous symlink attempt
- substitute USERNAME with actual username
- This worked for me on Win 7 Professional

**Comment by tombujok** [comment]
Thx for the hints.

**Comment by cmartin81** [comment]
@csansone Thanks for the tips! It helped creating a symlink!

**Comment by superbeef150** [comment]
I had to remove .ssh from the tail end of @csansone 's answer for it to work.

Made a lazy version for anyone future friends who are interested, don't have to replace anything:

`cygpath -D | xargs -I{} ln -s {}/../.ssh ~`
