### ISSUE TITLE
All files created with group execute bit set

### ISSUE THREAD

**Issue by mpcomplete** [babun/babun#329]
Every file I create has the g+x bit sit. e.g.

{ tmp }  » rm foo; touch foo; ls -l foo
-rw-rwxr--+ 1 mp None 0 May  1 03:51 foo
{ tmp }  » umask
0022

Changing my umask doesn't help. All new files have g+rwx - though the umask does affect user and world modes:

{ tmp }  » umask 000; rm foo; touch foo; ls -l foo
-rw-rwxrw-+ 1 mp None 0 May  1 03:54 foo
{ tmp }  » umask 777; rm foo; touch foo; ls -l foo
----rwx---+ 1 mp None 0 May  1 03:54 foo

I don't have this issue in cygwin.

**Comment by mpcomplete** [comment]
Digging more into it, I found https://cygwin.com/faq/faq.html#faq.using.ssh-pubkey-stops-working (from https://cygwin.com/ml/cygwin/2015-02/msg00100.html ). So it has something to do with ACLs. Running getfacl shows:

{ tmp }  » getfacl foo
# file: foo
# owner: mp
# group: None
user::---
group::---
group:Authenticated Users:rwx
group:SYSTEM:rwx
group:Administrators:rwx
group:Users:r-x
mask:rwx
other:---

Conclusion:
- This is actually an issue in cygwin, just a later version than I have installed.
- I still don't know how to fix it.

**Comment by mpcomplete** [comment]
Figured it out. It had to do with the ACLs on the directory I was in:
  getfacl .
# file: .
# owner: mp
# group: None
user::rwx
group::r-x
group:Authenticated Users:rwx
group:SYSTEM:rwx
group:Administrators:rwx
group:Users:r-x
mask:rwx
other:r-x
default:user::rwx
default:group::r-x
default:group:Authenticated Users:rwx
default:group:SYSTEM:rwx
default:group:Administrators:rwx
default:group:Users:r-x
default:mask:rwx
default:other:r-x

If I run "setfacl -b ./", it clears the mask on the directory and any new files will have the proper modes set. I just did that on my home dir and all is goood.

**Comment by svnpenn** [comment]
Fair warning to anyone using setfacl - it can kill your drive, possibly requiring a reinstall of Windows.
http://cygwin.com/ml/cygwin/2015-04/msg00103.html
