### ISSUE TITLE
Bug: New Vanilla install of Babun on Windows 7 x64 fails to create "Open Babun Here" in Context Menu

### ISSUE THREAD

**Issue by gdvallance** [babun/babun#336]
First, thank you for a wonderful piece of work.

I have just installed Babun so I can try and learn and use zsh shell on my Windows 7 x64 machine. However, the install does not, as the README suggests, create a context menu with "Open Babun Here"

![babun context menu issue unscaled](https://cloud.githubusercontent.com/assets/807161/7721390/23181cf8-fecf-11e4-8db7-ecf99d35d417.png)

I have had a look at other issues that are seem pertinent, but none seem to apply or have been closed as fixed. See issues #183 and #272. (I searched issues under term "Context"). 

Any suggestions on fixing this? Happy to help track down what is going on.

Thank you. 

gdvallance

**Comment by jlupi** [comment]
You are still on Babun 1.1.1, The context menu entry comes with 1.2.0 which will be released soon. On the official website babun.github.io we do not mention this feature yet. Stay tuned.

**Comment by gdvallance** [comment]
jlupi thanks for the clarification. However, maybe I can be excused because the feature is mentioned https://github.com/babun/babun (here) and the normal convention is that the README / Documentation on GitHub is for the current release rather than for *future* releases. Nor is this made clear. Hey ho ... :-)

No problem. I look forward to v1.2.0


gdvallance
