### ISSUE TITLE
command error message show zsh even after switch to bash 

### ISSUE THREAD

**Issue by shuhari** [babun/babun#337]
I have switched to bash using command "babun shell /bin/bash". but when I came into error, the shell still shows zsh, as following: 
zsh: command not found: abc

and "echo $SHELL" or "echo $0" still shows /bin/zsh

babun version: 1.1.1 cygwin 1.7.35 on Windows7

**Comment by tombujok** [comment]
Please read the output of babun --help

Usage:
  "babun shell <new_shell>" to set the user's default shell to new_shell
  "babun login" to login to the user's default shell

to login to user's default shell either restart babun or use babun login
