### ISSUE TITLE
cat /proc/$PID/environ command not work

### ISSUE THREAD

**Issue by shuhari** [babun/babun#338]
while "ps aux" gives the first PID of 5028, the following command 
cat /proc/5028/environ
shows error:
cat: /proc/5028/environ: No such file or directory

babun version: 1.1.1 cygwin 1.7.35 on Windows7

**Comment by tombujok** [comment]
I see the following things when I do ls on a proce/pid.

{ code } master » ls -a /proc/11324/                                                                                     
.   cmdline  cwd  exename  gid   mountinfo  pgid  root  stat   status  winexename
..  ctty     exe  fd       maps  mounts     ppid  sid   statm  uid     winpid

The lack of environ is definitely not a babun's fault - you can have a look at cygwin's manual/faq
