### ISSUE TITLE
Zsh ignoring oh-my-zsh.hide-status git config

### ISSUE THREAD

**Issue by tomlankhorst** [babun/babun#342]
Using **agnoster** as my Oh-my-zsh theme. After entering a command the shell takes a lot of time to show the input line again (3-4s for large repos). This slowness is causes by the call to 'git status'. This should however be possible to avoid checking the status by setting the git config key 'oh-my-zsh.hide-status' to 1. This however does not work, the shell keeps showing git's status. 

```
git config --global oh-my-zsh.hide-status 1
git config --get --global oh-my-zsh.hide-status
# returns 1
```

**Comment by tomlankhorst** [comment]
The slowness was traced down to the Agnoster theme and git on windows. End of the issue.

**Comment by arijoon** [comment]
Did you find a way to speed it up? I feel like the underlying theme is using the wrong git to execute commands
