### ISSUE TITLE
cygdrive plugin slows startup

### ISSUE THREAD

**Issue by ghost** [babun/babun#355]
I apologize if that is solved in the latest version, I'm using 1.1.0 from the downloadable zip file.

On my windows system zsh took about 4 seconds to appear which is a bit much in my opinion. After reading through startup scripts i managed to identify cygdrive plugin as a source, which kind of makes sense since it seemingly foreach-es through all the system volumes which may be a potentially rather slow operation.

I have disabled it on my installation but there doesn't seem to be any rcfile knob to do so, maybe adding that would be a good idea for people with a lot of (or slow) volumes mounted.

**Comment by jlupi** [comment]
will be fixed in #393
