### ISSUE TITLE
Passwords showing as plain texts

### ISSUE THREAD

**Issue by labsterx** [babun/babun#360]
When I use some commands that require a password (for example, FTP), the passwords I typed in after the password promote shows up as plain texts instead of "*******". This is big security problem and I hope it can be fixed soon. Thanks!

**Comment by darinkes** [comment]
Beside this is not a babun issue, if you really care about security: Don't use ftp!
The password is transported in plain text over the network.
So I don't even have to check your screen to get your password...

Instead use SSH! No password echo and everything is crypted!

**Comment by labsterx** [comment]
Yes, I totally agree about your comment on the security issue. But there do exist use cases when you have to type in password in the terminal other than FTP. And a lot of times you do not want the password showing up on the screen (for example, during a pair-programming section). I guess both Mac terminal and Windows command prompt hide passwords. Is there any reason why Babun doesn't support password hiding? I don't remember seeing passwords showing up when using Cygwin....

**Comment by darinkes** [comment]
Which tool(s) you are talking about and how do you start it?

**Comment by labsterx** [comment]
As a recent example, I have a Android keystore file stored locally (for Google Play store app submissions) and I was trying to use this command to extract info for this file:

$ keytool -list -keystore my-android-release-key.keystore

Then I see a prompt: "Enter keystore password: "

When I enter my password, all characters of that password show up on the Babun terminal screen.

BTW, Babun is really a great product and I use it every day. I can see only two thing missing. One is this password issue. Another is the support for tabs. I do believe this product have the great potential to become one of most popular window-based envelopment tools. Thanks.

**Comment by darinkes** [comment]
And whats happens if you run this command in a cmd or powershell window?

**Comment by labsterx** [comment]
I can see your point. I have some env issue to run the same command in cmd. But I can give you another example: That's when I use FTP (Let's for the time being put aside the discussion on whether FTP is secure or not). If you do 'ftp hostname.com' and follow the steps, your password will show up when using babun while it will be hidden when using cmd.

**Comment by darinkes** [comment]
What does "which ftp" give you?
Is it also "/cygdrive/c/WINDOWS/system32/ftp.exe"?

Don't use windows system tools in babun, they are most likely just programmed/tested for Windows programms.
Solution: Install a ftp client via pact e.g. ncftp.

Again: This is not an Issue of babun/cygwin. Password hiding needs to be done correctly inside the tools.

**Comment by labsterx** [comment]
ok. thanks.
