### ISSUE TITLE
please support "pact install maven"

### ISSUE THREAD

**Issue by ihadanny** [babun/babun#362]
need to install maven, thanks!

**Comment by jlupi** [comment]
mvn in not available as a cygwin package, so it is not possible to install it via pact. 

You have to install mvn and add it to your path.

**Comment by xjlin0** [comment]
To use maven in cygwin, you need to link to Windows native binaries
https://geekforum.wordpress.com/2015/03/19/install-git-and-maven-for-cygwin/
