### ISSUE TITLE
libMagickCore6_2 package in wrong compression format?

### ISSUE THREAD

**Issue by piw** [babun/babun#369]
I tried to install emacs-w32 but encountered the following error regarding libMagickCore6_2 package:

xz: (stdin): File format not recognized
tar: Child died with signal 13
tar: Error is not recoverable: exiting now

Using 7zip I can see the downloaded cygwin package is actually in bzip2 compression, no doubt the xz cannot recognize it.

I'm not sure if this is a bug in Babun or an upstream issue of cygwin. Is there a solution that I can repack it into xz format and process with installation?

Thank you!

**Comment by wallacewinfrey** [comment]
I am also experiencing this issue, but in slightly different circumstances. When I launch emacs-w32, I get this message:

`/usr/bin/emacs-w32.exe: error while loading shared libraries: cygMagickCore-6.Q16-2.dll: cannot open shared object file: No such file or directory`

**Comment by wallacewinfrey** [comment]
If I unpack  cygMagickCore-6.Q16-2.dll in my home directory, emacs-w32.exe works without issue.

**Comment by piw** [comment]
That works, thank you!

**Comment by wallacewinfrey** [comment]
I dunno if I'd say this fixed this - my suggestion is more of a workaround. I suggest you re-open so the devs can fix the underlying issue...

**Comment by piw** [comment]
I reported it on cygwin mailing list and they've taken care of it.
