### ISSUE TITLE
Add alias to .zshrc

### ISSUE THREAD

**Issue by phuongtailtranminh** [babun/babun#371]
Hi guys,

I'm trying to add my custom alias to zsh. On my OSX, i simply do it by adding a line to .zshrc then source it.

But when i do the same thing with babun on windows, there are some error after i restart babun.

"compdef: unknown command or service: git" and many line before this line "colors () {
"

Then the auto-complete don't work!

So, how can i add my alias to babun?

**Comment by prondzyn** [comment]
Please, check the [FAQ#31](http://babun.github.io/faq.html#_i_see_compdef_unknown_command_or_service_git). Maybe it will help you.

You should be able to add alias same as on your OSX to .zshrc

**Comment by jlupi** [comment]
What Peter sugessted should help, there are sometimes problems with oh-my-zsh and autocompletion.

Feel free to reopen if the problem still exists.
