### ISSUE TITLE
zsh shell login tip messy code when using gbk

### ISSUE THREAD

**Issue by inxi-pc** [babun/babun#375]
![_20150625142456](https://cloud.githubusercontent.com/assets/8216273/8348448/089fc7ca-1b46-11e5-8345-a1692543fb10.png)

Like this,my zsh shell  symbol ‘>>’ become  ‘禄’ when I use gbk code.what file is the configurate for this?

**Comment by jlupi** [comment]
You can try change your locales in `~/.babunrc`

See https://cygwin.com/faq-nochunks.html#faq.using.weirdchars

And some further reading:
http://stackoverflow.com/questions/10510618/some-of-the-outputs-from-cygwin-just-can-not-be-read-with-bad-encoding
https://cygwin.com/cygwin-ug-net/setup-locale.html

Let me know if it helps, we could update our FAQ if it works.

BTW: The prompt is configured in `babun.bash` for bash and in `babun.zsh-theme` for zsh.
