### ISSUE TITLE
Unusual %USER_HOME% variable on Babun web page

### ISSUE THREAD

**Issue by apjanke** [babun/babun#379]
The Babun web page (at http://babun.github.io/) says that Babun [installs by default to `%USER_HOME%\.babun`](https://github.com/babun/babun.github.io/blob/543e9fee860d48cf35095764dce30a58384d69b6/index.html#L155). `%USER_HOME%` is not a standard Windows environment variable. `%USERPROFILE%` is the Windows environment variable that refers to the user's "home" directory, and is probably what the page should use.

**Comment by jlupi** [comment]
You are right, thanks!
