### ISSUE TITLE
Git Error

### ISSUE THREAD

**Issue by labsterx** [babun/babun#384]
I've been using git on Babun for a long time but today I ran into a problem. Whenever I do any "git pull" (on whatever repository), I got the following error: 

2 [main] git 2548 child_info_fork::abort: C:\Users\user\.babun\cygwin\bin\cygcrypto-1.0.0.dll: Loaded to different address: parent(0x850000) != child(0x830000)
error: cannot fork() for git-pull: Resource temporarily unavailable

Can anybody help on that?

Thanks!

**Comment by papodaca** [comment]
I am seeing this also, tried to work around this by using "git fetch". That also has the same problem.

**Comment by labsterx** [comment]
I did some research and found out the problem was caused by my windows anti-virus software (BitDefender in my case). I fixed the problem by excluding the '.babun' folder in the anti-virus scan setting and everything works fine again.
