### ISSUE TITLE
Create a tab-enabled wrapper for mintty

### ISSUE THREAD

**Issue by tombujok** [babun/babun#39]
In order to support multiple-tabs a tab-enabled wrapper for mintty would have to be created.
Somebody would have to investigate how to do it - and code it up - using mintty codebase. 
Probably it would be a patch to mintty.

**Comment by xjlin0** [comment]
I actually think working on tty problems is more important than multitab -- node.js and Mysql console cannot be shown out of box because of mintty problem. I have to use console2 to workaround.  Make these two consoles working natively would be more important than multitab.

**Comment by tombujok** [comment]
Modifying mintty is probably impossible for now. 
Con-emu and tmux are the possible solutions for now.

**Comment by meffect** [comment]
Conemu does a horrible job beyond tabs. configuration hell, scrolling, window resize, 24bit color bugs everywhere you turn. Using mintty is a joy compared to conemu. I spent weeks trying to get conemu to work right with all the connectors, tricks, workarounds, etc. In the end i'm just pissed off. Tabs would be nice is all i'm sayin
