### ISSUE TITLE
Disable plugins?

### ISSUE THREAD

**Issue by cconrad** [babun/babun#392]
Hi,

first of all, this is a great project, I love how fast one can become productive using babun, instead of fiddling with cygwin configuration for hours to set everything up. Most defaults are very nice. I have a question about the "plugin architecture" that is described on the project's homepage. It sounds to me as if one should be able to disable/enable the different plugins. How would I do that, let's say I want to run zsh, but without oh-my-zsh?

Oh and more question, the last few days nothing happens for me when clicking the download button on the homepage. I had to download from http://projects.reficio.org/babun/babun-dist.zip as described in #220. Not sure if its a local problem, but I believe it was the same on 2 different boxes with Chrome.

Thanks and keep up the great work,
Claus

**Comment by jlupi** [comment]
Hi Claus

at the moment only the the `shell-here` plugin can be switched on/off by executing `babun shell-here remove` or `babun shell-here init. For other plugins we do not have this solution yet (must be coded up). 

The problem with the download - i have to have a look. 

Thanks

**Comment by jlupi** [comment]
The download link should work again

**Comment by cconrad** [comment]
Thanks for the info - and for fixing the download link, it works here now.
