### ISSUE TITLE
Cannot update to 1.2.0 from 1.1.1

### ISSUE THREAD

**Issue by jmclement** [babun/babun#400]
Running a babun check shows that babun is outdated. On running babun update, get pipefail issue.
Converting file using dos2unix sorts the pipefail issue but still cannot update as process stops on fetching origin. See below:

    { ~ }  » babun check                                                                                                          ~
    Executing babun check
    Source consistent [OK]
    Prompt speed      [OK]
    File permissions  [OK]
    Connection check  [OK]
    Update check      [OUTDATED]
    Hint: your babun is outdated. Execute 'babun update'
    Cygwin check      [OK]
    { ~ }  » babun update                                                                                                         ~
    Executing babun update
    : invalid option name: line 2: set: pipefail
    { ~ }  » dos2unix /usr/local/etc/babun/source/babun-core/tools/update_source.sh                                               ~
    dos2unix: converting file /usr/local/etc/babun/source/babun-core/tools/update_source.sh to Unix format...
    { ~ }  » babun update                                                                                                         ~
    Executing babun update
      upstream  [release]
      installed [1.1.1]
      newest    [1.2.0]
    HEAD is now at a4bf46e Regenerating doc with new url
    Fetching origin
          1 [main] git-remote-https 1736 fork: child -1 - forked process 9400 died unexpectedly, retry 0, exit code 0xC0000135, errno 11
    error: cannot fork() for fetch-pack: Resource temporarily unavailable
    error: Could not fetch origin
    Error on or near line 47, last command 'git --git-dir="$babun/source/.git" --work-tree="$babun/source" fetch --all';

**Comment by jessesanford** [comment]
I am having this exact error. What did you do to solve it? Why did you close the issue?

**Comment by jessesanford** [comment]
Anyone else seeing this:

```
{ / }  » babun update
Executing babun update
: invalid option name: line 2: set: pipefail
{ / }  » dos2unix /usr/local/etc/babun/source/babun-core/tools/update_source.sh
dos2unix: converting file /usr/local/etc/babun/source/babun-core/tools/update_source.sh to Unix format...
{ / }  » babun update
Executing babun update
  upstream  [release]
  installed [0.0.0]
  newest    [1.2.0]
HEAD is now at 03cbdd6 fiing broken shortcut
Fetching origin
fatal: unable to access 'https://github.com/babun/babun.git/': error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
error: Could not fetch origin
Error on or near line 47, last command 'git --git-dir="$babun/source/.git" --work-tree="$babun/source" fetch --all';
```

**Comment by Steiny69** [comment]
@jessesanford I get the same thing as you. Even the `installed [0.0.0]`.

**Comment by staminna** [comment]
I also have this. Anyone managed to fix this?
