### ISSUE TITLE
IntelliJ IDEA 14.1.4 Terminal

### ISSUE THREAD

**Issue by cvillanujr** [babun/babun#401]
In IntelliJ I added my .babun path in Tools -> Terminal -> Shell Path
C:\Users\myprofile\.babun\cygwin\bin\mintty.exe

When I click on the terminal tab it opens babun but in a separate window instead of internally. Should I be using C:\Users\myprofile\.babun\cygwin\bin\zsh.exe instead? 

Thanks.

**Comment by jlupi** [comment]
Yes, you have to use either zsh.exe or bash.exe depending on your preferences.

**Comment by tplessis** [comment]
It does not work with Intellij 14.1.4 on windows 10. Nothing happened, terminal is not launched. :/

**Comment by nkoder** [comment]
Maybe it is caused by IntelliJ? I've seen some IntelliJ issue concerning Windows 10 and terminal: https://youtrack.jetbrains.com/issue/IDEA-143300
