### ISSUE TITLE
Minor grammar mistakes in the welcome text

### ISSUE THREAD

**Issue by kkartaltepe** [babun/babun#407]
https://github.com/babun/babun/blob/master/babun-core/plugins/core/src/babun

```
  echo -e "There is a couple of plugins installed by default: oh-my-zsh, pact, cacert, etc."
  echo -e "There is also a lot of dev tools such as git, svn, unix utils, etc"
```
Should be

  echo -e "There **are** a couple of plugins installed by default: oh-my-zsh, pact, cacert, etc."
  echo -e "There **are** also a lot of dev tools such as git, svn, unix utils, etc"

**Comment by tombujok** [comment]
Well, I used to work a lot with the Brits - they frequently use "There's" for plural forms ;)
Here's the explanation: https://www.englishforums.com/English/TherePeople/hqmk/post.htm
Closing for new, but feel free to open a pull request with the correction.
