### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by lotterfriends** [babun/babun#408]
during the installation I got following error:
![image](https://cloud.githubusercontent.com/assets/3378880/8954671/83422980-35e7-11e5-8767-0b3b78c80e9c.png)

when I start start babun anyway I got following message:
![image](https://cloud.githubusercontent.com/assets/3378880/8954649/62a8dc28-35e7-11e5-94a2-6cf1235d9c0f.png)

System: Windows 7

**Comment by mhannen** [comment]
I have the same problem on one system. I got two systems with Windows 10. On the first one, the installation just worked fine. On the other one, it fails with the same error.

**Comment by mhannen** [comment]
Experimented a long time.... turns out reboot and deleting TMP-Files under USERFOLDER\AppData\Local\Temp helped. Could finally reinstall babun :)

**Comment by tombujok** [comment]
You can also close all babun instances and run rebase.bat. It's a stanard cygwin fork problem
