### ISSUE TITLE
Download link and mirrors missing HTTPS and checksum

### ISSUE THREAD

**Issue by Foxboron** [babun/babun#409]
The website for downloading babun should offer HTTPS as default and have a checksum available for verification of the download. This should prevent tampering of the download and help checking the integrity of the file.

HTTPS should also be used on the mirrors for the same reasons. It would be trivial for anyone at this point to DNS spoof the mirror. It is available and just needs to be added https://mirrors.kernel.org/

**Comment by tombujok** [comment]
Good point.
