### ISSUE TITLE
Cannot ssh to github

### ISSUE THREAD

**Issue by louisgv** [babun/babun#418]
Hello,

I generated a ssh keypair, and did `ssh -T git@github.com`, the result was fine:
```Hi louisgv! You've successfully authenticated, but GitHub does not provide shell access.```
However when I tried to clone something, it would return: 

```
Cloning into 'cita'...
Unable to open connection:
Host does not existfatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
I've looked around but haven't found anything similar. Please let me know what I should do,
Thanks for the awesome work,

Louis

**Comment by ericfrancis** [comment]
You cannot ssh to github as you've found out.

You need to add your public key to the github repo you are trying to clone.

**Comment by tombujok** [comment]
Thx for verifying this. Closing.
