### ISSUE TITLE
use Sublime Text 3 as editor for commit message

### ISSUE THREAD

**Issue by idomitori** [babun/babun#421]
I try use [this](https://github.com/babun/babun/issues/299) solution and this `git config --global core.editor "subl -w"`, but it just open new tab in ST3 with template for commit and get me this error:
`git commit`
`Aborting commit due to empty commit message.`

It means -w flag was ignored? How to fix the problem?

**Comment by idomitori** [comment]
I found [this](https://gist.github.com/versedi/d0a1f6635e300a7570fe) solution, and it work for me. It fix incorrect path to a COMMIT_EDITMSG.

**Comment by tombujok** [comment]
FAQ updated. Thx

**Comment by EricSB** [comment]
Dumb question, but when using the solution above, I get this message: /usr/local/bin/subl: line 4: /home/<my user name>/.git/COMMIT_EDITMSG: No such file or directory  The .git folder is present and just for the heck of it, I tried creating a file with the name of COMMIT_EDITMSG and that didn't resolve is... any suggestions?

Thanks in advance!

**Comment by Log1x** [comment]
I know this is old, but I tried all of the suggested methods through out multiple issues concerning subl and found https://github.com/rossy/cyg-subl to be the best solution across the board.

Hopefully this helps someone.

**Comment by gtroeno** [comment]
@Log1x 
> Hopefully this helps someone.

After hours of searching and trying to get subl working in OMZ (default plugin not working), this is the one suggestion that finally made it work - in 2019!

Thank you!
