### ISSUE TITLE
Confused on how to install avr-gcc in babun

### ISSUE THREAD

**Issue by snowe2010** [babun/babun#431]
From my basic googling, I see that avr-gcc can be installed in cygwin, yet I cannot find anything detailing how I should go about getting it into babun. I've tried `pact find avr` and `pact find gcc`, but I can't find any avr-gcc or gcc-avr package. I was under the impression that babun could install any cygwin package, but I guess I'm just not understanding something properly.

**Comment by AnrDaemon** [comment]
Trash babun, download Cygwin setup, install Cygwin, install avr-gcc.
It's really THAT simple.

**Comment by AnrDaemon** [comment]
Detailed instructions can be found at http://cygwinports.org/

**Comment by tombujok** [comment]
It's impossible to install a package that's not in the Cygwin's package repo:
https://cygwin.com/cgi-bin2/package-grep.cgi?grep=avr-gcc&arch=x86

**Comment by snowe2010** [comment]
Couldn't get it to work with cygwin, and it was also a pain to install cygwin. Ended up using MHV AVR Tools with babun and it works perfectly.

**Comment by AnrDaemon** [comment]
Pain? What part of your body you've used to install it?
It is a straightforward 1-2-3 process, and it is thoroughly documented.

**Comment by AnrDaemon** [comment]
TB> It's impossible to install a package that's not in the Cygwin's package repo:
TB>  https://cygwin.com/cgi-bin2/package-grep.cgi?grep=avr-gcc&arch=x86

As has been said, this package is in Cygwin ports, and it is easily possible
to install it directly... using normal Cygwin setup.

**Comment by Firesphere** [comment]
Please, please stop this trolling @AnrDaemon it's annoying and has no value at all.
