### ISSUE TITLE
When starting babun, it takes a long time for prompt to display

### ISSUE THREAD

**Issue by mike-mosher** [babun/babun#434]
When I initially start babun, it takes a long time to get the initial prompt to display.  After that it runs fairly quick.  I can hold down the enter key and it keeps up decently.  It's the initial prompt that can take a long time.   

I have alot of mapped drives in Windows Explorer that I suspect might be causing this.  It can take 3-4 seconds to get the prompt when at work connected by Ethernet.  It will take twice that long on wireless.  When I head home, it will take a long time,  I'm guessing around 20 seconds.   I believe this is due to a timeout of the mapped drives, since I cannot access the drives at home.

I have looked into BLOTA software that would cause this, and even uninstalled Symantec and noticed no difference.  I have changed the shell to bash and back to zsh and notice no difference. I had a default babun install on Win8 and noticed the issue.  I recently did a fresh install of Win10 and noticed the issue again after installing babun.  

I have removed all the mapped drives from windows at home and opened babun and noticed around a 4 second pause before getting the prompt. 

Help troubleshooting is appreciated.  I'm not sure how to stop babun from mapping my windows drives to /cygdrive/

**Comment by jlupi** [comment]
We do not have a mechanism to disable the plugin yet. Just to see if the cygdrive plugin causes the issue open /usr/local/etc/babun/source/babun-core/plugins/start.sh and comment out the line `plugin_start "cygdrive"`. Restart babun. Is it quicker now?

You should revert your change afterwards otherwise you may have conflicts while updating babun. 
If it is a cygdrive issue a pull request with the option to disable it would be appreciated :-)

**Comment by mike-mosher** [comment]
That seems to work, but not in the way I expected.   When I am on my work network with all my network drives connected, and I have commented out `plugin_start cygdrive`, the prompt is displayed very quickly; under 2 seconds.  The odd thing is that it seems that my Windows drives are mapped:

```
{ ~ } master » cd /cygdrive 
{ /cygdrive }  » ls -1                                                                                 /cygdrive
c
q
r
s
t
u
v
w
x
y
z
{ /cygdrive }  » ls -1 t                                                                               /cygdrive
configs
images
tcl-scripts
{ /cygdrive }  »                                                                                       /cygdrive
```

When I am at home (with mapped network drives but not on VPN, so unable to access them), I still get the prompt quickly, but trying to display items in /cygdrive/ it takes 30 seconds:

```
{ ~ } master » cd /cygdrive                                                                                   ~
{ /cygdrive }  » ls                                                                                /cygdrive 130

{ /cygdrive }  » ls                                                                                  /cygdrive 1
c
{ /cygdrive }  »  
```


Is there somewhere else in babun that tries to run cygdrive?  Is it happening when I try to display the contents of the /cygdrive/ folder?

**Comment by jlupi** [comment]
no there shouldn't

**Comment by jlupi** [comment]
>> Is there somewhere else in babun that tries to run cygdrive? Is it happening when I try to display the contents of the /cygdrive/ folder?

nope.

The thing is that now you still have the old drives mapped. Try to remove the symlinks and see if it gets better.

**Comment by mike-mosher** [comment]
I decided to remove my mapped drives.  I have a script to add them whenever I need them.  I prefer the speed of babun over the ease of the mapped drives!  

Thanks for the help.
