### ISSUE TITLE
git pull not working

### ISSUE THREAD

**Issue by Brialius** [babun/babun#438]
➜  ~  git --version
git version 2.1.4
➜  ~  git pull
fatal: 'pull' appears to be a git command, but we were not
able to execute it. Maybe git-pull is broken?
➜  ~  babun --version
babun version 1.2.0
Created and maintained by Tom Bujok (@tombujok)
Copyright (c) 2014-2015.
➜  ~
Executing daily babun check:
Source consistent [OK]
Prompt speed      [OK]
File permissions  [OK]
Connection check  [OK]
Update check      [OK]
Cygwin check      [OK]

Have Windows 10 Pro x64
Try to reinstall, delete old cygwin, uninstall windows git, but all it not helped :(

**Comment by stanleystl** [comment]
My machine have the same versions and I was having the same issue. In my case, I also had Scoop installed and it added an Environment Variable named _GIT_SSH_ that was changing the path for my ssh.exe. Deleting that variable and restarting babun made it work.

Copying the files from C:\Users\\_USERNAME_\\.ssh into /home/_USERNAME_/.ssh also worked, but I prefer the solution above, which didn't break Scoop, btw.

**Comment by Brialius** [comment]
I've reinstalled OS and this error is gone.

**Comment by srinisoundar** [comment]
@Brialius  @stanleystl I'm also facing the same issue. reinstall didn't help. Any other solution ?

Thanks,
Srini
