### ISSUE TITLE
Disable creation of ".un~" files

### ISSUE THREAD

**Issue by jmcomets** [babun/babun#446]
First of all, great job with babun, I'm very pleased to return to a unix-y shell on Windows. :beers:

Now on to my issue, I can't figure out where all these `.<filename>.un~` files are coming from, and they're really annoying (especially with version control). I'd like to disable their creation if it doesn't screw up babun too much.

Note that my usual workflow is working with Vim under a Tmux session.

**Comment by jlupi** [comment]
this are the vim's backup files. You can disable them. Have a look here http://stackoverflow.com/questions/607435/why-does-vim-save-files-with-a-extension

**Comment by jmcomets** [comment]
Nope. `set backup?` returns `nobackup`

**Comment by jlupi** [comment]
yeah, sorry i should be more precise. the `un~` are undo files and no backup files, so the `set noundofile` should be set. You can create your own `.vimrc` for that in `~`

**Comment by jmcomets** [comment]
I added `set noundofile` in my custom vimrc and that was it.

Small footnote : IMO the default /etc/vimrc file in babun shouldn't change defaults, I'm used to using ex mode and it annoyed me to have Q mapped, or in this case the noundofile option was set by default.
