### ISSUE TITLE
powerline fonts

### ISSUE THREAD

**Issue by jrock2004** [babun/babun#448]
So I installed the powerline fonts from https://github.com/powerline/fonts and installed them in the windows fontbook. When I open babun and go to options to change the font. I see the fonts there but when I select one of the meslo and hit ok I get

```
There is no font with that name.
Choose a font from the list of fonts.
```

Any ideas?

**Comment by jrock2004** [comment]
I realized that this is a mintty issue not a babun issue

**Comment by DanielGGordon** [comment]
I am also having this issue. Did you find a solution?
