### ISSUE TITLE
pact does not install ruby gem command

### ISSUE THREAD

**Issue by bertramn** [babun/babun#450]
Hi guys, I just installed ruby via pact but once finished the gem command are not available. Any idea where the spanner could jam?

```sh
{ ~ }  » pact install ruby
...
{ ~ }  » ruby --version
ruby 2.2.2p95 (2015-04-13 revision 50295) [i386-cygwin]

{ ~ }  » gem --version
-bash: gem: command not found
```

BTW absolutely love it :+1:

**Comment by jrock2004** [comment]
Does gem.bat --version work?

**Comment by bertramn** [comment]
Unfortunately not. I compared the babun install with my local cygwin install that works correctly and the only thing that looks like gem is below:

```sh
{ / }  » find /usr -name gem
/usr/local/etc/babun/external/oh-my-zsh/plugins/gem
/usr/local/etc/babun/home/oh-my-zsh/.oh-my-zsh/plugins/gem
```

**Comment by jrock2004** [comment]
Taking the site below it looks like you need to download and install rubygems separately. 

http://phaseshiftllc.com/articles/2008/10/02/setting-up-rails-on-windows-with-cygwin.html

**Comment by bertramn** [comment]
can confirm `pact install rubygems` does the trick. Thanks for the pointer!

**Comment by numediaweb** [comment]
Please see https://github.com/babun/babun/issues/93#issuecomment-160977126
