### ISSUE TITLE
Installed emacs - but it does not start

### ISSUE THREAD

**Issue by nullp01nt3r** [babun/babun#453]
```
{ babun-1.2.0 }  » emacs                                 /cygdrive/c/apps/programming/babun-1.2.0
/usr/bin/emacs-nox.exe: error while loading shared libraries: cygdbus-1-3.dll: cannot open shared object file: No such file or directory
```
Emacs has been installed via: `pact install emacs`.

I tried the workarounds suggested in the FAQs related to message `error loading shared libraries` - but none worked (gettext, and ca-certificates were already installed; libsasl2 was not found by pact).

**Comment by gejianxin** [comment]
pact install dbus
