### ISSUE TITLE
[RELEASE BLOCKER] Problem with git and https proxy auth on the newest Cygwin 

### ISSUE THREAD

**Issue by tombujok** [babun/babun#455]
Guys, there's a problem with git on the newest cygwin.
If the https proxy is set there's a bug in git (and underlying curl) that makes it impossible to clone/fetch.
Babun uses git extensively in the update mechanisms, thus we can't release...
Could anybody try to look into it apart from us. For now, we don't have any solution.

Steps to reproduce:
- install newest cygwin
- install git
- use one of the well known https proxies that use authentication
- git clone anything

**Comment by tombujok** [comment]
I think @jlupi tried to ask on Cygwin.com with no luck
https://www.cygwin.com/ml/cygwin/2015-09/msg00296.html

Anybody could help on this one? One guess would be to replace git.exe with an older one by hand and see if it works.

**Comment by jlupi** [comment]
Further details here https://www.mail-archive.com/cygwin@cygwin.com/msg143981.html

**Comment by tombujok** [comment]
Is anybody willing to look into this?

**Comment by jlupi** [comment]
The issue was confirmed and addressed to the committer of the change. Fix to be expected in one of the future git releases. 

http://git.661346.n2.nabble.com/Commit-5841520b-makes-it-impossible-to-connect-to-github-from-behind-my-company-s-firewall-td7641599.html

Workaround in progress...

**Comment by jlupi** [comment]
Fixed in #496, Target release 1.3.0 #393
