### ISSUE TITLE
Disable pwd listing on right side of current line

### ISSUE THREAD

**Issue by inspirebin** [babun/babun#461]
![untitled](https://cloud.githubusercontent.com/assets/5962044/10066075/852faec4-62ac-11e5-9da6-e30600037d65.png)

Babun lists the current working directory on the right side , as i have highlighted in the image. That tends to take a lot of space and i want to disable it . I could not find an option to remove it via the options menu.

**Comment by telekenetix** [comment]
You just need to choose a different theme.

Go into your .zshrc
```console
$ vim ~/.zshrc
```

and edit the ZSH_THEME
```vim
# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="ys"
# My theme is ys :)
```

Check here for screenshots and pick one that does not have the directory on the right hand side.
https://github.com/robbyrussell/oh-my-zsh/wiki/themes

**Comment by jlupi** [comment]
thanks for answering
