### ISSUE TITLE
oh-my-zsh git prompt very slow on some Windows hosts

### ISSUE THREAD

**Issue by tombujok** [babun/babun#48]

**Comment by baudren** [comment]
@tombujok, I still suffer from very slow git prompt (Win8.1), whenever I am inside a git repository, it takes 5 or 6 seconds to display the line (on a newly created repo, with just a few commits). Can you share which theme was the one you added to share this issue? Thanks in advance,

**Comment by sashokbg** [comment]
Same problem here. Babun takes a long time to show prompt and git status takes forever

**Comment by davidvartanian** [comment]
Same problem here, Windows 10, just trying babun within git working directory.

**Comment by baudren** [comment]
@MatanRubin thanks - I had missed that. Indeed, with the "babun" theme, the speed is back to normal. I am still unsure what the other themes got wrong, and/or if it is possible to apply the speed fix to all of them in a transparent way.

In any case, thanks @tombujok for the fix!

**Comment by samiraguiar** [comment]
I have a similar problem (my theme is set to babun).

`git status` takes around 0.5 seconds when run in bash (from Git for Windows) and around 2 seconds when run in Babun. The funny thing is: if I run `git status` in bash and then run the same command in babun it takes 5 seconds the first time and the subsequent times take the same 2 seconds.

**Comment by zbennett10** [comment]
Same here.. have babun theme as well.

**Comment by nealhnguyen** [comment]
How did you optimize babun's theme for git prompt? How would I do the same for another zsh theme?

**Comment by igitur** [comment]
@tombujok Here is another thread about possible enhancements to speed up the git prompt on cygwin. Seems we have to avoid forks at all costs.

https://github.com/robbyrussell/oh-my-zsh/issues/5486

**Comment by yakzan** [comment]
I gained 2 seconds commenting out the vcs_info line in the prompt_git function in the agonster-theme file; now it takes only half a second to return to the prompt. 


`prompt_git() {
  (( $+commands[git] )) || return
  local PL_BRANCH_CHAR
  () {
    local LC_ALL="" LC_CTYPE="en_US.UTF-8"
    PL_BRANCH_CHAR=$'\ue0a0'         # 
  }
  local ref dirty mode repo_path
  repo_path=$(git rev-parse --git-dir 2>/dev/null)

  if $(git rev-parse --is-inside-work-tree >/dev/null 2>&1); then
    dirty=$(parse_git_dirty)
    ref=$(git symbolic-ref HEAD 2> /dev/null) || ref="➦ $(git rev-parse --short HEAD 2> /dev/null)"
    if [[ -n $dirty ]]; then
      prompt_segment yellow black
    else
      prompt_segment green black
    fi

    if [[ -e "${repo_path}/BISECT_LOG" ]]; then
      mode=" <B>"
    elif [[ -e "${repo_path}/MERGE_HEAD" ]]; then
      mode=" >M<"
    elif [[ -e "${repo_path}/rebase" || -e "${repo_path}/rebase-apply" || -e "${repo_path}/rebase-merge" || -e "${repo_path}/../.dotest" ]]; then
      mode=" >R>"
    fi

    setopt promptsubst
    autoload -Uz vcs_info

    zstyle ':vcs_info:*' enable git
    zstyle ':vcs_info:*' get-revision true
    zstyle ':vcs_info:*' check-for-changes true
    zstyle ':vcs_info:*' stagedstr '✚'
    zstyle ':vcs_info:*' unstagedstr '●'
    zstyle ':vcs_info:*' formats ' %u%c'
    zstyle ':vcs_info:*' actionformats ' %u%c'
    #vcs_info
    echo -n "${ref/refs\/heads\//$PL_BRANCH_CHAR }${vcs_info_msg_0_%% }${mode}"
  fi
}
`
