### ISSUE TITLE
How to run a bash script in babun?

### ISSUE THREAD

**Issue by aborruso** [babun/babun#488]
Hi,
I would like to start from hello world:

    #!/bin/bash
    echo Hello World 

How to run it in babun?

Thank you

**Comment by Evolution0** [comment]
Save to a file with or without the .sh extension then either: sh filename or ./filename

**Comment by aborruso** [comment]
thank you @Evolution0

**Comment by Xerus2000** [comment]
I would like to actually have it in the Windows open-with contest-menu integration to run a shell script with Babun, instead of having to first start and then run the script. Git bash also does that.
