### ISSUE TITLE
Windows like paths not accepted

### ISSUE THREAD

**Issue by grze87** [babun/babun#493]
Hi there,

I often copy windws like path c:\dir1\dir2\dir3 and want to use it in babun like this

cd c:\dir1\dir2\dir3

Currently Babun says:

cd: no such file or directory: c:\dir1\dir2\dir3

Would be great to have it find out that it is windows path, convert into linux  one /cygdrive/c/dir1/dir2/dir3  and cd into it.

**Comment by yaci** [comment]
@grze87 I think this may be because '\' is treated as escaping character, not path separator. I am aware of three alternative ways that work:
* cd c:\\dir1\\dir2\\dir3
* cd 'c:\dir1\dir2\dir3'
* cd c:/dir1/dir2/dir3

**Comment by grze87** [comment]
al right, second option works good. First option does not work.

regards

2015-10-28 20:14 GMT+01:00 Jacek Maciejewski <notifications@github.com>:

> @grze87 <https://github.com/grze87> I think this may be because '\' is
> treated as escaping character, not path separator. I am aware of three
> alternative ways that work:
>
>    - cd c:\dir1\dir2\dir3
>    - cd 'c:\dir1\dir2\dir3'
>    - cd c:/dir1/dir2/dir3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babun/babun/issues/493#issuecomment-151961179>.
>



-- 
pozdrawiam,
Grzegorz Wojciechowski
