### ISSUE TITLE
Lizard does not work

### ISSUE THREAD

**Issue by itavero** [babun/babun#499]
I already had Python and [Lizard](http://lizard.ws) installed on my Windows installed on my Windows machine.
After installing Babun (I'm using bash as my default shell) it is not possible to run lizard from the command line:

```
{ ~ }  » lizard
C:\Python27\python.exe: can't open file '/cygdrive/c/Python27/Scripts/lizard': [Errno 2] No such file or directory
```

It does work on my Windows command line and `pip` indicates that it is installed.

**Comment by adamarthurryan** [comment]
I'm pretty sure you'll need to maintain two separate copies of Python if you want to use it both in the Windows command shell and in Babun. To install Python for Cygwin/Babun, just `pact install python`.

**Comment by itavero** [comment]
That's too bad. Guess I'll just stick with the bash that my Git installation offers me for now.
