### ISSUE TITLE
Chrome (v. 47) blocks babun download as malicious

### ISSUE THREAD

**Issue by HyBRiD1492** [babun/babun#537]
I Just downloaded babun and Chrome blocks it:
babun-1.2.0-dist.zip may harm your browsing experience, so Chrome has blocked it.

**Comment by sahat** [comment]
Ran into the same issue, although it's pretty easy to bypass it in the Downloads (CTRL+J).

**Comment by feimosi** [comment]
It's a known issue. Duplicate of #464
