### ISSUE TITLE
Why does babun mount /cygdrive with noacl

### ISSUE THREAD

**Issue by PW999** [babun/babun#540]
Why does babun mount the drives with the `noacl`option ? I found that this breaks every tools which changes file rights and all files and folders have the curent user as owner and 'None' as group ownership.
chmod, chown, chgrp and setfacl do not work with this option and thus it become impossible to use tools like ssh (because you need 0600 permission on the private key) or to make any shell script executable.

**Comment by vyazelenko** [comment]
+1
This needs to be changed.

**Comment by piaolinzhi** [comment]
+1
It make my crazy.

**Comment by piaolinzhi** [comment]
I found a solution and worded in my env.
Create a file and name the file with you login name under /etc/fstab.d/.
Edit the file and copy the following content into the file 
   none /cygdrive cygdrive binary,acl,posix=0,user 0 0

then close all the babun or cygwin process and restart the babun.

**Comment by planesweep** [comment]
project is dead
