### ISSUE TITLE
Can't using Anacoda3 python3.5 and g++.

### ISSUE THREAD

**Issue by jiamo** [babun/babun#544]
{ ~ }  » which python3.5                                                                        ~
/cygdrive/d/Anacoda3/python3.5
{ ~ }  » python3.5     

Can't response. And the windows cmd can use it well.

![screenclip](https://cloud.githubusercontent.com/assets/732751/12053225/e80299c0-af51-11e5-936d-2d960b3f50e6.png)

**Comment by jiamo** [comment]
g++ is similar.
{ ~ }  » g++ --version                                                                          ~
{ ~ }  » g++                                                                                      ~ 127
{ ~ }  » babun check                                                                        ~ 127
Executing babun check
Source consistent [OK]
Prompt speed      [OK]
File permissions  [OK]
Connection check  [OK]
Update check      [OK]
Cygwin check      [OK]

**Comment by jiamo** [comment]
I aslo use `pact install python3`  to install python3 
While I find  .babun\cygwin\bin the python3 is a empty file but have a file name.

**Comment by AnthonyWC** [comment]
You can install with ```pip install python3```
