### ISSUE TITLE
How do a I run babun in cmder?

### ISSUE THREAD

**Issue by yuqigong** [babun/babun#546]
I was using babun and windows command in cmder.
I have many *.bat files, can only be used cmder.But I need babun again.
Hope to have a solution, thank you~

**Comment by TiTnOuK** [comment]
1- Add new task in CMDER settings
2- Rename task by *{Babun}*
3- add this command in **Task Parameters**: 
```
/icon "%userprofile%\.babun\cygwin\bin\mintty.exe" /dir "%userprofile%"
```
4- add this command in **Commands**: 
```
%userprofile%\.babun\cygwin\bin\mintty.exe /bin/env CHERE_INVOKING=1 /bin/zsh.exe
```
You're now ready to use Babun in CMDER ! :)

**Comment by DanielGGordon** [comment]
I think this was addressed elsewhere as well - but this would be a good thing to add to the wiki (and maybe to Cmder's wiki)
