### ISSUE TITLE
is there a way to remove or modify "username@host" from title bar?

### ISSUE THREAD

**Issue by solor** [babun/babun#548]

**Comment by solor** [comment]
solved.

**Comment by lbjdaking23** [comment]
@solor do your remember what you did to remove it? I am going insane trying to remove it lol

**Comment by lbjdaking23** [comment]
My sanity is actually restored. For anyone trying to find the location in the future I found the screen.plugin.zsh file and found "TAB_TITLE_PREFIX" and modified that.
