### ISSUE TITLE
Windows 7 install errors and warnings

### ISSUE THREAD

**Issue by Drugoy** [babun/babun#586]
Apart from errors mentioned in issue #552 I get some extra ones:
A. On 'Fixing symlink' stage I get these errors:

```
…
Fixing symlink -> /usr/bin/makeinfo
Fixing symlink -> /usr/bin/mcdiff
File not found: C:/Users/myUserHere/.babun/cygwin/bin/mc
Fixing symlink -> /usr/bin/mcedit
File not found: C:/Users/myUserHere/.babun/cygwin/bin/mc
Fixing symlink -> /usr/bin/mcview
File not found: C:/Users/myUserHere/.babun/cygwin/bin/mc
Fixing symlink -> /usr/bin/ncurses5-config
…
Fixing symlink -> /usr/bin/rnano
File not found: C:/Users/myUserHere/.babun/cygwin/bin/nano
Fixing symlink -> /usr/bin/rview
…
Fixing symlink -> /usr/bin/zipinfo
File not found: C:/Users/myUserHere/.babun/cygwin/bin/unzip
Fixing symlink -> /usr/lib/cpp
```

There are `mc.exe`, `nano.exe` and `unzip.exe` but not `mc`, `nano` and `unzip` in that folder.

B. Later on the `installing plugin's home` stage I get this warning:

```
Installing plugin's home [core]
WARNING: Git push strategy set to  which is unsupported - changing to 'matching'
Installing plugin's home [cygfix]
```

C. On the very last stage I get these errors:

```
…
Error updating setup.ini, reverting

Installing chere
Package chere not found or ambiguous name, exiting
Operation finished successfully.
Operation finished successfully.
…
```

**Comment by wsgavin** [comment]
I can validate I am having the same errors on Windows 7 as well.

**Comment by Drugoy** [comment]
Well, judging by https://github.com/babun/babun/graphs/contributors babun project is hardly alive.

**Comment by rappard** [comment]
The setup.ini error (point C) is most likely due to the installer trying to retrieve the following file:
  http://mirrors.kernel.org/sourceware/cygwin///setup.ini (copy/paste verbatim from the cmd window)
This location gives a 404 error, not sure what the current location is.

Environment:
Windows 7 Enterprise [Version 6.1.7601]
cmd.exe > Run as administrator (C:\windows\system32>)
Babun 1.2.0 distribution
