### ISSUE TITLE
How to make babun/cygwin home directory equal windows home directory?

### ISSUE THREAD

**Issue by Chiel92** [babun/babun#591]
I just installed babun. I want the cygwin user home directory to equal my windows home directory. So, to be clear, I don't want to add the cygwin home to the `C:\Users` as a new user, I want it to be the same as my current windows home directory.

Now, according to this post, http://stackoverflow.com/questions/1494658/how-can-i-change-my-cygwin-home-folder-after-installation, there is a neat way to make the cygwin home directory point to your windows home directory. You open the file `/etc/nsswitch.conf` and make sure is has a line `db_home`: windows. However, after restarting my pc,  `echo $HOME` still says `/home/chiel.tenbrinke`, which is not what is should be. It should say something like `/cygdrive/c/Users/Chiel.tenBrinke`.

Why is this not working?

My cygwin version is `CYGWIN_NT-6.1-WOW IM-Chiel-2015 1.7.35(0.287/5/3) 2015-03-04 12:07 i686 Cygwin`.

**Comment by TimDeve** [comment]
Read the [FAQ](http://babun.github.io/faq.html#_how_to_use_the_windows_user_profile_directory_as_my_home_directory_in_babun) before posting an issue.

**Comment by Chiel92** [comment]
Thanks
