### ISSUE TITLE
Uninstall?

### ISSUE THREAD

**Issue by tomgraham** [babun/babun#597]
Yes, I know, delete the directory. But that's not a clean uninstall. There are still registry key settings, including that my context menu still has "Open Babun Here" instead of "Open Command Here" which is a major annoyance.

**Comment by confuser** [comment]
Under your .babun directory, there is an `uninstall.bat` script

**Comment by jlupi** [comment]
FAQ 6. http://babun.github.io/faq.html#_how_can_i_uninstall_babun

**Comment by distinguished-git** [comment]
uninstall.bat just throws tons of errors and doesn't uninstall your malware.
