### ISSUE TITLE
zsh auto completion has many useless results (*.exe, *.dll)

### ISSUE THREAD

**Issue by krrr** [babun/babun#598]
I'm on Windows 8.1 with latest babun. When I open prompt and type "python" and hit tab zsh give me
```
python            python2           python2.7.exe     pythonw.exe
python.exe        python2.7         pythonw
```

I have already used `zstyle ':completion:*:complete:-command-:*:*' ignored-patterns '*.dll'` to remove `*.dll`, but it doesn't work for `*.exe`. How can I remove them?

**Comment by skywind3000** [comment]
take this:

```
zstyle ':completion:*:complete:-command-:*:*' ignored-patterns '*.dll|*.exe|*.so|*.pyd'
```
