### ISSUE TITLE
pact's ruby does not work

### ISSUE THREAD

**Issue by brianpeiris** [babun/babun#605]
Running `pact install ruby` succeeds but `ruby -v` does not display anything and exits immediately with exit code 127.

Please let me know what steps I can take to help debug this.

**Comment by Pixelshot** [comment]
Any update on this? I'm facing a similar situation

**Comment by brianpeiris** [comment]
I just ended up compiling ruby from source inside babun. Compilation worked without a problem and ruby works for me now. I guess the pact package just needs to be updated. https://www.ruby-lang.org/en/documentation/installation/#building-from-source

**Comment by CoolCold** [comment]
+1 for the same problem

**Comment by mogthesprog** [comment]
I get exactly the same issue with python actually... Such a strange issue
