### ISSUE TITLE
emacs doesn't run

### ISSUE THREAD

**Issue by jamesla** [babun/babun#629]
New install of babun on windows 10 x64

```
pact install emacs
emacs
zsh: command not found: emacs-nox
```

I've seen an existing issue where this was apparently fixed in 1.10 however I'm on 1.2.0. Any ideas?

**Comment by elzii** [comment]
Bump, same issue.

**Comment by matthewjberger** [comment]
Bump

**Comment by camsolo** [comment]
Bump.

**Comment by KeithBierman** [comment]
I have the original "emacs installed but not running" issue. I tried pact remove emacs; pact install emacs and that didn't do it. I unaliased emacs (so I am now running /usr/bin/emacs -nw instead of emacs-nox). 

having to "fall back" to vi is disconcerting.

**Comment by vipzrx** [comment]
the same problem

**Comment by tfinneid** [comment]
I am having the same problem, annoying...

**Comment by jamesla** [comment]
Moved to bash for windows

**Comment by blambin** [comment]
the some
