### ISSUE TITLE
Window position

### ISSUE THREAD

**Issue by artlantis** [babun/babun#637]
Dear friends,

babun doesn't keep windows position after close. In each session, starting with random position. So, is it possible to keep the previous session position?

**Comment by HiCodin** [comment]
you can try to maximize the babun window and then use that window's colums and rows to keep the session position. It will leave u with maximized style window though if you are ok with that.

**Comment by jungor** [comment]
![image](https://cloud.githubusercontent.com/assets/6581182/24319811/f9ae23ba-1161-11e7-894a-e60043d39319.png)
this setting in window option may work.

**Comment by artlantis** [comment]
@jungor Thank you, I will try that.
