### ISSUE TITLE
Add `cygutils-extra` to pre-installed packages?

### ISSUE THREAD

**Issue by al-the-x** [babun/babun#638]
First off, thanks a ton for all the work on babun. Despite all the headache of frequent `rebaseall` and `fork` / `exec` errors, it makes developing with OSS toolchains much, much less painful on Windows.

I recently ran across a situation where I needed to copy the contents of a file -- my newly generated SSH key -- onto the Windows clipboard for pasting into a web form -- on GitHub -- and noted that the `getclip` and `putclip` commands provided by `cygutils-extra` were not installed already, although all of the dependencies are installed by default. 

Any chance that `cygutils-extra` could be added to the install list? 

Happy to open a PR for this, if someone will point me in the right direction. Thanks again!

**Comment by al-the-x** [comment]
FWIW, I did read about the different ways to shuttle items to and from the clipboard in Cygwin / Windows. I'll enumerate them here for the curious:

* Redirect to (only) the `CLIP` command provided by Windows: `DIR | CLIP` or `CLIP < file.ext`
* Redirect to _or_ from the `/dev/clipboard` pseudo-device: 
  * `cat /dev/clipboard` to view the contents, redirect as normal
  * `cat file.ext > /dev/clipboard` to write to the clipboard
* Use the `getclip` and `putclip` commands from `cygutils-extra`:
  * `getclip` to view the contents, redirect as normal
  * `putclip < file.ext` or `la | putclip` to write to the clipboard

Additional suggestions (aside from redirect variations) welcomed!

**Comment by xizdaqrian** [comment]
That is excellent! First time I've ever heard of that. Yes, please add as a pre-installed package.

**Comment by al-the-x** [comment]
ping.
