### ISSUE TITLE
the input device is not a TTY

### ISSUE THREAD

**Issue by jingcheng407** [babun/babun#655]
![image](https://cloud.githubusercontent.com/assets/7554452/16714382/ccf7b9a0-46f3-11e6-913e-d5afc6cd3562.png)
I want run a docker in babun.
Please help me,thank you!

**Comment by liuxiaopiao** [comment]
Met the same problem...

**Comment by zhaolin0801** [comment]
same problem~~~~~

**Comment by METAJIJI** [comment]
Try this: `TERM=winpty docker run ...`

**Comment by whitecolor** [comment]
This doesn't work, not I have a doubts that "Babun - a Windows shell you will love!"

**Comment by rodrigobdz** [comment]
Have you tried running the command without as `docker run --rm -i ubuntu /bin/bash`?

**Comment by fasihahmed** [comment]
Ran into this problem running a windows container from a windows server 2016 installation.

Using babun 1.2.0 on Win server host machine.

**Comment by raupie** [comment]
Same problem, any update?
`docker exec -it webserver /bin/bash
`the input device is not a TTY. If you are using mintty, try prefixing the command with winpty`

**Comment by satishbt** [comment]
faced the same problem.. Any solution

**Comment by raupie** [comment]
I gave up on babun. Went to WSL and haven't looked back. Zero issues.

**Comment by richardsimoes** [comment]
Same problem here....

**Comment by edwincoder** [comment]
Same problem here....

**Comment by Wythehard** [comment]
Same problem here....

**Comment by Jirry** [comment]
Same problem here....

**Comment by sethbergman** [comment]
Here's what worked for me:
- Pin `babun` shell to taskbar
- Right click on icon > right click on `babun` > Properties
- Replace `mintty.exe -` with `bash.exe -`
- Reopen `babun`
