### ISSUE TITLE
SVN command not recognized after updating via Pact

### ISSUE THREAD

**Issue by rdlaner** [babun/babun#681]
I just updated Subversion (SVN) via pact to the latest SVN version, 1.9.4. Before updating, svn worked fine for me. After updating, however, the svn command is no longer works. I'm using ZSH as my shell and it doesn't explicitly say that the command is not found (and even syntax highlighting shows svn is legit), it just doesn't do anything any more.

I've seen some past issues where it looked like the same thing was happening after git had been updated. Perhaps it is something similar?

**Comment by ma-santamaria** [comment]
It seems to be the same issue. I fixed it by updating all the cygwin installation as @tombujok recomended [here](https://github.com/babun/babun/issues/232#issuecomment-72896728).

**Comment by rdlaner** [comment]
Got it, that seemed to fix it for me. Thanks!
