### ISSUE TITLE
How could I delete `open Babun here` from the menu after uninstall babun?

### ISSUE THREAD

**Issue by wsdjeg** [babun/babun#687]
I  want to reinstall babun, but I do not need `open Babun here` in the menu bar, how could I delete it?

**Comment by engrin** [comment]
[43. I don’t want the 'Open Babun here' option in the context menu](http://babun.github.io/faq.html#_i_don_t_want_the_open_babun_here_option_in_the_context_menu)

**Comment by engrin** [comment]
- install babun again 
- start babun shell
- issue the following command.

```bash
babun shell-here remove
```

**Comment by wsdjeg** [comment]
Got it, thanks!

**Comment by heyjef** [comment]
for anyone in the future that is trying to do this, *but not reinstall babun*, use this (if you have cygwin/bash):
```
local keys=("HKCU\Software\Classes\Directory\Background\shell\babun"
"HKCU\Software\Classes\Directory\shell\babun"
"HKCU\Software\Classes\Drive\Background\Shell\babun"
"HKCU\Software\Classes\Drive\shell\babun")

for key in ${keys[*]}
do 
  cmd /c "reg" "delete" "${key}" "/f" || echo "Failed deleting ${key}"
done
```

if you don't have bash, you will have to go into `regedit` via win+r and delete from the above.

this is directly from the [source](https://github.com/babun/babun/blob/991159167bc4b3c2d1c3fb4aaae12d7710f45504/babun-core/plugins/shell-here/exec.sh#L27-L36)
