### ISSUE TITLE
Full uninstall (including pact packages)

### ISSUE THREAD

**Issue by jamesla** [babun/babun#698]
I broke some of my packages and want to start from scratch with babun.

When I run uninstall.bat it doesnt uninstall the pact packages and when I reinstall its still broken as my broken packages are still there.

How do I completely remove babun?

**Comment by GreyDireWolf** [comment]
Yup same problem with me. uninstall.bat doesn't remove pact packages also I'm having trouble with finding installed location of babun. On website it is mentioned that the location is `%USERPROFILE%\.babun  `  but windows gives error while navigating to that directory(it says it couldn't find the path)

**Comment by jamesla** [comment]
Moved to bash for windows
