### ISSUE TITLE
PHP show nothing

### ISSUE THREAD

**Issue by nuFox** [babun/babun#714]
I tried to install PHP on babun
pact install php
The installation is OK but when i want to test it with a
php --version
nothing appends. No message, no information. And that the same when i want to excute a simple echo with php ... 
i'm on windows 10

**Comment by nuFox** [comment]
Work if you excute the update bash script

**Comment by jeanphorn** [comment]
This problem happened on me too, but "updata" command didn't work.
![babun_show_probem](https://user-images.githubusercontent.com/5744511/30201986-674c2b62-94af-11e7-92d2-db8fc2659664.png)

**Comment by nfrigus** [comment]
Had the same issue after updating from PHP 5.6 to 7.1
Found that you need to run `update.bat` located in babun installation folder.
That seems to resolve the problem.

**Comment by yuzhenlei** [comment]
> Had the same issue after updating from PHP 5.6 to 7.1
> Found that you need to run `update.bat` located in babun installation folder.
> That seems to resolve the problem.

This is right，but update.bat means full download cygwin. we use babun as it is lightweight
