### ISSUE TITLE
Use a newer version of mintty (that supports searching the output buffer)

### ISSUE THREAD

**Issue by RickMohr** [babun/babun#730]
According to  [this post](http://stackoverflow.com/a/38869358), mintty (babun's terminal app) supports searching the output buffer via Alt+F3.

The version of mintty installed by babun is 1.1.3
The latest version of mintty is 2.7.2

Using `pact remove mintty` and `pact install mintty` fetches the latest version, but running it fails with
![image](https://cloud.githubusercontent.com/assets/2162993/21268590/71ea3e46-c37d-11e6-8b1f-6bedf97af57d.png)

If babun used a newer version of mintty we could search the output buffer.

**Comment by svbeon** [comment]
my installation is on 2.7.4, try update.bat?

**Comment by RickMohr** [comment]
That worked, thanks.
