### ISSUE TITLE
Tmux does not work

### ISSUE THREAD

**Issue by entbugger** [babun/babun#744]
After installing and executing tmux (with bash as shell script), it returns the "127" non-zero exit code. Any ideas on possible problems?

**Comment by Zakjholt** [comment]
Same issue

**Comment by paulieadam** [comment]
I had the same problem. Manually running update.bat kind of worked for me. Now I have to run babun as admin to do babun update.

Just to clarify, I ran update.bat from the Command Prompt and not from babun.

**Comment by kitsunekyo** [comment]
@paulieadam solution worked like a charm

**Comment by s4z** [comment]
update.bat solved it for me also, thanks!

**Comment by shuaiwang88** [comment]
where is update.bat

**Comment by Aeres-u99** [comment]
Update.bat is there in .babun directory (or the top most level of folder wherein you have installed babun)
If you have continued with default installation  -
 %userprofile%/.babun/update.bat
or else -
<INSTALLATION_DIR>/.babun/update.bat
