### ISSUE TITLE
Missing `pact.repo` directory?

### ISSUE THREAD

**Issue by moollaza** [babun/babun#77]
I just installed babun and tried running the `pact` command. It seems to be throwing an error related to pact each time I run any pact commands though:

`/usr/local/bin/pact: line 9: /cygdrive/c/Users/Zaahir/.pact/pact.repo: No such file or directory`

The line this refers to is `source ~/.pact/pact/repo` -- I'm assuming this was suppose to be created during the install?

**Comment by perlsky** [comment]
I got started to use the babun for practicing the ansible.
First of all, I updated the cygwin folder using setup-x86.exe from official cygwin homepage becaue update command provided by babun does not work properly. (perl does not fork for instance.)
Now it's very comfortable after then.
