### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by hegga** [babun/babun#774]
Hi,

Is this project dead since the last commit to github was over a year ago? Support for a newer version of cygwin would have been nice.

**Comment by AmundsenJunior** [comment]
Looks like the project's in need of new help: #712

**Comment by kenjones-cisco** [comment]
I took many of the PRs that were viable and pulled them into a branch on my fork of this project. I've fixed some of the issues on found here, and then did some refactoring and simplification on the plugins.

Feel free to take a look:
https://github.com/kenjones-cisco/babun/tree/develop

**Comment by gliptak** [comment]
@kenjones-cisco Are you planning to publish releases? How can one try out your changes? Thanks

**Comment by kenjones-cisco** [comment]
Actually I was planning to setup AppVeyor tonight for doing automated builds, and doing a release using Github Releases.

**Comment by hegga** [comment]
Hi @kenjones-cisco! Any updates to this? I'd like to try out your changes.

**Comment by planesweep** [comment]
I think the project is dead. There some really annoying bugs. The project is more or less in BETA state.

**Comment by tombujok** [comment]
Not dead. Wanna help?
https://github.com/babun/babun/issues/810

**Comment by Xerus2000** [comment]
@kenjones-cisco will you ever submit these changes back to the main repo? As of now, I can't find a newer installation file in your repo.
