### ISSUE TITLE
git pull is broken

### ISSUE THREAD

**Issue by srinisoundar** [babun/babun#776]
After updating oh-my-zsh, I get the below error when I try to do a git pull.

fatal: 'pull' appears to be a git command, but we were not
able to execute it. Maybe git-pull is broken?

Note : I tried reinstalling babun but still the same error shows up. 

Could someone help ? thanks.

**Comment by ralberts** [comment]
I haven't seen a problem.  Have you tried running "git pull" from with in the git shell?  Does that work?  It might be useful to post the version of git you are using as well.  Also in babun if you could post the response from command "which git".

**Comment by srinisoundar** [comment]
Hi @ralberts  

Thanks for the reply. 

"git pull" was working in get shell and git --version returns 2.12.1
In babun "which git" returns /usr/bin/git and  git --version returns 2.1.4

Surprisingly the issue got resolved. I installed cygwin standalone for windows. Now I see it's working :)

Regards,
Srini
