### ISSUE TITLE
Is this project dead ?

### ISSUE THREAD

**Issue by melMass** [babun/babun#802]
Hello,

23 pull requests with some from more than 2 years ago.
Is babun still maintained ?

Coming from UNIX I can't seem to find the proper alternative with an active community.

**Comment by ulidtko** [comment]
Hey,

I'm just a passer-by, but I can tell that I've tried Babun once (shortly), and was tremendously disappointed by the quality.

Furthermore, the developer reaction was dismissing, mildly speaking. (Try and see yourself how my single issue went along #226).

With the best intentions, I'd recommend to avoid wasting your time here, and maybe try `msys2`. I'd walked away from Windows development for the time being; however I also heard some nice things about that thing from fellow engineers.

Hope that helps, and good luck!

**Comment by melMass** [comment]
Thanks for the clarification. 
I have to agree with him about diplomacy  (#226 ). 😉
