### ISSUE TITLE
Just use Gitshell people!

### ISSUE THREAD

**Issue by EddieOne** [babun/babun#809]
The effort is good here. However, a bunch of vb scripts and .bat files. I can see why it was abandoned. 

Install github desktop, in the options, use gitShell. It will pull in your keys from .ssh folder.

**Comment by sharpedavid** [comment]
Are you posting to the right project? I don't think Babun and Git Shell have anything to do with one another. There is almost no functionality overlap. Babun integrated Cygwin, oh-my-zsh, and lots of other stuff. Git Shell is "a login shell for SSH accounts to provide restricted Git access"; it is not a replacement for Cygwin or any similar project.

**Comment by EddieOne** [comment]
I think a lot of people are needing something better than windows powershell. It's so buggy, copy and paste is almost always in some form of a failed state. There's command prompt from windows 95 of course. Gitshell provides more than ssh as it emulates many of the bash functions, like scp, grep. So I guess it depends on the use case. If people are wanting a nice terminal to run python scripts or get a unix-like environment, I think gitshell is a good solution. I'm sure some may need things from the addons provided by babun, in that case gitshell won't work.
