### ISSUE TITLE
Is there any plan to support multi-tabs?

### ISSUE THREAD

**Issue by YoleYu** [babun/babun#81]
Babun is one of the most fatastic shell in Windows, but I want to more, want to know is  there any plan to support multi-tabs?

**Comment by AnthonyWC** [comment]
You can use screen; more powerful than multi-tabs.

**Comment by Frees** [comment]
You can use https://github.com/juho-p/fatty

**Comment by GraanJonlo** [comment]
I have tried to use screen but it doesn't seem to have any effect. It doesn't start but it doesn't error either
