### ISSUE TITLE
Project Not Dead. Looking for someone to create a script to download full cygwin mirror

### ISSUE THREAD

**Issue by tombujok** [babun/babun#810]
The real blocker for babun is the lack of versioning of cygwin mirros.
If we manage to download a full cygwin mirror and put it somewhere online we may proceed with the release of a new babun version.

Anybody can take care of that? TODO:

- [ ] download any of the mirrors (without x86_64 folder for now)
- [ ] find any free http hosting and put it somewhere online

**Comment by avishefi** [comment]
There are many cygwin mirrors, why can't babun rely on one of the public mirrors?

**Comment by tombujok** [comment]
The issue is that the mirror changes frequently. We want to have a stable unchanging snapshot.

**Comment by avishefi** [comment]
According to the following thread we need ~50GB of online storage:
https://cygwin.com/ml/cygwin/2014-03/msg00167.html

**Comment by tombujok** [comment]
@avishefi sounds good. I can organize the storage if no one arranges it, but the script to download it and verify each file's size is more of an issue for now.

**Comment by avishefi** [comment]
@tombujok initially I though scripting it with rsync, something [like this](http://magicmonster.com/kb/app/cygwin/rsync.html) only extended with size checking, but then I noticed [pmcyg](http://pmcyg.sourceforge.net/) which also verifies sizes and checksums.

I tested it with my own Cygwin installation using the following commands:
``` shell
mkdir cyg-mirror
cygcheck -cd | tail -n +3 | cut -f 1 -d " " > mypackages.txt
pmcyg-2.2/pmcyg.py --mirror=<mirror-url> --directory=cyg-mirror mypackages.txt
```
The `cygcheck` for generating the package list is optional, we can maintain a static list of packages / groups and have pmcyg download the latest snapshot from a mirror.

The size of the resulting repository is 250MB without source packages, it does size and hash checks and creates a Cygwin repository on a local directory that is suitable for burning into DVD/USB and to be used for offline installation.


What do you think?

**Comment by tombujok** [comment]
I think I like the rsync more, because we do not have a list of packages at hand. We would need to parse the setup.ini file somehow.  
I guess we could then validate with pmcyg right?

**Comment by NazarH** [comment]
I can help with hosting/storage, physical location - USA.

**Comment by avishefi** [comment]
Update - I have a working version, I will do some additional tests and send a gist

**Comment by tombujok** [comment]
@avishefi @NazarH could you work together to have it hosted on the storage @NazarH is oferring?

**Comment by avishefi** [comment]
A working version with rsync: https://gist.github.com/avishefi/8b765686f50af88deef8f344f1e82283
It went really slow so I split the file list with `split` and used `parallel` to utilize the bandwidth better.

I still have more work to do with the validation part, I will share it in a few days.

Running it against one of the European Cygwin mirrors results in a repository of about 40GB on disk.
The mirror parallelism parameter controls how many jobs parallel spawns, notice that some mirrors allow only one connection while others allow more.
I used mirror parallelism set to 3 on my tests, it took 10-12 hours to sync the entire repository from scratch.

**Comment by thomasklash** [comment]
@tombujok what is the status on this?
I can place the mirror on a 100/100 dedi if you like.

**Comment by tombujok** [comment]
@thomasklash That would be great. I don't know if the script prepared by @avishefi is 100% ready, but if you could take care of fixing & running it and then hosting the repo that would be great.

**Comment by avishefi** [comment]
@thomasklash I will send something you can execute on your mirror on the weekend.

**Comment by thomasklash** [comment]
Great!

**Comment by Slapbox** [comment]
This is an exciting development. I'm very hopeful.

**Comment by avishefi** [comment]
@thomasklash I created a Python gist that validates Cygwin's setup.ini
https://gist.github.com/avishefi/00642f50cd8644f6770c30449530ac6e

This, combined with the [previous shell script](https://gist.github.com/avishefi/8b765686f50af88deef8f344f1e82283) which rsync's with GNU Parallel an entire Cygwin distribution, will give you a synchronized mirror + a report of which packages do not comply with the repository's setup.ini.

**Comment by thomasklash** [comment]
@avishefi could you please explain what to pass in as the arguments for `$1` (mirror) `$2` (cygDist), and `$3` (mirrorParallelism)?

**Comment by avishefi** [comment]
Sure:

[sync_mirror.sh](https://gist.github.com/avishefi/8b765686f50af88deef8f344f1e82283) receives a cygwin mirror that supports rsync (notice that on the [Cygwin mirror list](https://cygwin.com/mirrors.html) it is noted which addresses support rsync), a path to a directory which it will create and sync the remote mirror to, and a level of parallelism to be passed to GNU Parallel so it knows how many parallel rsync processes to spawn.
Some mirrors only allow a certain amount of connections, some even only 1 in parallel.

[validate_packages.py](https://gist.github.com/avishefi/00642f50cd8644f6770c30449530ac6e) takes a full path to a directory where the Cygwin mirror was rsync'd to, and validates the setup.ini against the existing packages on that directory.

For example:
```
./sync_mirror.sh rsync://ftp.fau.de/cygwin/ /path/to/cygwin/repository/ 3
python validate_packages.py /path/to/cygwin/repository/
```

Let me know if you experience any issues.

**Comment by thomasklash** [comment]
I got it going :+1:

**Comment by thomasklash** [comment]
Output from `sync_mirror.sh`:
```
sent 184,180 bytes  received 2,044,607,167 bytes  5,144,129.17 bytes/sec
total size is 4,088,486,529  speedup is 2.00
local:0/30/100%/124.3s
Done
```

Output from `validate_packages.py`:
```
Scanning architecture: x86
=====================
Parsing setup.ini...
Validating 10317 packages...
Processed 500 packages
Processed 1000 packages
Processed 1500 packages
Processed 2000 packages
Processed 2500 packages
Processed 3000 packages
Processed 3500 packages
Processed 4000 packages
Processed 4500 packages
Processed 5000 packages
Processed 5500 packages
Processed 6000 packages
Processed 6500 packages
Processed 7000 packages
Processed 7500 packages
Processed 8000 packages
Processed 8500 packages
Processed 9000 packages
Processed 9500 packages
Processed 10000 packages
Found 0 package errors
Errors written to: /home/cygwin/tmp.bDHRvJB9wSwl/cygwin-rsync/x86_errors.json
=====================
```

The mirror can be found here:

http://solidus.rip/cyg/

**Comment by hojerst** [comment]
I create a mirror which hosts the same version (but without x86_64). Just to have a backup :)
http://babun-mirror.apps.redcube.de/

**Comment by avishefi** [comment]
@tombujok what are the next steps? are there any other tasks we can help with?

**Comment by tombujok** [comment]
Thx guys. Now I need to check if we still have free hosting from Azure and if Jenkins build server is still alive. It may take me a couple of days... Stay tunned.

**Comment by thomasklash** [comment]
What's going on? @tombujok

**Comment by avishefi** [comment]
@tombujok what are the next steps? can we help on releasing a new Babun version?

**Comment by thomasklash** [comment]
Looks like he went AWOL again :)

**Comment by avishefi** [comment]
How can we release a new version of Babun? @tombujok

**Comment by tombujok** [comment]
Sorry guys, busy times. We need a jenkins installation on a windows box to set up the build process.  I was trying to set it up, but with no luck, as all the server subscriptions I got a couple of years ago are expired. We would need to talk to some hosting company

**Comment by ssolidus** [comment]
@tombujok I have a server that I can deploy Jenkins to.

**Comment by tombujok** [comment]
That would be great. Then we could try to set up the build. It just needs to run on Windows.

**Comment by ssolidus** [comment]
@tombujok Do you have a direct message I could reach you from, in order to supply you credentials and so on?

**Comment by NazarH** [comment]
@tombujok Ping me if you still need help with hosting.

**Comment by ssolidus** [comment]
He's gone in the wind again

**Comment by claui** [comment]
Because it can’t be said often enough: a big, big thanks to all the people involved so far. ❤️ I’m grateful to see how you all are donating bandwidth, hosting space, and development time to get Babun back on track; it’s certainly going to be worth it. Looking forward to see a reliable package ecosystem emerge!

**Comment by tombujok** [comment]
@ssolidus great, ping me with the credentials to jenkins at bujokos [at] gmail.com

**Comment by lanfengp** [comment]
@tombujok  Any update? As a loyal user, I have been always waiting for the update.

**Comment by tombujok** [comment]
I never heard from anyone with any jenkins update.

**Comment by lanfengp** [comment]
@tombujok  Any update?

**Comment by Xerus2000** [comment]
Why do you need so much space tho? The cygwin in my .babun is not even a gigabyte big, and the setup barely a megabyte. What is all in there?

**Comment by aneagoe** [comment]
Silly question... but why not use appveyor? It's free for opensource projects...
https://www.appveyor.com/pricing/

By the looks of it, getting a Jenkins windows instance running somewhere seems quite an endeavor, not everyone can help with and the whole fiasco has to be repeated if/when the current one becomes unavailable or unmaintained.

**Comment by lanfengp** [comment]
Agree @ssolidus 's comment. 
Adding some more people into the maintenance group can help make this project much more stable. 
The current piles of unresolved issues make babun very frustrating to use.

**Comment by safinaskar** [comment]
There is Cygwin time machine: http://www.crouchingtigerhiddenfruitbat.org/cygwin/timemachine.html . So, it seems you don't need to setup your own service, it exists already.

But note that I currently cannot access it here, from Moscow. I was able to access it using https://fri-gate.org

**Comment by hojerst** [comment]
@safinaskar Thanks for the link - I didn't know that this even exists (I actually considered building something like this myself, but I don't really have the storage capacity - besides the time :) ).

That said, the fact that it costs me money to hosts the mirror and that there are little to none changes in the maintenance of this project, I will take down my babun cygwin mirror. Considering the better alternative at http://ctm.crouchingtigerhiddenfruitbat.org/pub/cygwin/circa/index.html, this shouldn't be a real loss for the project.

**Comment by NtH0** [comment]
@tombujok please? Life is miserable enough being forced to use Windows at work. Don't let babun die.

**Comment by dcpc007** [comment]
When i see simple bugs like #562 opened since 30 monthes, where someone send a patch in a basic script and ZERO action from the maintainer to accpet or refuse the solution... it's not a jenkins or infra problem...

**Comment by claui** [comment]
I would like to remind everyone involved that no maintainer owes us anything. Let’s accept that @tombujok may have moved on from GitHub, at least for now. I’d suggest we focus on a solution.

Would anyone of us be willing and able to take care of babun going forward?

@jlupi As a member of the babun org, do you have the power to appoint new maintainers? Or know someone who currently does?

**Comment by dcpc007** [comment]
He still often come and answers that it's not dead. If i understand last discussion it's because no more plateform to compile/test the code ?
but for some subject like the #562, it's a .bat file to modify to handle a trailing / in the install path ...

**Comment by dcpc007** [comment]
pitty i'm on linux, i'm learning devops (IT part) with Gitlab and look for testers with contents to implement a CI environment. but think i can't help for a windows project like here

**Comment by ssolidus** [comment]
@claui he may not owe anybody anything, but it is still rude and frustrating to instruct people willing to use their time and effort to do things for him, and then not respond.

**Comment by claui** [comment]
@ssolidus As an off-and-on Babun user who has no resources to contribute (neither Windows skills nor package hosting juice), I appreciate the hell out of everyone who volunteered, and who understandably grew frustrated over time. I feel your [recent comment](#issuecomment-394152187) was perfectly reasonable and helpful. (Considering its number of 👍s, I’m not the only one who agrees with you).

With that being said, I stand by my point:
Any further commitment to telling @tombujok, who is obviously on a GitHub sabbatical, how to run a project that is his and only his may be a waste of time.

Let’s:

1. figure out which of us wants to volunteer to commit to further development of babun and to assume leadership;

2. (politely) ask @jlupi and @tombujok whether they’re cool with adding a new maintainer to the babun org; **and**

3. accept their choice (or lack thereof), fork babun, and make it fly.

**Comment by tombujok** [comment]
@claui Thx Claudia.

I'll follow up with an announcement within 48h.

**Comment by saltyeyes** [comment]
I'm not sure if I missed something (quite possible, likely even) but I can't see any announcement?

**Comment by claui** [comment]
@tombujok bumpety bump?

**Comment by tombujok** [comment]
Let me comment on the following statement first:
`He may not owe anybody anything, but it is still rude and frustrating to instruct people willing to use their time and effort to do things for him, and then not respond.`

I easily spent more than a thousand of hours working on this project, absolutely for free, just for fun, and I do not owe anyone anything. It's rather the other way around, not matter what state the project is right now, and how often I show up online. Some respect would be appreciated. You all got it for free.

It is not rude and frustrating to ask the community to show a minimal effort to keep the project running. I won't comment on `to do things for him` as I think that person was too frustrated to think logically. Both tasks would take me 2h each, so I don't think anyone got screwed by working on them, especially that the effort may not be wasted, should these people be willing to contribute further (see below) There are a couple of people who seem to be pretty strongly involved here. Maybe they will be willing to work on the code instead of just commenting here.

Multiple times I asked the community who would be willing to contribute, but not by sending a small untested patch, that pretty frequently didn't work in any other use-case than the one that the person had in mind. I never found anyone who was willing to contribute for a longer period of time and their skills were on the level that I could have a minimal level of trust that the whole project did not collapse after 3 months of contributing. Updating `a simple bat file` means that there are several installation use-cases that have to be tested manually (each taking 30 minutes to run), but I'm sure people are well aware of that.

It's a damn tough project to work on even if it may not seem so for many of you. Cygwin has many quirks, not mentioning our beloved Windows environment. The build takes a long time, the installation takes even longer, if something doesn't work it's a hell of a process to find out where it broke and why - you pretty much need to know the codebase by heart to be fluent in it. There's no integration tests, which could make it a bit easier, but in order to have them we would need to code up an integration tests framework for babun. Any volunteers?

For multiple reasons, I do not have any time to work on the code, nor to browse the issues. What is more I do not even use babun anymore, which makes it pretty much impossible for me to run the project. AFAIK @jlupi is in a similar position. 

I could, however, answer questions related to the implementation, provided we could find people that would want to work on the project. I could commit to half an hour a week, maybe more should I see real flame in the persons eyes:) I can imagine @jlupi could cover some questions too.

In order not to let the project die we would need people who were willing to really take a deep dive into the code and start working on it. I mean it's like at least 10h-20h a week at the beginning. I used to spend at lease 20h a week for many months. It's a big workload, and the learning curve is really steep, especially at the beginning. It can be really frustrating - I really mean it. Once someone gets there however it's an enormous satisfaction, since the project has a lot of potential & users - and it's really easy to add small features with great value very quickly (also know as babun plugins).

In order to reactive the project I want to give you a full to-do list, so that you do not need to rely on me being online, and so that you may help each other achieve it:
1. someone needs to host a "frozen" mirror of cygwin repo, otherwise the repo changes too quickly, there is no stable state to work on,
2. someone needs to setup a jenkins server hosted on windows
3. someone needs to create a jenkins build that would produce the babun zip file, using the cygwin mirror hosted in ad.1. 
4. someone needs to test whether the produced babun.zip installer executes

I've created a hell lot of development documentation, e.g. here: http://babun.github.io/development.html
The build files are relatively easy to follow. Should be not that tough to accomplish steps 1 to 4. Anyone reaches that state, the project is ready to roll - but involvement of all of you is needed.
Otherwise forking is not a great idea, if it's tough for someone to successfully build the project from source...

Great so many people care about the project. Wish you all luck! Hope to see some results, but I'm not expecting anything - it's a free and open-source project after all!

**Comment by ssolidus** [comment]
@tombujok Had you said from the start what you just said above, none of the rest of the thread would have happened.

Also, I did some of those tasks for you to help you revive the project, which clearly you never had the time to do. From my perspective, it seemed as though you were ignoring or not responding to any requests to build the project.

Glad that it's all cleared up, but sad that we no longer will have Babun.

**Comment by NtH0** [comment]
Thanks for the info, @tombujok. I agree with @ssolidus, this could have been cleared from the beginning, your initial message in this thread gives a whole different idea about the future of babun, on which many of us, I assume, based our expectations.

> I do not have any time [...] to browse the issues

> I want to give you a full to-do list

Given that the second could take some time, could you start by giving a trusted user rw access to the issues for a clean-up?

**Comment by tombujok** [comment]
@NtH0 yep, could you guys elect someone? Are you interested in doing the first walk-through?

**Comment by claui** [comment]
Terms of the election are open for discussion until 2018-07-27 12:00:00 UTC.

**Comment by spiralofhope** [comment]
Why did a random bureaucrat appear?

Who controls babunvoting@cpellegrino.de and how is there any assurance this isn't rigged?

This whole thing feels like work to fuzz things over with an argument by verbosity-esque charade of red tape in order to have some random person appear out of thin air as our new and glorious leader.  I've seen people fly in, take over a project, install their friends, then politicize it.

Nice quick vote too.

No thanks, I'm out.

**Comment by claui** [comment]
> how is there any assurance this isn't rigged?

@spiralofhope ADoodle is one of the most popular services for anonymous voting. There are several others though. You think ADoodle is an elaborate scam set up by big Babun? Let’s choose a different anonymous voting service, then. Or let’s use GitHub’s 👍 reactions (but then the vote is no longer anonymous).

> Who controls babunvoting@cpellegrino.de

How does that matter?
This is only to collect your email address so you don’t have to disclose them here publicly. Feel free to do the latter if you prefer so.

> Why did a random bureaucrat appear?

Did you even read a single comment in this thread?

> Nice quick vote too.
> No thanks, I'm out.

Feel free to come up with another method, then.

**Comment by claui** [comment]
Election closed for now due to [lack of feedback](https://github.com/babun/babun/issues/845#issuecomment-410242390).

Maybe a simple 👍/👎 poll works better?

Anybody even interested in the role of maintainer?

**Comment by ssolidus** [comment]
@tombujok @claui I think the fact that the issue took so long to clarify, most people who were interested in seeing this project succeed have moved on. 

I have just started using Cygwin 64-bit. If the issues and transition were handled better, there probably would have been a few people who put their hands up, but it took a year to get here. I think you're out of luck.

**Comment by tombujok** [comment]
@ssolidus No, there was literally no-one to contribute. Easy to lash out on @claui who was among very few who tried to help.

Interested in contributing? Just send a bunch of PRs, do a deep-dive, don't complain and don't wait for elections. Easy.

**Comment by ouraios** [comment]
Windows Subsystem for Linux have now replaced Babun, that's all.

**Comment by ssolidus** [comment]
> 
> 
> @ssolidus No, there was literally no-one to contribute. Easy to lash out on @claui who was among very few who tried to help.
> 
> Interested in contributing? Just send a bunch of PRs, do a deep-dive, don't complain and don't wait for elections. Easy.

Hahaha, just ignoring the fact that you misled everyone by indicating you would resume development, and when people helped out as you requested, you didn't respond for months.

You're the one lashing out and finger pointing.
