### ISSUE TITLE
Make babun installable on an existing Cygwin instance

### ISSUE THREAD

**Issue by Schwolop** [babun/babun#83]
I don't know what should happen if Cygwin is detected, but a lot of things were broken out of the box when I installed Babun on a system that already had Cygwin. For a start, Babun didn't detect that zsh was an available shell, even though it definitely exists (because my original Cygwin install is using it.)

When I fiddled with a lot of the CYGWIN_PATH variables in scripts, and copied all of Babun's /usr/local/\* into my own Cygwin install it fixed most things. For whatever reason, I can't run pact properly as the repository host resolves but then 404s each file. I suspect a path problem here, but this discussion is going out of scope of this issue...

**Comment by jorgeorpinel** [comment]
Quick question, not really Babun-realted but topic-related:
Do you know whether Cygwin 32bit is OK to use on 64bit Windows systems anyway, or will it misbehave?
