### ISSUE TITLE
Electing a maintainer for babun

### ISSUE THREAD

**Issue by claui** [babun/babun#845]
## Edit July 27: Discussion prolonged until 2018-08-03

**I suggest that we continue discussing the terms of the election for one more week** due to a couple of issues raised.

### Issues and to-dos before we proceed

The following issues need to be sorted out before we can proceed:

- [ ] Decide whether a pre-election step should be added (@tombujok please decide)
- [ ] Decide whether a probation period should apply, during which PR merging is blocked until approved by an owner (@tombujok please decide)
- [ ] Improve transparency of the voting process (raised by @spiralofhope)

**Additionally, doubts were raised** as to whether or not I am trustworthy.
I’m at a loose end as to where these allegations come from. Even if it were my intention to rig the vote (or to try to “install a friend”, [according to a comment](
https://github.com/babun/babun/issues/810#issuecomment-408251961)), I have no idea how I would be able to do that technically and get away with it!
**Please point out any intransparencies** so we can fix them together.

With that being said, I’m **more than happy to let someone else** other than me organize the vote. That’d be great, less work for me then! I tried to design the process so it doesn’t matter who organizes the election. **Any volunteers, please step forward.**

(Original content below)
___

As someone not interested in the role of maintainer, I volunteer to organize the [election @tombujok has suggested](https://github.com/babun/babun/issues/810#issuecomment-407552624).

## Goal

The goal of this issue is to elect a new maintainer for babun by anonymous vote.

## Timeline of the election

- [x] Discuss the terms of this election by posting a comment here;
discussion **ends** ~~2018-07-27~~ **2018-08-03 12:00:00 UTC**
- [ ] Candidates register by introducing themselves via comment here;
registration **begins** ~~2018-07-27~~ **2018-08-03 12:00:00 UTC** and **ends** ~~2018-08-03~~ **2018-08-10 12:00:00 UTC**
- [ ] Voters react with 👍to this issue to register as a voter; also, every voter sends their email address and **their own GitHub username** to [babunvoting@cpellegrino.de](mailto:babunvoting@cpellegrino.de);
registration **begins** ~~2018-07-27~~ **2018-08-03 12:00:00 UTC** and **ends** ~~2018-08-03~~ **2018-08-10 12:00:00 UTC**
- [ ] **Voting begins** ~~2018-08-03~~ **2018-08-10** shortly after 12:00:00 UTC when voters receive an email from `no_reply@adoodle.org` containing a link
- [ ] **Voting ends** ~~2018-08-06~~ **2018-08-13 12:00:00 UTC**; results are announced here
- [ ] I delete from my system all the email addresses and GitHub usernames I gathered earlier

## Terms of the election

- Voting is anonymous, and will be held on [https://www.adoodle.org/](https://www.adoodle.org/).
- Everyone who has commented on, or reacted to, #810 before [this comment was posted](https://github.com/babun/babun/issues/810#issuecomment-407552624) has the right to vote.
- Voters must react with 👍to this issue to register, and send their email address and GitHub username to [babunvoting@cpellegrino.de](mailto:babunvoting@cpellegrino.de);
- The vote will be conducted on [https://www.adoodle.org/](https://www.adoodle.org/), with @tombujok and me registered as observers
- Results will be published anonymously at adoodle.org, and will also be posted here after voting ends.

## Privacy

Email addresses sent to me will not be made public. I will share them only with adoodle.org so they can send the voting link; adoodle.org’s privacy policy will apply. GitHub usernames sent to me via email will not be made public. I will correlate them to 👍reactions and email addresses in order to verify that everyone gets only one vote. After the election is over, I will delete from my system all the email addresses and GitHub usernames I gathered earlier.

**Comment by tombujok** [comment]
Sounds good @claui. Not much traction though... :(
One question: what if none of the candidates who registered themselves has any experience in technologies that are required to maintain babun? I would maybe include a pre-election step, where non-suitable candidates are removed.

**Comment by claui** [comment]
I feel the most important thing is to find someone willing to commit to doing regular maintenance in the first place.

I can imagine that triaging and responding to PRs and issues may require different skills. Not every action will depend on a level of Babun knowledge that only you have right now. I feel we shouldn’t worry too much about lack of Babun-specific experience; given enough hours, that experience will come.

While I’m fine with a pre-election step, I’m not sure how we’re going to tell in advance how quickly the candidate will actually develop the technical skills you mentioned.

Another way to keep an eye on code quality would be to configure the repo so PR merging is blocked unless at least one owner (i. e. you) approves the PR. Would this address your doubts?

That workflow implies you’d still have to be involved but only minimally; the new maintainer would still be responsible for triaging and getting PRs ready to merge. So the maintainer would only mention you in the small fraction of cases where the PR is actually ready to be merged.

Which approach would you prefer?

**Comment by claui** [comment]
Let’s continue discussing the terms of the election **until 2018-08-03 12:00:00 UTC** due to issues raised.

I have updated the description to reflect the changed dates, the issues, and the to-dos.

**Comment by claui** [comment]
Closing this due to lack of feedback, and because we’re past the (already extended) deadline.

@tombujok Feel free to reopen anytime you like, and I’ll be happy to pick up where we left off.
