### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by DanielRuf** [babun/babun#868]
Is this project still maintained?

**Comment by vmario89** [comment]
no :-(. please see the previous issues

**Comment by JustAShoeMaker** [comment]
It was a nice project, ran relatively issue free, but it would be nice if there was a way to flag projects as litter or if the dev would say, tired now, anyone else want to try? and hand it over...

**Comment by tombujok** [comment]
Yep, it's dead, litter, <use your own synonym>, whatever. Easy to complain, huh?

I was trying to find maintainers but with not luck. Everyone just prefers to grab what's there online for free, but if any involvement is required they are just uninterested and are first to complain about litter.

Good luck with any other tools you may find out there. If you don't contribute to them or pay for them, they will end up like babun pretty soon anyway.

**Comment by DanielRuf** [comment]
> I was trying to find maintainers but with not luck. Everyone just prefers to grab what's there online for free, but if any involvement is required they are just uninterested and are first to complain about litter.
> 
> Good luck with any other tools you may find out there. If you don't contribute to them or pay for them, they will end up like babun pretty soon anyway.

Exactly.
What could be the next possible steps? Is there currently enough interest to find active maintainers?

**Comment by mg64ve** [comment]
Obviously a project like this require a proper number of active maintainers.
I guess it requires a lot of activities

**Comment by lorvent** [comment]
sad to hear.

many people may not have enough skills to contribute, thats why they just litter instead of contributing.

how about adding a patreon or gitstore.app

**Comment by brenc** [comment]
Great project. It's a shame maintainers couldn't be found. Thank you for updating the README on GitHub to let us know that this project has been discontinued. Could http://babun.github.io/ be updated with this new information as well? If I didn't know to specifically go looking at the GitHub, I would never have known that the project was discontinued. Thanks!

**Comment by DVCoder** [comment]
> > I was trying to find maintainers but with not luck. Everyone just prefers to grab what's there online for free, but if any involvement is required they are just uninterested and are first to complain about litter.
> > Good luck with any other tools you may find out there. If you don't contribute to them or pay for them, they will end up like babun pretty soon anyway.
> 
> Exactly.
> What could be the next possible steps? Is there currently enough interest to find active maintainers?

Agreed with everything said. Babun is one of the most useful tool I have used and sad to see that it is discontinued. In the future if there opportunity to help, I would like to be notified. And assist in any way I can.

**Comment by saberone** [comment]
> Yep, it's dead, litter, , whatever. Easy to complain, huh?
> 
> I was trying to find maintainers but with not luck. Everyone just prefers to grab what's there online for free, but if any involvement is required they are just uninterested and are first to complain about litter.
> 
> Good luck with any other tools you may find out there. If you don't contribute to them or pay for them, they will end up like babun pretty soon anyway.

Hang on a minute. I'd be more than willing to pay for Babun. And I think if you put up something it would generate some money too.

I find babun very useful, and I was pleasantly suprised by it. Came late to the party.

**Comment by QGB** [comment]
but WSL is only for Windows 10 ：)

**Comment by kapitanluffy** [comment]
Took the liberty in adding it in [maintainers wanted](https://github.com/pickhardt/maintainers-wanted). I hope we can continue this project :)

**Comment by juanitogan** [comment]
... and I still have trouble with regex ^ and $ in WSL, so I can't switch to WSL yet.  Apparently, this is due the difference in line-ending handling between Cygwin and WSL (WSL is a mess here, in my opinion).

**Comment by ismailhkose** [comment]
> Yep, it's dead, litter, , whatever. Easy to complain, huh?
> 
> I was trying to find maintainers but with not luck. Everyone just prefers to grab what's there online for free, but if any involvement is required they are just uninterested and are first to complain about litter.
> 
> Good luck with any other tools you may find out there. If you don't contribute to them or pay for them, they will end up like babun pretty soon anyway.

@tombujok
Thanks for all of the contributions so far.
As an Owner of the project, Would you mind to send an email to Cygwin, MinGW e-mail list if anyone wants to maintain or merge to Cygwin or MingGW?

**Comment by kypes** [comment]
This makes me really sad ☹
Thank you for everything throughout the years 🙏

**Comment by JustAShoeMaker** [comment]
@tombujok Really wasn't meant to insult, but more along the lines of providing folks with a way to know a project is dead. And it can happen for a million reasons. But yes, disappointment after investing some affection into it is one of them.

**Comment by cardil** [comment]
I was sad to hear that when I noticed change in README as babun was a great help.

If someone here is looking for an alternative. I've switched back to native cygwin64 + https://github.com/kou1okada/apt-cyg and been using that for couple of months.

**Comment by Aeres-u99** [comment]
;_; ;_; Only if I were a bit better. is there any way by which we can revive the project? I will provide what all assistance I can. I am a newbie at programming, but I am ready to learn and try to revive the the good ol' and the best babun. Please give me a chance and I shall give my best to do what all I can.

**Comment by rbreaves** [comment]
I definitely appreciate projects like this one and am sad to see there's a lack of maintainers out there for it. It's not too surprising though, between WSL and the fact that many Windows devs I know would rather not be bothered to learn cygwin or babun and the powerful tools a linux/unix/posix based system can provide them. And that's probably also the rub, anyone that appreciates Babun are probably linux or mac users who are forced to use Windows at work, but want/need a better terminal to get their work done.

**Comment by sentrychris** [comment]
Hi @tombujok, firstly I'd like to say thank you very much for developing and maintaining Babun, it was one of the first tools I used while learning the UNIX command line.

I'm sorry to hear you couldn't find maintainers, I remember you raising the issue a while back but I didn't really have the knowledge to help, but it's been a while since then, so if you're looking to revive the project I'd love to help?

**Comment by CerebralMischief** [comment]
> This makes me really sad ☹
> Thank you for everything throughout the years 🙏
> I use babun alongside WSL to update my choco packages etc.

While I can see the reason for work on this to end it doesn't change the fact that it's unfortunate and sad news.  I've been using this for a while now and wish I had the bandwidth to contribute as I'd rather not see this mothballed.

**Comment by CerebralMischief** [comment]
> Yep, it's dead, litter, , whatever. Easy to complain, huh?
> 
> I was trying to find maintainers but with not luck. Everyone just prefers to grab what's there online for free, but if any involvement is required they are just uninterested and are first to complain about litter.
> 
> Good luck with any other tools you may find out there. If you don't contribute to them or pay for them, they will end up like babun pretty soon anyway.

Thank you very much for all the time you devoted to this project!  I wish others were a bit more understanding as it truly is easier to cast stones vs. actually putting the effort into maintaining a project like this and it's level of complexity.  I sincerely appreciate the awesomeness this tool is and thank you very much for all your hard work.  I wish you all the best and hopefully contributors can be rustled up.

**Comment by slibbe** [comment]
Sad news even though reasonable. Babun was so much more handy in use than cygwin64 it's based on.

**Comment by moonwitch** [comment]
I completely lack the technical know-how to contribute, but I wouldn't have minded paying though. Honestly. But I respect your decision, obviously. And I just responded here to show you the respect and gratitude.

**Comment by joanbarros** [comment]
Sad to hear, I wouldn't mind chipping in some dev time, but from the outside it's really hard to figure out where my efforts would be better applied.

Is there a way for us to coordinate on things that need to get done?

**Comment by altimmons** [comment]
I loved Babun.  It was a bit under the radar- a bit discrete.  But it really was excellent.  It was like someone configured Cygwin for you like a pro would have it set up, but for a noob like me.  Yet, as a noob, I lack the requisite skill to contribute.

I do think with time that Babun would become the fav over vanilla Cyg or MingW or MSys2.  

There are a lot of great tools out there - this being one of them, but they are exhausting and (importantly) non-paying.  Its the dark side of FOSS - paying rent...

**Comment by sebthom** [comment]
Anyone interested, you can try https://github.com/vegardit/cygwin-portable-installer as a potential alternative

**Comment by rbonvall** [comment]
I just found out the project is discontinued. I just wanted to chime in to share my appreciation for the contributors. I have been a happy user of babun for six years. Thanks for your work!

**Comment by Jeklah** [comment]
I would happily lend what skills I have to maintain this. I have used this shell setup for a long time and would be more than happy to contribute and possibly bring it back to life if more maintainers are found.

**Comment by Aeres-u99** [comment]
I too am ready to provide assistance. Just give us some initial guidelines and we will take over This project doesnt deserves to die.

**Comment by mjhd** [comment]
Have to say - I don't like the idea of a "litter" tag since it's not always clear that a project is meant to be actively maintained - if people don't look at the most recent commits and make a judgement call it's kinda on them frankly...

**Comment by sukhchain9935** [comment]
I would have contributed, but I don't know if I have the skills for it or not.

**Comment by fxtentacle** [comment]
@tombujok I know I'm super late to the party, but I just wanted to say thank you.

I only noticed this thread today, because today was the first time I needed to DuckDuck something related to my Babun install. For me, it has "just worked" since 2016.

I'm always happy to pay for my JetBrains subscription and I use Babun equally often. Looking back, maybe you should have charged for it.

**Comment by Avec112** [comment]
I actually use Babun even today on both Win 7 and Win 10. I have met one big hurdle and that was updating Git. Back then I thought my time with Babun was over. However I found an solution by deleting `.\babun\bin\git.exe` and then you can install `Git Bash` which will provide you with an updated Git version. Whenever I want to update Git I just install an newer version of `Git Bash`.

**Comment by Jefa-saucedev** [comment]
I always encounter issues trying to download the shell.

**Comment by pa-0** [comment]
Late to the party but maybe consider adding a `FUNDING.yaml` to the repository for the hell of it (along with a short corresponding invitation), to see if there are enough people out there interested enough to fund Babun's resurrection?

**Comment by Jeklah** [comment]
Thanks, but yes a little late. I've since switched to Ubuntu fully to do my
work on.
