### ISSUE TITLE
proxy fails with some corporate proxy

### ISSUE THREAD

**Issue by simonbasle** [babun/babun#95]
I'm not sure which proxy is used where I work but it seems to be a corporate windows proxy, which is autoconfigured. I managed to find out the configuration (host and port) but couldn't make it work in babun...

after numerous tries, including giving my username and password in the proxy url (with several different syntaxes, with or without domain name, etc...), I was stuck. I noticed in the logs that the proxy still asked me for authentication when testing with a random `pact install tar`, so basic authentication is probably not compatible with this proxy :(

**Comment by hippias** [comment]
I finally got it working with the following **.wgetrc** file in the home directory:
**proxy_user**=*PROXY_USER_VALUE*
**proxy_password**=*PROXY_USER_PASSWORD_VALUE*
**http_proxy**=*PROXY_URL*
**no_proxy**=localhost,127.0.0.1

I could not explain why using the standard way of configuring proxy in babun did not work out.

**Comment by debovema** [comment]
Thanks @hippias for the workaround with .wgetrc :smile_cat:

**Comment by gravaton** [comment]
I had an issue with my corporate proxy as well, it was related to the aliasing of "curl" and "wget" to force them to override the user agent.  Seeing what looks like a modern browser, my proxy attempts to do pass-through Windows authentication and then fails.  I am unaware of situations/environments in which overriding this user agent is desirable (although they might be out there!) but perhaps making it more clear/visible that it's going on and providing an easy method to disable it would be preferable?

**Comment by b-luu** [comment]
Had similar problem and solved just putting `ask_password=on` in my .wgetrc and entering my password when prompted during pact install and co.

**Comment by hairlessbear** [comment]
Modifying the `USER_AGENT` environment variable worked for me. babun [uses one](https://github.com/babun/babun/blob/832a55bbb4c2f9354378b7847fb1d76ecc5f7d57/babun-core/plugins/core/src/babun.rc#L23) that is flagged as unsafe (i.e. out-of-date) by my proxy (which is fair since it's the agent string for [IE 9](http://www.useragentstring.com/pages/useragentstring.php?name=Internet+Explorer)). Modifying it to be any other string (as long as it's not another out-of-date user agent) or just commenting the line out in `.babunrc` fixes the error.

**Comment by danorr** [comment]
Found hardcoding the username and password in the ~/.babunrc file also worked. Not ideal but added the following details:

export http_proxy=http://USERNAME:PASSWORD@proxy:PORT_NUM

Update the username, password, proxy, and port_num. 

Then run >>> source ~/.babunrc
In my case, there wasn't an update to download so could remove the details and re-enable it when there was.
