### ISSUE TITLE
No way to copy/paste into vim

### ISSUE THREAD

**Issue by organman91** [babun/babun#97]
It's possible I'm doing it wrong, but right-clicking while at the prompt dumps the contents of the clipboard into the shell, but in vim does nothing.

**Comment by pgrm** [comment]
just a comment for future references - I managed to copy it out of vim with `"*Y` and paste into another vim windows with `"*P`

**Comment by ihadanny** [comment]
Guys, sorry, the "*p" doesn't copy from the windows clipboard, instead it uses some mysterious internal babun clipboard. Couldn't get it to work. 
Right click is way more intuitive and works in vim both in cygwin AND when I ssh from babun to a linux box, and open VIM there :)
Can I please re-open this?

**Comment by oysteinkrog** [comment]
I've fixed msys2 vim so that windows clipboard works, use msys2 instead of babun.

**Comment by ihadanny** [comment]
seriously?! you mean uninstall babun and install msys2 for everything? or
do you mean there's some way to use msys2 vim from inside babun?

**Comment by oysteinkrog** [comment]
Msys2 has lots of packages (use pacman to install them), so you can setup whatever system you want.
You can't use msys2 packages from inside babun as babun is not msys2.
Having said that.. I don't understand quite why the cygwin vim in babun2 does not handle windows clipboard.. it should be possible to get that working.
Msys2 itself is basically cygwin+mods+a really nice package manager.

**Comment by TheKas** [comment]
Try it with the following parameters

```bash
echo "set mouse-=a" >> ~/.vimrc~
```

**Comment by ihadanny** [comment]
It works! small correction:

echo "set mouse-=a" >> ~/.vimrc

(without the trailing ~)


On 16 June 2015 at 14:56, Kaspar Janowsky <notifications@github.com> wrote:

> Try it with the following parameters
>
> echo "set mouse-=a" >> ~/.vimrc~
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babun/babun/issues/97#issuecomment-112398367>.
>



-- 
Sent from my androido

**Comment by ihadanny** [comment]
opening a stackoverflow for this question, please answer here for
posterity:
http://stackoverflow.com/questions/30883413/babun-copy-paste-from-windows-clipboard-into-vim


On 17 June 2015 at 08:59, Ido Hadanny <ido.hadanny@gmail.com> wrote:

> It works! small correction:
>
> echo "set mouse-=a" >> ~/.vimrc
>
> (without the trailing ~)
>
>
> On 16 June 2015 at 14:56, Kaspar Janowsky <notifications@github.com>
> wrote:
>
>> Try it with the following parameters
>>
>> echo "set mouse-=a" >> ~/.vimrc~
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/babun/babun/issues/97#issuecomment-112398367>.
>>
>
>
>
> --
> Sent from my androido
>



-- 
Sent from my androido

**Comment by dragon788** [comment]
Using "*p or "+p is pretty normal for those used to *nix systems (Linux and OSX). Mouse mode is definitely the best way to get right click pasting working. Sometimes you also have to edit the mintty settings to determine how the mouse will behave.

**Comment by firmlyjin** [comment]
enter below chartor to  ~/.vimrc
map <C-c> "+y 
map <C-v> "+p

**Comment by DavidAwad** [comment]
You may find other solutions to pasting in babun by holding down shift when you right click and looking at the menu. 

For example, `shift + insert` is a keyboard shortcut that works for me, while it's not great I'm much happier with that than `shift + mouse click`!

**Comment by adgnaf** [comment]
> 
> 
> In my cygwin+vim setup I need to use the vim "paste from system command".
> "*p
> Basically * is the system clipboard register.
> More info here:
> http://vim.wikia.com/wiki/Accessing_the_system_clipboard

This solution works in msys2 vim.
