### ISSUE TITLE
Publish to Chocolatey package repo

### ISSUE THREAD

**Issue by mcandre** [babun/babun#99]
So that Windows users can install babun with `cinst babun`.

http://chocolatey.org/

**Comment by tombujok** [comment]
Closed due to inactivity.

**Comment by Chris2011** [comment]
Sry? What do you mean with inactivity?

**Comment by tugberkugurlu** [comment]
I wouldn't close this. I would leave it open, mark with [`up-for-grabs`](http://up-for-grabs.net/#/) label.
